const GREENWAVE_VERSION="v1.33-charge-price-availability-app-links";
const SKEY="greenwave_dk_settings_v2",HKEY="greenwave_dk_history_v2",EKEY="greenwave_dk_ev_planner_v1";
const EV_PLANNER_PROFILES={renaultMeganeETech:{id:"renaultMeganeETech",name:"Renault Megane E-Tech EV40",usableBatteryKwh:40,defaultConsumptionKwh100:17,notes:"40 kWh batteri. Forbrug er justerbart."}};
const state={map:null,userMarker:null,destinationMarker:null,routeLine:null,routeGlow:null,fuelMarkers:[],currentPosition:null,destination:null,originalDestination:null,temporaryChargeDestination:null,route:null,selectedAutocomplete:null,autocompleteTimer:null,stations:[],lastEvPlannerSuggestions:[],lastChargingList:[],history:[],evWeather:null,evDetailsOpen:false,myRenault:{ok:false,status:"not-connected",message:"MyRenault ikke tilsluttet. Manuel batteristatus bruges."},settings:{mobilityType:"fuel",chargeProvider:"all",fuelType:"benzin95",maxFuelDetourMeters:2000,fuelAlongMeters:50000,fuelSort:"cheapest",routeMode:"fast",avoidFerries:false}};
const els={},ids=["map","destinationInput","goBtn","autocompleteResults","historySection","historyList","settingsBtn","settingsBackdrop","settingsModal","closeSettingsBtn","saveSettingsBtn","fuelTypeSelect","fuelDetourSelect","fuelAlongSelect","fuelSortSelect","routeModeSelect","statusText","reasonText","recalcBtn","routeDistance","routeDuration","routeEta","fuelRefreshBtn","fuelSummary","fuelList"];
document.addEventListener("DOMContentLoaded",()=>{ids.forEach(id=>els[id]=document.getElementById(id));removeLegacyDrivingUi();initChargingUi();initEvPlannerUi();ensureRouteBatteryBoxes();ensureChargeStopBanner();bind();loadSettings();ensureFuelAlongOptions();loadHistory();initMap();syncSettingsUi();setFuelPanelMode();renderHistory();renderEvPlanner();renderChargeStopBanner();refreshMyRenaultStatus();setStatus("Klar");});
function bind(){on(els.destinationInput,"input",()=>{state.selectedAutocomplete=null;clearTimeout(state.autocompleteTimer);state.autocompleteTimer=setTimeout(searchAutocomplete,250);});on(els.goBtn,"click",calculateRoute);on(els.recalcBtn,"click",calculateRoute);on(els.fuelRefreshBtn,"click",refreshFuel);on(els.settingsBtn,"click",openSettings);on(els.closeSettingsBtn,"click",closeSettings);on(els.settingsBackdrop,"click",closeSettings);on(els.saveSettingsBtn,"click",saveSettings);document.addEventListener("click",e=>{const chargeStopButton=e.target.closest(".charge-stop-google-action");if(chargeStopButton){openGoogleAndSelectChargeStop(chargeStopButton);return;}if(e.target.closest("#continueDestinationBtn")){continueToOriginalDestination();return;}if(e.target.closest("#clearChargeStopBtn")){clearChargeStop();return;}if(!e.target.closest(".search-card")&&!e.target.closest(".autocomplete"))hideAutocomplete();});}
function on(el,ev,fn){if(el)el.addEventListener(ev,fn);}
function removeLegacyDrivingUi(){document.querySelector(".gw")?.remove();document.getElementById("startBtn")?.remove();document.getElementById("stopBtn")?.remove();if(els.reasonText)els.reasonText.textContent="EV Planner bruger rute, batteri og vejr til at beregne ladebehov.";const actions=document.querySelector(".actions");if(actions&&!actions.querySelector("button"))actions.remove();}
function initChargingUi(){const body=document.querySelector("#settingsModal .settings-body");if(body&&!document.getElementById("mobilityTypeSelect")){const type=document.createElement("section");type.innerHTML='<h3>Type</h3><select id="mobilityTypeSelect"><option value="fuel">Brændstof</option><option value="charging">Ladning</option></select>';body.prepend(type);const charge=document.createElement("section");charge.innerHTML='<h3>Ladning</h3><label>Ladeleverandør</label><select id="chargeProviderSelect"><option value="all">Alle</option><option value="clever">Clever</option><option value="eon">E.ON</option><option value="spirii">Spirii</option><option value="norlys">Norlys</option><option value="ok">OK</option><option value="q8f24">Q8/F24</option><option value="circlek">Circle K</option><option value="tesla">Tesla</option><option value="ionity">Ionity</option><option value="unox">Uno-X</option><option value="unknown">Andre/ukendt</option></select>';const routeSection=[...body.querySelectorAll("section")].find(s=>/Rute/i.test(s.textContent||""));body.insertBefore(charge,routeSection||null);}ensureAvoidFerriesControl();els.mobilityTypeSelect=document.getElementById("mobilityTypeSelect");els.chargeProviderSelect=document.getElementById("chargeProviderSelect");els.avoidFerriesToggle=document.getElementById("avoidFerriesToggle");on(els.mobilityTypeSelect,"change",()=>{state.settings.mobilityType=els.mobilityTypeSelect.value;setFuelPanelMode();if(state.route)refreshFuel();});on(els.chargeProviderSelect,"change",()=>{state.settings.chargeProvider=els.chargeProviderSelect.value;setFuelPanelMode();renderCharging();drawFuelMarkers();renderEvPlanner();});}
function initEvPlannerUi(){
  ensureEvPlannerStyles();
  const panel=document.querySelector(".panel");
  if(!panel||document.getElementById("evPlanner"))return;
  const card=document.createElement("section");
  card.id="evPlanner";
  card.className="fuel ev-planner";
  card.innerHTML=`<header><h2>EV Planner v1</h2></header><div class="ev-profile-note">Bilprofil: Renault Megane E-Tech EV40 · 40 kWh batteri · forbrug kan justeres.</div><div id="myRenaultStatus" class="ev-planner-note">MyRenault ikke tilsluttet · Manuel batteristatus bruges.</div><div id="evWeatherStatus" class="ev-planner-note">Automatisk vejr: afventer rute.</div><div class="ev-planner-grid"><label>Bilprofil<select id="evProfileSelect"><option value="renaultMeganeETech">Renault Megane E-Tech EV40</option></select></label><label>Start-SoC %<input id="evStartSocInput" type="number" min="0" max="100" step="1"></label><label>Minimum-SoC %<input id="evMinSocInput" type="number" min="0" max="50" step="1"></label><label>Rutedistance km<input id="evRouteDistanceInput" type="number" min="0" step="0.1"></label><label>Basisforbrug kWh/100 km<input id="evConsumptionInput" type="number" min="5" max="35" step="0.1"></label><label>Temperatur °C<input id="evTemperatureInput" type="number" min="-30" max="45" step="1"></label><label>Vind km/t<input id="evWindInput" type="number" min="0" max="120" step="1"></label><label>Nedbør<select id="evPrecipitationSelect"><option value="none">Ingen/tørt</option><option value="rain">Regn</option><option value="heavyRain">Kraftig regn</option><option value="snow">Sne/slud</option></select></label><label>Vejtype<select id="evRoadTypeSelect"><option value="mixed">Blandet</option><option value="city">By</option><option value="country">Landevej</option><option value="highway">Motorvej</option></select></label></div><div id="evPlannerSummary" class="ev-planner-summary"></div><button id="evDetailsToggle" class="ev-details-toggle" type="button" hidden>Vis EV-detaljer</button><div id="evPlannerSuggestions" class="ev-planner-suggestions"></div>`;
  const fuel=document.querySelector(".fuel");
  panel.insertBefore(card,fuel||null);
  els.evProfileSelect=document.getElementById("evProfileSelect");
  els.evStartSocInput=document.getElementById("evStartSocInput");
  els.evMinSocInput=document.getElementById("evMinSocInput");
  els.evRouteDistanceInput=document.getElementById("evRouteDistanceInput");
  els.evConsumptionInput=document.getElementById("evConsumptionInput");
  els.evTemperatureInput=document.getElementById("evTemperatureInput");
  els.evWindInput=document.getElementById("evWindInput");
  els.evPrecipitationSelect=document.getElementById("evPrecipitationSelect");
  els.evRoadTypeSelect=document.getElementById("evRoadTypeSelect");
  els.evPlannerSummary=document.getElementById("evPlannerSummary");
  els.evDetailsToggle=document.getElementById("evDetailsToggle");
  els.evPlannerSuggestions=document.getElementById("evPlannerSuggestions");
  els.myRenaultStatus=document.getElementById("myRenaultStatus");
  els.evWeatherStatus=document.getElementById("evWeatherStatus");
  loadEvPlannerSettings();
  syncEvPlannerUi();
  [els.evProfileSelect,els.evStartSocInput,els.evMinSocInput,els.evRouteDistanceInput,els.evConsumptionInput,els.evTemperatureInput,els.evWindInput,els.evPrecipitationSelect,els.evRoadTypeSelect].forEach(el=>on(el,"input",()=>handleEvPlannerInput(el)));
  [els.evProfileSelect,els.evStartSocInput,els.evMinSocInput,els.evRouteDistanceInput,els.evConsumptionInput,els.evTemperatureInput,els.evWindInput,els.evPrecipitationSelect,els.evRoadTypeSelect].forEach(el=>on(el,"change",()=>handleEvPlannerInput(el)));
  on(els.evDetailsToggle,"click",()=>{state.evDetailsOpen=!state.evDetailsOpen;renderEvPlanner();});
}
function defaultEvPlannerSettings(){const profile=EV_PLANNER_PROFILES.renaultMeganeETech;return{profileId:profile.id,startSoc:80,minSoc:15,routeDistanceKm:"",consumptionKwh100:profile.defaultConsumptionKwh100,temperatureC:10,windKmh:10,precipitation:"none",roadType:"mixed"};}
function loadEvPlannerSettings(){try{state.evPlanner={...defaultEvPlannerSettings(),...JSON.parse(localStorage.getItem(EKEY)||"{}")};}catch{state.evPlanner=defaultEvPlannerSettings();}}
function saveEvPlannerSettings(){state.evPlanner={profileId:els.evProfileSelect?.value||"renaultMeganeETech",startSoc:numPlannerInput(els.evStartSocInput,80),minSoc:numPlannerInput(els.evMinSocInput,15),routeDistanceKm:els.evRouteDistanceInput?.value||"",consumptionKwh100:numPlannerInput(els.evConsumptionInput,EV_PLANNER_PROFILES.renaultMeganeETech.defaultConsumptionKwh100),temperatureC:numPlannerInput(els.evTemperatureInput,10),windKmh:numPlannerInput(els.evWindInput,10),precipitation:els.evPrecipitationSelect?.value||"none",roadType:els.evRoadTypeSelect?.value||"mixed"};try{localStorage.setItem(EKEY,JSON.stringify(state.evPlanner));}catch{}}
function syncEvPlannerUi(){const v=state.evPlanner||defaultEvPlannerSettings();if(els.evProfileSelect)els.evProfileSelect.value=v.profileId||"renaultMeganeETech";if(els.evStartSocInput)els.evStartSocInput.value=String(v.startSoc??80);if(els.evMinSocInput)els.evMinSocInput.value=String(v.minSoc??15);if(els.evRouteDistanceInput)els.evRouteDistanceInput.value=v.routeDistanceKm||"";if(els.evConsumptionInput)els.evConsumptionInput.value=String(v.consumptionKwh100??EV_PLANNER_PROFILES.renaultMeganeETech.defaultConsumptionKwh100);if(els.evTemperatureInput)els.evTemperatureInput.value=String(v.temperatureC??10);if(els.evWindInput)els.evWindInput.value=String(v.windKmh??10);if(els.evPrecipitationSelect)els.evPrecipitationSelect.value=v.precipitation||"none";if(els.evRoadTypeSelect)els.evRoadTypeSelect.value=v.roadType||"mixed";}
function handleEvPlannerInput(el){if(el===els.evTemperatureInput||el===els.evWindInput||el===els.evPrecipitationSelect)state.evWeather=null;saveEvPlannerSettings();renderEvPlanner();}
function syncEvPlannerRouteDistance(force){if(!els.evRouteDistanceInput||!state.route?.distance)return;const current=String(els.evRouteDistanceInput.value||"").trim();if(force||!current){els.evRouteDistanceInput.value=(Number(state.route.distance)/1000).toFixed(1);saveEvPlannerSettings();}}
function evPlannerInputs(){const profile=EV_PLANNER_PROFILES[els.evProfileSelect?.value]||EV_PLANNER_PROFILES.renaultMeganeETech;const routeInput=numPlannerInput(els.evRouteDistanceInput,null);const routeDistanceKm=Number.isFinite(routeInput)&&routeInput>0?routeInput:(state.route?.distance?Number(state.route.distance)/1000:0);const myRenault=usableMyRenaultStatus();const autoWeather=usableEvWeather();const manualStartSoc=Math.max(0,Math.min(100,numPlannerInput(els.evStartSocInput,80)));const minSoc=Math.max(0,Math.min(80,numPlannerInput(els.evMinSocInput,15)));const manualWeather={temperatureC:Math.max(-30,Math.min(45,numPlannerInput(els.evTemperatureInput,10))),windKmh:Math.max(0,Math.min(120,numPlannerInput(els.evWindInput,10))),precipitation:els.evPrecipitationSelect?.value||"none"};const weather=autoWeather||manualWeather;return{profile,startSoc:myRenault?myRenault.soc:manualStartSoc,manualStartSoc,startSocSource:myRenault?"myrenault":"manual",myRenault,minSoc,routeDistanceKm,consumptionKwh100:Math.max(5,Math.min(35,numPlannerInput(els.evConsumptionInput,profile.defaultConsumptionKwh100))),temperatureC:weather.temperatureC,windKmh:weather.windKmh,precipitation:weather.precipitation,weatherSource:autoWeather?"automatic":"manual",weatherMessage:autoWeather?.message||state.evWeather?.message||"Manuel vejrinput bruges.",roadType:els.evRoadTypeSelect?.value||"mixed"};}
function usableMyRenaultStatus(){const soc=Number(state.myRenault?.soc??state.myRenault?.batterySoc??state.myRenault?.batteryLevel);return state.myRenault?.ok&&!state.myRenault?.stale&&isValidSoc(soc)?{soc,status:state.myRenault.status||"connected",ageMinutes:state.myRenault.ageMinutes,timestamp:state.myRenault.timestamp,batteryAutonomy:state.myRenault.batteryAutonomy}:null;}
function usableEvWeather(){const w=state.evWeather?.weather;if(!state.evWeather?.ok||!w)return null;const temperatureC=Number(w.temperatureC),windKmh=Number(w.windKmh);return{temperatureC:Number.isFinite(temperatureC)?Math.max(-30,Math.min(45,temperatureC)):10,windKmh:Number.isFinite(windKmh)?Math.max(0,Math.min(120,windKmh)):10,precipitation:w.precipitation||precipitationFromWeather(w),message:state.evWeather.message||"Automatisk vejr fra Open-Meteo."};}
function precipitationFromWeather(w){const snow=Number(w.snowfallMm),rain=Number(w.rainMm),precip=Number(w.precipitationMm);if(Number.isFinite(snow)&&snow>0.05)return"snow";const wet=Math.max(Number.isFinite(rain)?rain:0,Number.isFinite(precip)?precip:0);if(wet>=2)return"heavyRain";if(wet>0.05)return"rain";return"none";}
function applyAutoWeatherToInputs(){const w=usableEvWeather();if(!w)return;if(els.evTemperatureInput)els.evTemperatureInput.value=String(Math.round(w.temperatureC));if(els.evWindInput)els.evWindInput.value=String(Math.round(w.windKmh));if(els.evPrecipitationSelect)els.evPrecipitationSelect.value=w.precipitation;saveEvPlannerSettings();}
async function refreshMyRenaultStatus(){state.myRenault={ok:false,status:"loading",message:"Henter batteristatus fra MyRenault..."};renderEvPlanner();try{const r=await fetch("/api/myrenault-status",{cache:"no-store"});const d=await r.json().catch(()=>({}));const level=Number(d.batteryLevel);if(r.ok&&d.ok&&!d.stale&&isValidSoc(level)){state.myRenault={...d,ok:true,batteryLevel:level,soc:level,message:"Batteristatus fra MyRenault"};}else{state.myRenault={...d,ok:false,status:d.status||"unavailable",message:d.message||"MyRenault ikke tilsluttet · Manuel batteristatus bruges.",batteryLevel:isValidSoc(level)?level:null,stale:Boolean(d.stale),ageMinutes:d.ageMinutes??null,timestamp:d.timestamp||null};}}catch(e){console.warn("MyRenault status unavailable:",e.message);state.myRenault={ok:false,status:"error",message:"MyRenault ikke tilsluttet · Manuel batteristatus bruges.",stale:true};}renderEvPlanner();}
function updateEvExternalStatus(plan){if(els.myRenaultStatus){if(plan.myRenault){els.myRenaultStatus.textContent=`Batteristatus fra MyRenault: ${formatSocSpaced(plan.startSoc)}${myRenaultUpdatedLabel(plan.myRenault)?` · senest opdateret ${myRenaultUpdatedLabel(plan.myRenault)}`:""}.`;}else if(state.myRenault?.stale&&isValidSoc(state.myRenault?.batteryLevel)){els.myRenaultStatus.textContent=`MyRenault batteristatus er gammel: ${formatSocSpaced(state.myRenault.batteryLevel)}${myRenaultUpdatedLabel(state.myRenault)?` · senest opdateret ${myRenaultUpdatedLabel(state.myRenault)}`:""}. Manuel batteristatus bruges.`;}else els.myRenaultStatus.textContent=state.myRenault?.message||"MyRenault ikke tilsluttet · Manuel batteristatus bruges.";}if(els.evWeatherStatus){if(plan.weatherSource==="automatic")els.evWeatherStatus.textContent=`Automatisk vejr aktivt · ${weatherInputLabel(plan)}.`;else els.evWeatherStatus.textContent=state.evWeather?.status==="error"?"Automatisk vejr ikke tilgængeligt · manuel vejrinput bruges.":"Automatisk vejr afventer rute · manuel vejrinput bruges.";}}
function calculateEvPlanner(){const v=evPlannerInputs();const batteryKwh=Number(v.profile.usableBatteryKwh);const routeProfile=plannerRouteProfile(v.routeDistanceKm);const routeRoadConsumptionKwh100=routeProfile.available?routeRoadConsumption(v.consumptionKwh100,routeProfile):v.consumptionKwh100;const weatherFactor=calculateEvWeatherFactor(v,!routeProfile.available);const adjustedConsumptionKwh100=routeRoadConsumptionKwh100*weatherFactor;const energyNeededKwh=v.routeDistanceKm*adjustedConsumptionKwh100/100;const socUsed=batteryKwh>0?energyNeededKwh/batteryKwh*100:null;const arrivalSoc=Number.isFinite(socUsed)?v.startSoc-socUsed:null;const reservePercentPoints=Number.isFinite(arrivalSoc)?arrivalSoc-v.minSoc:null;const safeEnergyKwh=Math.max(0,(v.startSoc-v.minSoc)/100*batteryKwh);const safeRangeKm=adjustedConsumptionKwh100>0?safeEnergyKwh/adjustedConsumptionKwh100*100:0;const missingPercentPoints=Number.isFinite(reservePercentPoints)?Math.max(0,-reservePercentPoints):0;const missingKwh=missingPercentPoints/100*batteryKwh;return{...v,batteryKwh,routeProfile,routeRoadConsumptionKwh100,weatherFactor,adjustedConsumptionKwh100,energyNeededKwh,socUsed,arrivalSoc,reservePercentPoints,safeRangeKm,missingKwh,missingPercentPoints,needsCharge:Number.isFinite(arrivalSoc)&&arrivalSoc<v.minSoc};}
function plannerRouteProfile(routeDistanceKm){const profile=state.route?.roadProfile;if(profile?.available)return profile;const distance=Number(state.route?.distance),duration=Number(state.route?.duration);if(distance>0&&duration>0)return buildAverageSpeedRouteProfile(distance,duration,"route-average-fallback");return{available:false,source:"manual-road-type",cityKm:0,ruralKm:0,motorwayKm:0,unknownKm:Math.max(0,Number(routeDistanceKm)||0),totalKm:Math.max(0,Number(routeDistanceKm)||0),percentages:{city:0,rural:0,motorway:0,unknown:100}};}
function routeRoadConsumption(base,profile){const total=Number(profile?.totalKm)||0;if(!profile?.available||total<=0)return Number(base)||0;const city=Number(profile.cityKm)||0,rural=Number(profile.ruralKm)||0,motorway=Number(profile.motorwayKm)||0,unknown=Number(profile.unknownKm)||0;return(city*base*0.90+rural*base+motorway*base*1.18+unknown*base)/total;}
function renderEvPlanner(){if(!els.evPlannerSummary||!els.evPlannerSuggestions)return;const plan=calculateEvPlanner();updateEvExternalStatus(plan);renderRouteBatteryBoxes(plan);syncEvDetailsVisibility(plan);if(!plan.routeDistanceKm){els.evPlannerSummary.innerHTML=`<div class="ev-planner-empty">Indtast rutedistance eller beregn en rute for at planlægge batteriet.</div>`;els.evPlannerSuggestions.innerHTML="";state.lastEvPlannerSuggestions=[];return;}const arrivalText=Number.isFinite(plan.arrivalSoc)?formatSocRaw(plan.arrivalSoc):"--";const status=plan.needsCharge?"Batteriet rækker ikke":"Batteriet rækker";const level=plan.needsCharge?"warn":"ok";const reserveText=Number.isFinite(plan.reservePercentPoints)?`Estimeret reserve ved ankomst er ca. ${Math.max(0,plan.reservePercentPoints).toFixed(0).replace(".",",")} procentpoint.`:"Reserve kunne ikke beregnes.";const missingText=`Mangler ca. ${formatKwh(plan.missingKwh)} / ${plan.missingPercentPoints.toFixed(0).replace(".",",")} procentpoint.`;els.evPlannerSummary.innerHTML=`<div class="ev-compact-summary"><strong>${esc(plan.profile.name)} · ${plan.profile.usableBatteryKwh} kWh</strong><span>Start: ${formatSoc(plan.startSoc)} · Minimum: ${formatSoc(plan.minSoc)}</span><span>Forventet ankomst: ${arrivalText}</span><span>${esc(routeProfileLabel(plan))}</span><span>Justeret forbrug: ${formatKwh100(plan.adjustedConsumptionKwh100)}</span><span>Beregnet ud fra ${plan.routeProfile?.available?"ruteprofil + vejr":"valgt vejtype + vejr"}</span><span>Ruteenergi: ${formatKwh(plan.energyNeededKwh)}</span><span>${compactWeatherLabel(plan)}</span></div><div class="ev-planner-status" data-level="${level}">${status}. ${plan.needsCharge?missingText:reserveText}</div>`;renderEvPlannerSuggestions(plan);}
function syncEvDetailsVisibility(plan){const hasCalculatedRoute=Boolean(state.route?.distance&&plan.routeDistanceKm);const compact=hasCalculatedRoute&&!state.evDetailsOpen;document.getElementById("evPlanner")?.classList.toggle("ev-compact",compact);if(els.evDetailsToggle){els.evDetailsToggle.hidden=!hasCalculatedRoute;els.evDetailsToggle.textContent=state.evDetailsOpen?"Skjul EV-detaljer":"Vis EV-detaljer";}}
function compactWeatherLabel(plan){const source=plan.weatherSource==="automatic"?"Automatisk vejr":"Manuelt vejr";return `${source}: ${Math.round(Number(plan.temperatureC)||0)}°C, ${Math.round(Number(plan.windKmh)||0)} km/t vind`;}
function renderEvPlannerSuggestions(plan){if(!els.evPlannerSuggestions)return;if(!plan.needsCharge){els.evPlannerSuggestions.innerHTML="";state.lastEvPlannerSuggestions=[];return;}const result=evPlannerChargingSuggestions(plan);const explanation=`<div class="ev-planner-note">Forslagene viser første mulige ladestop inden beregnet rækkevidde.${plan.needsCharge?" Senere ladestop beregnes først efter første ladestop.":""}</div>`;if(!result.items.length){state.lastEvPlannerSuggestions=[];els.evPlannerSuggestions.innerHTML=`${explanation}<div class="ev-planner-status" data-level="warn">${esc(result.message)}</div>`;return;}state.lastEvPlannerSuggestions=result.items;const note=result.message?`<div class="ev-planner-note">${esc(result.message)}</div>`:"";els.evPlannerSuggestions.innerHTML=`<h3>Foreslåede ladepunkter inden ca. ${fmtDist(plan.safeRangeKm*1000)}</h3>${explanation}${note}${result.items.map((p,i)=>{const priceInfo=getChargerPriceInfo(p),availabilityInfo=getChargerAvailabilityInfo(p),operatorLink=getOperatorAppLink(p);const meta=[p.provider||"Ukendt leverandør",p.powerKw?`${p.powerKw} kW`:"",`${fmtDist(p.distanceAlongRoute)} langs ruten`,`${fmtDist(p.distanceToRoute)} fra ruten`].filter(Boolean).join(" · ");return `<article class="fuel-item"><div class="fuel-title"><span>${esc(p.name||"Ladepunkt")}</span><span class="fuel-price">${esc(priceInfo.badge)}</span></div><div class="fuel-meta">${esc(meta)}</div>${chargerPriceMarkup(priceInfo)}${chargerAvailabilityMarkup(availabilityInfo)}<div class="charge-stop-actions"><button type="button" class="charge-stop-google-action" data-list="suggestions" data-index="${i}">Åbn i Google og vælg</button>${operatorLinkMarkup(operatorLink)}</div></article>`;}).join("")}`;
}
function evPlannerChargingSuggestions(plan){if(state.settings.mobilityType!=="charging")return{items:[],message:"Skift Type til Ladning og hent ladepunkter langs ruten for konkrete ladestop."};const selected=state.settings.chargeProvider||"all";const allPoints=dedupeChargingPoints(state.stations||[]).filter(isUsableChargingSuggestionPoint);const points=selected==="all"?allPoints:allPoints.filter(p=>p.providerKey===selected);if(!allPoints.length)return{items:[],message:"Ingen ladepunkter er hentet endnu. Tryk Opdater ladepunkter."};if(!points.length)return{items:[],message:"Ingen egnede ladepunkter fundet for valgt leverandør."};const safeRangeMeters=Math.max(0,Number(plan.safeRangeKm||0)*1000);const preferredMin=safeRangeMeters*0.70,preferredMax=safeRangeMeters*0.97,target=safeRangeMeters*0.85;const reachable=points.filter(p=>Number(p.distanceAlongRoute)<=safeRangeMeters);if(!reachable.length)return{items:[],message:selected==="all"?"Ingen egnede ladepunkter fundet før minimum-SoC-grænsen.":"Ingen egnede ladepunkter fundet for valgt leverandør."};const usefulReachable=preferUsefulChargingPower(reachable);const preferred=usefulReachable.filter(p=>Number(p.distanceAlongRoute)>=preferredMin&&Number(p.distanceAlongRoute)<=preferredMax);const fallback=usefulReachable.filter(p=>Number(p.distanceAlongRoute)<preferredMin||Number(p.distanceAlongRoute)>preferredMax);const usingPreferred=preferred.length>0;const pool=usingPreferred?preferred:fallback;const message=usingPreferred?"":fallback.some(p=>Number(p.distanceAlongRoute)<preferredMin)?`Tidligt ladestop foreslået, fordi der ikke blev fundet bedre senere ladepunkt${selected==="all"?"":" for valgt leverandør"}.`:"Ladestop ligger tæt på minimum-SoC-grænsen; kør med ekstra margin.";const items=[...pool].sort((a,b)=>usingPreferred?sortPreferredChargeStop(a,b,target):sortFallbackChargeStop(a,b)).slice(0,5);return{items,message};}
function selectedChargingProviderLabel(key){const option=[...(els.chargeProviderSelect?.options||[])].find(item=>item.value===key);return option?.textContent||key;}
function chargingMapsLinks(point){const lat=Number(point?.lat),lng=Number(point?.lng);const coords=Number.isFinite(lat)&&Number.isFinite(lng)?`${lat},${lng}`:"";const navigationUrl=coords?`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(coords)}&travelmode=driving`:"https://www.google.com/maps/search/?api=1&query=ladestation";const name=String(point?.name||"").trim();const provider=String(point?.provider||"").trim();const address=[point?.address,point?.street,point?.postalCode||point?.postal_code,point?.city].map(value=>String(value||"").trim()).filter(Boolean).join(" ");if(coords&&!name&&!provider&&!address)return{searchUrl:navigationUrl,navigationUrl};const generic=chargingPlaceNameIsGeneric(name,provider);const preciseParts=generic&&!address?[coords]:[name,provider,address,"elbil ladestation",coords];const query=preciseParts.filter(Boolean).join(" ")||coords||"ladestation";return{searchUrl:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`,navigationUrl};}
function chargingPlaceNameIsGeneric(name,provider){const a=String(name||"").trim().toLowerCase(),b=String(provider||"").trim().toLowerCase();if(!a)return true;if(a===b)return true;return["clever","ionity","circle k","ok","norlys","spirii","tesla","e.on","q8/f24","uno-x"].includes(a);}
function dedupeChargingPoints(points){const kept=[];for(const point of points){const duplicate=kept.find(item=>sameChargingProvider(point,item)&&sameChargingSite(point,item));if(!duplicate){kept.push(point);continue;}if(chargingPointDataScore(point)>chargingPointDataScore(duplicate)){kept[kept.indexOf(duplicate)]=point;}}return kept;}
function sameChargingProvider(a,b){return String(a?.providerKey||a?.provider||"unknown").toLowerCase()===String(b?.providerKey||b?.provider||"unknown").toLowerCase();}
function sameChargingSite(a,b){const alat=Number(a?.lat),alng=Number(a?.lng),blat=Number(b?.lat),blng=Number(b?.lng);return Number.isFinite(alat)&&Number.isFinite(alng)&&Number.isFinite(blat)&&Number.isFinite(blng)&&distanceMeters(alat,alng,blat,blng)<=50;}
function chargingPointDataScore(point){return(Number(point.powerKw)||0)+(isValidChargePrice(point.priceKwh)?1000:0)+(point.connectorType?10:0)+chargingPointNameScore(point);}
function chargingPointNameScore(point){const name=String(point?.name||"").trim();return Math.min(name.length,80)+(point?.provider?20:0);}
function isUsableChargingSuggestionPoint(p){return Number.isFinite(Number(p.distanceAlongRoute))&&Number.isFinite(Number(p.distanceToRoute))&&Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng))&&(p.providerKey||p.connectorType||p.powerKw||"priceKwh"in p);}
function chargingPowerTier(point){const kw=Number(point?.powerKw||0);if(kw>=300)return 5;if(kw>=150)return 4;if(kw>=50)return 3;if(kw>=22)return 2;if(kw>=11)return 1;return 0;}
function preferUsefulChargingPower(points){const best=Math.max(...points.map(chargingPowerTier));if(best>=3)return points.filter(p=>chargingPowerTier(p)>=3);if(best>=2)return points.filter(p=>chargingPowerTier(p)>=2);if(best>=1)return points.filter(p=>chargingPowerTier(p)>=1);return points;}
function sortPreferredChargeStop(a,b,target){return Math.abs(Number(a.distanceAlongRoute)-target)-Math.abs(Number(b.distanceAlongRoute)-target)||Number(b.powerKw||0)-Number(a.powerKw||0)||Number(a.distanceToRoute||0)-Number(b.distanceToRoute||0);}
function sortFallbackChargeStop(a,b){return Number(b.distanceAlongRoute||0)-Number(a.distanceAlongRoute||0)||Number(b.powerKw||0)-Number(a.powerKw||0)||Number(a.distanceToRoute||0)-Number(b.distanceToRoute||0);}
function calculateEvWeatherFactor(plan,includeManualRoadType=true){let factor=1;const temp=Number(plan.temperatureC),wind=Number(plan.windKmh);if(temp<0)factor+=0.20+Math.min(0.10,Math.abs(temp)*0.006);else if(temp<5)factor+=0.12;else if(temp<10)factor+=0.06;else if(temp>30)factor+=0.08;else if(temp>25)factor+=0.04;if(wind>10)factor+=Math.min(0.15,(wind-10)*0.003);factor+=({none:0,rain:0.07,heavyRain:0.12,snow:0.20}[plan.precipitation]??0);if(includeManualRoadType)factor+=({city:-0.07,mixed:0,country:0.04,highway:0.16}[plan.roadType]??0);return Math.max(0.85,Math.min(1.60,factor));}
function routeProfileLabel(plan){const p=plan.routeProfile;if(!p?.available)return`Ruteprofil ikke tilgængelig — bruger valgt vejtype (${roadTypeLabel(plan.roadType)})`;const pct=p.percentages||{};const parts=[`${formatPct(pct.motorway)} motorvej`,`${formatPct(pct.rural)} landevej`,`${formatPct(pct.city)} by`];if(Number(pct.unknown)>0.5)parts.push(`${formatPct(pct.unknown)} ukendt`);return`Ruteprofil estimeret ud fra rutehastighed: ${parts.join(" · ")}`;}
function formatPct(value){const n=Number(value);return`${Number.isFinite(n)?Math.round(n):0} %`;}
function weatherInputLabel(plan){const road=plan.routeProfile?.available?"":`, ${roadTypeLabel(plan.roadType)}`;return `${Math.round(plan.temperatureC)}°C, ${Math.round(plan.windKmh)} km/t vind, ${precipitationLabel(plan.precipitation)}${road}`;}
function precipitationLabel(value){return{none:"tørt",rain:"regn",heavyRain:"kraftig regn",snow:"sne/slud"}[value]||"tørt";}
function roadTypeLabel(value){return{city:"by",mixed:"blandet vej",country:"landevej",highway:"motorvej"}[value]||"blandet vej";}
function ensureEvPlannerStyles(){if(document.getElementById("ev-planner-style"))return;const style=document.createElement("style");style.id="ev-planner-style";style.textContent=".ev-planner{margin-top:12px}.ev-profile-note,.ev-planner-note,.ev-planner-empty{color:var(--muted);font-size:13px}.ev-planner-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin-top:12px}.ev-planner-grid label{display:block;color:var(--muted);font-size:12px;text-transform:uppercase}.ev-planner-grid input,.ev-planner-grid select{width:100%;margin-top:6px;background:#111f33;border:1px solid #31425d;border-radius:14px;padding:11px}.ev-compact .ev-planner-grid,.ev-compact .ev-profile-note,.ev-compact #myRenaultStatus,.ev-compact #evWeatherStatus{display:none}.ev-compact-summary{display:grid;gap:4px;margin-top:10px;color:#dce8f8}.ev-compact-summary strong{color:#fff;font-size:15px}.ev-compact-summary span{color:var(--muted);font-size:13px}.ev-details-toggle{margin-top:10px;background:transparent;border:1px solid var(--line);border-radius:12px;color:#d7ffe3;padding:9px 12px;font-weight:800}.ev-planner-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px;margin-top:12px}.ev-planner-kpis div,.ev-planner-status{background:#101d2f;border:1px solid var(--line);border-radius:16px;padding:12px}.ev-planner-kpis span{display:block;color:var(--muted);font-size:11px;text-transform:uppercase}.ev-planner-kpis strong{display:block;margin-top:3px;font-size:20px;color:#fff}.ev-planner-status{margin-top:10px;color:#dce8f8}.ev-planner-status[data-level=ok]{border-color:rgba(57,228,123,.55)}.ev-planner-status[data-level=warn]{border-color:rgba(255,194,102,.65);color:#ffe3ad}.ev-planner-suggestions h3{margin:14px 0 4px;color:var(--muted);font-size:13px;text-transform:uppercase}@media(max-width:720px){.ev-planner-grid{grid-template-columns:1fr 1fr}.ev-planner-grid label:first-child{grid-column:1/-1}}";document.head.appendChild(style);}
function ensureRouteUiStyles(){if(document.getElementById("route-ev-ui-style"))return;const style=document.createElement("style");style.id="route-ev-ui-style";style.textContent=".trip.trip-with-battery{grid-template-columns:repeat(6,minmax(0,1fr))}.trip div[data-range-level=ok]{border-color:rgba(57,228,123,.65);background:rgba(57,228,123,.10)}.trip div[data-range-level=warn]{border-color:rgba(255,214,102,.70);background:rgba(255,214,102,.12)}.trip div[data-range-level=caution]{border-color:rgba(255,149,64,.80);background:rgba(255,149,64,.13)}.trip div[data-range-level=danger]{border-color:rgba(255,93,93,.85);background:rgba(255,93,93,.14)}.charge-stop-banner{margin:12px 0;background:#101d2f;border:1px solid rgba(57,228,123,.35);border-radius:16px;padding:12px;color:#dce8f8}.charge-stop-banner strong,.charge-stop-banner span{display:block}.charge-stop-banner span{color:var(--muted);font-size:13px;margin-top:4px}.charge-stop-warning{color:#ffe3ad!important}.charge-price-line,.charge-availability-line{margin-top:8px;color:#fff;font-weight:800}.charge-stop-actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin-top:10px}.charge-stop-actions button{background:#39e47b;color:#05210f;border:0;border-radius:12px;padding:9px 12px;font-weight:900}.charge-stop-actions #clearChargeStopBtn{background:transparent;color:#dce8f8;border:1px solid var(--line)}.charge-stop-actions a{color:#d7ffe3;font-weight:800;text-decoration:none}.charge-stop-actions .charge-operator-link{border:1px solid var(--line);border-radius:12px;padding:9px 12px}.charge-stop-actions .charge-operator-link:hover{border-color:rgba(57,228,123,.7)}@media(max-width:720px){.trip.trip-with-battery{grid-template-columns:repeat(2,minmax(0,1fr))}.charge-stop-actions{display:grid;grid-template-columns:1fr}.charge-stop-actions button,.charge-stop-actions a{width:100%;text-align:center}}";document.head.appendChild(style);}
function ensureRouteBatteryBoxes(){const trip=document.querySelector(".trip");if(!trip)return;ensureRouteUiStyles();trip.classList.add("trip-with-battery");if(!document.getElementById("routeBatteryCurrent"))trip.insertAdjacentHTML("beforeend",'<div><span>Aktuel batteri</span><strong id="routeBatteryCurrent">--</strong></div><div><span>Ved destination</span><strong id="routeBatteryArrival">--</strong></div>');if(!document.getElementById("routeBatteryRange"))trip.insertAdjacentHTML("beforeend",'<div><span>Rækkevidde</span><strong id="routeBatteryRange">--</strong></div>');els.routeBatteryCurrent=document.getElementById("routeBatteryCurrent");els.routeBatteryArrival=document.getElementById("routeBatteryArrival");els.routeBatteryRange=document.getElementById("routeBatteryRange");}
function renderRouteBatteryBoxes(plan){ensureRouteBatteryBoxes();if(!els.routeBatteryCurrent||!els.routeBatteryArrival||!els.routeBatteryRange)return;const current=Number(plan?.startSoc);const arrival=Number(plan?.arrivalSoc);const safeRange=Number(plan?.safeRangeKm);els.routeBatteryCurrent.textContent=isValidSoc(current)?formatSocSpaced(current):"--";els.routeBatteryArrival.textContent=plan?.routeDistanceKm&&Number.isFinite(arrival)?formatSocRawSpaced(arrival):"--";els.routeBatteryRange.textContent=Number.isFinite(safeRange)&&safeRange>0?`${Math.round(safeRange)} km`:"--";const rangeBox=els.routeBatteryRange.closest("div");if(rangeBox){const level=routeBatteryRangeLevel(plan);if(level)rangeBox.dataset.rangeLevel=level;else delete rangeBox.dataset.rangeLevel;}}
function routeBatteryRangeLevel(plan){const safeRange=Number(plan?.safeRangeKm),targetKm=Number(state.route?.distance)/1000;if(!Number.isFinite(safeRange)||safeRange<=0||!Number.isFinite(targetKm)||targetKm<=0)return"";const marginPercent=(safeRange-targetKm)/safeRange*100;if(marginPercent>15)return"ok";if(marginPercent>=10)return"warn";if(marginPercent>=5)return"caution";return"danger";}
function ensureChargeStopBanner(){const trip=document.querySelector(".trip");if(!trip)return;ensureRouteUiStyles();let banner=document.getElementById("chargeStopBanner");if(!banner){banner=document.createElement("section");banner.id="chargeStopBanner";banner.className="charge-stop-banner";banner.hidden=true;trip.insertAdjacentElement("afterend",banner);}els.chargeStopBanner=banner;}
function renderChargeStopBanner(){ensureChargeStopBanner();const banner=els.chargeStopBanner;if(!banner)return;const stop=state.temporaryChargeDestination;if(!stop){banner.hidden=true;banner.innerHTML="";return;}const original=state.originalDestination;const warning=String(stop.rangeWarning||"").trim();banner.hidden=false;banner.innerHTML=`<strong>Midlertidig destination: ${esc(destinationLabel(stop)||"Ladestop")}</strong><span>Efter ladestop: ${esc(destinationLabel(original)||"Oprindelig destination mangler")}</span>${warning?`<span class="charge-stop-warning">${esc(warning)}</span>`:""}<div class="charge-stop-actions"><button type="button" id="continueDestinationBtn">Fortsæt til slutdestination</button><button type="button" id="clearChargeStopBtn">Fjern ladestop</button></div>`;}
function destinationLabel(dest){return String(dest?.label||dest?.displayName||dest?.name||"").trim();}
function hasCoordinates(dest){return Number.isFinite(Number(dest?.lat))&&Number.isFinite(Number(dest?.lng));}
function chargePointLabel(point){const name=String(point?.name||"").trim(),provider=String(point?.provider||"").trim();return[name,provider].filter(Boolean).join(" · ")||"Ladestop";}
function isCurrentTemporaryChargeDestination(query,dest){const stop=state.temporaryChargeDestination;if(!stop||!hasCoordinates(stop)||!hasCoordinates(dest))return false;const sameCoords=Math.abs(Number(stop.lat)-Number(dest.lat))<0.000001&&Math.abs(Number(stop.lng)-Number(dest.lng))<0.000001;const sameLabel=destinationLabel(stop)&&destinationLabel(stop)===String(query||"").trim();return sameCoords||sameLabel;}
function numPlannerInput(el,fallback){const n=Number(String(el?.value??"").replace(",","."));return Number.isFinite(n)?n:fallback;}
function isValidSoc(value){const n=Number(value);return Number.isFinite(n)&&n>=0&&n<=100;}
function formatSoc(value){return `${Math.round(Math.max(0,Math.min(100,Number(value)||0)))}%`;}
function formatSocSpaced(value){return `${Math.round(Math.max(0,Math.min(100,Number(value)||0)))} %`;}
function formatSocRaw(value){const n=Number(value);return Number.isFinite(n)?`${Math.round(n)}%`:"--";}
function formatSocRawSpaced(value){const n=Number(value);return Number.isFinite(n)?`${Math.round(n)} %`:"--";}
function formatKwh(value){const n=Number(value);return Number.isFinite(n)?`${n.toFixed(1).replace(".",",")} kWh`:"-- kWh";}
function formatKwh100(value){return `${Number(value).toFixed(1).replace(".",",")} kWh/100 km`;}
function formatSignedPercent(value){const n=Number(value);const sign=n>0?"+":"";return `${sign}${n.toFixed(0).replace(".",",")}%`;}
function initMap(){if(typeof L==="undefined"){setStatus("Kort kunne ikke indlæses.");return;}state.map=L.map("map",{zoomControl:false,attributionControl:false,preferCanvas:true});L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{subdomains:"abcd",maxZoom:20}).addTo(state.map);state.map.setView([55.6761,12.5683],10);}
async function searchAutocomplete(){const q=els.destinationInput.value.trim();if(q.length<2){hideAutocomplete();return;}try{const r=await fetch(`/api/geocode?q=${encodeURIComponent(q)}&limit=6&mode=suggest`,{cache:"no-store"});const d=await r.json();const items=Array.isArray(d)?d:(d.results||[]);if(!items.length){hideAutocomplete();return;}els.autocompleteResults.innerHTML=items.map((it,i)=>{const label=it.displayName||it.label||"Ukendt adresse",p=splitAddress(label);return `<button type="button" data-index="${i}"><strong>${esc(p.title)}</strong><small>${esc(p.subtitle)}</small></button>`;}).join("");els.autocompleteResults.classList.remove("hidden");[...els.autocompleteResults.querySelectorAll("button")].forEach(b=>b.addEventListener("click",()=>{const it=items[Number(b.dataset.index)],label=it.displayName||it.label||"Destination",p=splitAddress(label);state.selectedAutocomplete={lat:Number(it.lat),lng:Number(it.lng??it.lon),label:p.title,displayName:label};els.destinationInput.value=p.title;hideAutocomplete();}));}catch(e){console.warn(e);hideAutocomplete();}}
function hideAutocomplete(){els.autocompleteResults?.classList.add("hidden");}
async function calculateRoute(){const q=els.destinationInput.value.trim();if(!q){alert("Indtast en destination.");return;}try{const dest=state.selectedAutocomplete||await geocode(q);const keepTemporary=isCurrentTemporaryChargeDestination(q,dest);if(!keepTemporary){state.originalDestination=null;state.temporaryChargeDestination=null;}renderChargeStopBanner();await routeToKnownDestination(dest,{save:!keepTemporary});}catch(e){console.error(e);setStatus(`Fejl: ${e.message}`);}}
async function routeToKnownDestination(dest,{save=false}={}){try{setStatus("Finder position og beregner rute...");if(els.goBtn)els.goBtn.disabled=true;if(els.recalcBtn)els.recalcBtn.disabled=true;if(els.fuelRefreshBtn)els.fuelRefreshBtn.disabled=true;const pos=await getCurrentPosition();state.currentPosition=pos;updateCurrentMarker(pos,true);state.destination=dest;updateDestinationMarker(dest);if(save){saveHistory(dest);renderHistory();}const route=await fetchRoute(pos,dest);await applyRoute(route);if(els.recalcBtn)els.recalcBtn.disabled=false;if(els.fuelRefreshBtn)els.fuelRefreshBtn.disabled=false;setStatus(state.settings.mobilityType==="charging"?"Rute klar. Henter ladepunkter...":"Rute klar. Henter tankstationer...");await refreshFuel();}catch(e){console.error(e);setStatus(`Fejl: ${e.message}`);}finally{if(els.goBtn)els.goBtn.disabled=false;}}
function chargeStopPointFromButton(button){const index=Number(button?.dataset?.index);const list=button?.dataset?.list==="charging"?state.lastChargingList:state.lastEvPlannerSuggestions;return Number.isInteger(index)&&index>=0?list?.[index]:null;}
function chargeStopSelectionProblem(point){if(!state.route)return"Lav en rute først for at bruge ladestop.";if(!point||!hasCoordinates(point))return"Ladepunktet mangler koordinater.";const original=state.originalDestination||state.destination;if(!hasCoordinates(original))return"Oprindelig destination mangler.";return"";}
function chargeStopRangeWarning(point){try{const plan=calculateEvPlanner();const safeRangeMeters=Number(plan?.safeRangeKm)*1000,along=Number(point?.distanceAlongRoute);if(Number.isFinite(safeRangeMeters)&&safeRangeMeters>0&&Number.isFinite(along)&&along>safeRangeMeters)return"Dette ladepunkt ligger længere væk end beregnet rækkevidde.";}catch{}return"";}
function googleMapsChargerUrl(point){const lat=Number(point?.lat),lng=Number(point?.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return"";return`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${lat},${lng}`)}&travelmode=driving`;}
function isMobileBrowser(){return typeof navigator!=="undefined"&&/iphone|ipad|ipod|android|mobile/i.test(navigator.userAgent||"");}
function openGoogleMapsToCharger(point){const url=googleMapsChargerUrl(point);if(!url){setStatus("Ladepunktet mangler koordinater.");return false;}try{if(isMobileBrowser()){window.location.href=url;return true;}const opened=window.open(url,"_blank","noopener");if(!opened)window.location.href=url;return true;}catch(e){console.warn("Could not open Google Maps:",e.message);try{window.location.href=url;return true;}catch{return false;}}}
function applyChargeStopSelection(point){const problem=chargeStopSelectionProblem(point);if(problem){setStatus(problem);return null;}const original=state.originalDestination||state.destination;state.originalDestination={...original};const label=chargePointLabel(point);const warning=chargeStopRangeWarning(point);const dest={lat:Number(point.lat),lng:Number(point.lng),label,displayName:label,name:point.name||label,provider:point.provider||"",rangeWarning:warning};state.temporaryChargeDestination=dest;state.destination=dest;state.selectedAutocomplete=dest;if(els.destinationInput)els.destinationInput.value=label;renderChargeStopBanner();if(warning)setStatus(warning);return dest;}
function openGoogleAndSelectChargeStop(button){const point=chargeStopPointFromButton(button);const dest=applyChargeStopSelection(point);if(!dest)return;const opened=openGoogleMapsToCharger(point);if(opened)void routeToKnownDestination(dest,{save:false});}
async function selectChargeStop(index){return selectChargeStopPoint(state.lastEvPlannerSuggestions?.[Number(index)]);}
async function selectChargeStopPoint(point){const dest=applyChargeStopSelection(point);if(dest)await routeToKnownDestination(dest,{save:false});}
async function continueToOriginalDestination(){const original=state.originalDestination;if(!hasCoordinates(original)){setStatus("Oprindelig destination mangler.");return;}state.temporaryChargeDestination=null;state.originalDestination=null;state.destination=original;state.selectedAutocomplete=original;if(els.destinationInput)els.destinationInput.value=destinationLabel(original);renderChargeStopBanner();await routeToKnownDestination(original,{save:false});}
async function clearChargeStop(){const original=state.originalDestination;state.temporaryChargeDestination=null;state.originalDestination=null;renderChargeStopBanner();if(hasCoordinates(original)){state.destination=original;state.selectedAutocomplete=original;if(els.destinationInput)els.destinationInput.value=destinationLabel(original);await routeToKnownDestination(original,{save:false});return;}setStatus("Ladestop fjernet.");}
async function geocode(q){const r=await fetch(`/api/geocode?q=${encodeURIComponent(q)}&limit=1`,{cache:"no-store"});const d=await r.json();const it=Array.isArray(d)?d[0]:(d.result||d.results?.[0]);if(!r.ok||!it)throw new Error(d.message||d.error||"Adresse ikke fundet");const lat=Number(it.lat),lng=Number(it.lng??it.lon);if(!Number.isFinite(lat)||!Number.isFinite(lng))throw new Error("Adresse uden koordinater");const label=it.displayName||it.label||q;return{lat,lng,label:splitAddress(label).title,displayName:label};}
async function fetchRoute(from,to){const avoid=state.settings.avoidFerries?"&avoid=ferries":"";const r=await fetch(`/api/route?fromLat=${from.lat}&fromLng=${from.lng}&toLat=${to.lat}&toLng=${to.lng}&mode=${encodeURIComponent(state.settings.routeMode)}${avoid}`,{cache:"no-store"});const d=await r.json();if(!r.ok||!d.routes?.length)throw new Error(d.error||"Ingen rute fundet");const route=selectRoute(d.routes);return{geometry:normalizeGeometry(route.geometry?.coordinates||route.geometry),distance:Number(route.distance||0),duration:Number(route.duration||0),roadProfile:buildRouteRoadProfile(route)};}
function selectRoute(routes){if(state.settings.routeMode!=="eco")return routes[0];return[...routes].sort((a,b)=>(a.distance+a.duration*4)-(b.distance+b.duration*4))[0];}
function buildRouteRoadProfile(route){const totalDistance=Number(route?.distance)||0;const buckets={cityKm:0,ruralKm:0,motorwayKm:0,unknownKm:0};let annotatedMeters=0;for(const leg of route?.legs||[]){const annotation=leg?.annotation||{};const distances=annotation.distance||[],durations=annotation.duration||[],speeds=annotation.speed||[];const count=Math.max(distances.length,durations.length,speeds.length);for(let i=0;i<count;i++){const dist=Number(distances[i]);const duration=Number(durations[i]);const speed=Number(speeds[i]);const meters=Number.isFinite(dist)&&dist>0?dist:(Number.isFinite(speed)&&speed>0&&Number.isFinite(duration)&&duration>0?speed*duration:0);if(meters<=0)continue;const speedKmh=Number.isFinite(speed)&&speed>0?speed*3.6:(Number.isFinite(duration)&&duration>0?meters/duration*3.6:null);addRoadProfileMeters(buckets,meters,speedKmh);annotatedMeters+=meters;}}if(annotatedMeters>0){const unknown=Math.max(0,totalDistance-annotatedMeters);buckets.unknownKm+=unknown/1000;return finalizeRoadProfile(buckets,totalDistance/1000,"speed-fallback");}if(totalDistance>0&&Number(route?.duration)>0)return buildAverageSpeedRouteProfile(totalDistance,Number(route.duration),"route-average-fallback");return finalizeRoadProfile({cityKm:0,ruralKm:0,motorwayKm:0,unknownKm:totalDistance/1000},totalDistance/1000,"unavailable");}
function buildAverageSpeedRouteProfile(distanceMeters,durationSeconds,source){const speedKmh=distanceMeters/durationSeconds*3.6;const buckets={cityKm:0,ruralKm:0,motorwayKm:0,unknownKm:0};addRoadProfileMeters(buckets,distanceMeters,speedKmh);return finalizeRoadProfile(buckets,distanceMeters/1000,source);}
function addRoadProfileMeters(buckets,meters,speedKmh){const km=meters/1000;if(!Number.isFinite(speedKmh)||speedKmh<=0)buckets.unknownKm+=km;else if(speedKmh<50)buckets.cityKm+=km;else if(speedKmh<90)buckets.ruralKm+=km;else buckets.motorwayKm+=km;}
function finalizeRoadProfile(buckets,totalKm,source){const total=Math.max(0,Number(totalKm)||0);const city=Number(buckets.cityKm)||0,rural=Number(buckets.ruralKm)||0,motorway=Number(buckets.motorwayKm)||0,unknown=Number(buckets.unknownKm)||0;const denominator=city+rural+motorway+unknown||total;return{available:source!=="unavailable"&&denominator>0,source,cityKm:city,ruralKm:rural,motorwayKm:motorway,unknownKm:unknown,totalKm:denominator,percentages:{city:denominator?city/denominator*100:0,rural:denominator?rural/denominator*100:0,motorway:denominator?motorway/denominator*100:0,unknown:denominator?unknown/denominator*100:0}};}
async function refreshEvWeather(){if(!state.route?.geometry?.length){state.evWeather={ok:false,status:"missing-route",message:"Automatisk vejr afventer rute."};return;}state.evWeather={ok:false,status:"loading",message:"Henter automatisk vejr..."};renderEvPlanner();try{const r=await fetch("/api/weather-route",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({geometry:state.route.geometry})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||`weather-route ${r.status}`);state.evWeather=d;applyAutoWeatherToInputs();}catch(e){console.warn(e);state.evWeather={ok:false,status:"error",message:"Automatisk vejr ikke tilgængeligt.",error:e.message};}}
async function applyRoute(route){state.route=route;state.evDetailsOpen=false;drawRoute(route.geometry);updateTrip(route);syncEvPlannerRouteDistance(true);await refreshEvWeather();renderEvPlanner();}
async function refreshFuel(){if(state.settings.mobilityType==="charging")return refreshCharging();if(!state.route)return;setFuelPanelMode();els.fuelRefreshBtn.disabled=true;els.fuelSummary.textContent="Henter tankstationer og priser...";try{const r=await fetch("/api/fuel-route",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({geometry:state.route.geometry,fuelType:state.settings.fuelType,maxDetourMeters:state.settings.maxFuelDetourMeters,fuelAlongMeters:state.settings.fuelAlongMeters})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`fuel-route ${r.status}`);state.stations=(d.stations||[]).map(s=>({...s,price:isValidFuelPrice(s.price)?Number(s.price):null,matchStatus:s.matchStatus||null,matchReason:s.matchReason||null,sourceStatus:s.sourceStatus||null,dataQuality:s.dataQuality||null})).sort(sortFuelStations);renderFuel(d);drawFuelMarkers();renderEvPlanner();}catch(e){console.error(e);els.fuelSummary.textContent=`Kunne ikke hente tankstationer: ${e.message}`;}finally{els.fuelRefreshBtn.disabled=false;}}
function renderFuel(d){const count=state.stations.length,priced=state.stations.filter(s=>isValidFuelPrice(s.price)).length;if(!count){const raw=fuelDebugValue(d,"rawElements");const norm=fuelDebugValue(d,"normalizedStations");const returned=d?.counts?.returned??d?.stations?.length??0;const api=d?.counts?.apiStations??d?.debug?.priceApi?.apiStations??"?";els.fuelSummary.textContent=`0 stationer. Debug: raw=${raw}, norm=${norm}, returned=${returned}, API=${api}, bbox=${JSON.stringify(d?.input?.routeBbox||d?.debug?.routeBox||d?.debug?.overpass?.bbox||{})}, errors=${(d?.debug?.errors||d?.debug?.overpass?.attempts?.map(a=>a.error||a.statusText||a.status).filter(Boolean)||[]).join(" | ")}`;els.fuelList.innerHTML="";return;}els.fuelSummary.textContent=`${count} stationer inden for ${fmtDist(state.settings.fuelAlongMeters)} langs ruten. ${priced} med kendt pris. Kilder: ${fuelSourceStatusSummary(d)}.`;els.fuelList.innerHTML=state.stations.slice(0,20).map(s=>{const hasPrice=isValidFuelPrice(s.price);const price=hasPrice?formatFuelPrice(s.price):"Pris ikke tilgængelig";const reason=stationPriceReason(s);const sortReason=stationSortReasonLabel(s);const meta=[hasPrice&&sortReason?sortReason:"",`${fmtDist(s.distanceAlongRoute)} langs ruten`,`${fmtDist(s.distanceToRoute)} fra ruten`,hasPrice&&s.priceProduct?s.priceProduct:"",hasPrice&&s.priceSource?`Pris fra ${s.priceSource}`:"",!hasPrice&&reason?reason:""].filter(Boolean).join(" · ");return `<article class="fuel-item"><div class="fuel-title"><span>${esc(s.name||"Tankstation")}</span><span class="fuel-price">${esc(price)}</span></div><div class="fuel-meta">${esc(meta)}</div><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${s.lat},${s.lng}">Åbn i Google Maps</a></article>`;}).join("");}
async function refreshCharging(){if(!state.route)return;setFuelPanelMode();els.fuelRefreshBtn.disabled=true;els.fuelSummary.textContent="Henter ladepunkter langs ruten...";try{const r=await fetch("/api/charging-route",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({geometry:state.route.geometry,maxDetourMeters:state.settings.maxFuelDetourMeters,fuelAlongMeters:state.settings.fuelAlongMeters})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`charging-route ${r.status}`);state.stations=(d.chargingPoints||[]).map(p=>({...p,...normalizeChargePriceFields(p),...normalizeChargeAvailabilityFields(p),provider:p.provider||"Ukendt leverandør",providerKey:p.providerKey||"unknown"})).sort(sortChargingPoints);renderCharging(d);drawFuelMarkers();renderEvPlanner();}catch(e){console.error(e);els.fuelSummary.textContent=`Kunne ikke hente ladepunkter: ${e.message}`;}finally{els.fuelRefreshBtn.disabled=false;}}
function renderCharging(d){setFuelPanelMode();const all=state.stations||[],visible=visibleChargingPoints(),pricingMessage=d?.pricingMessage||"Ladepunkter fundet via OSM. Ingen aktiv priskilde til kr/kWh.",activeSources=chargingSourceStatusSummary(d),explanation="Priser og ledighed vises kun, når der findes en dokumenteret kilde. Ellers kan operatørens app/kort bruges.";const status=chargingDataStatus(all,visible,d);if(!all.length){state.lastChargingList=[];const raw=d?chargingDebugValue(d,"rawElements"):"?";const norm=d?chargingDebugValue(d,"normalizedChargingPoints"):"?";els.fuelSummary.textContent=d?`0 ladepunkter. Debug: raw=${raw}, norm=${norm}, returned=${d?.counts?.returned??0}, priser=${status.withPrice}, ledighed=${status.withAvailability}, kilder=${activeSources}, status=${pricingMessage}, bbox=${JSON.stringify(d?.input?.routeBbox||d?.debug?.overpass?.bbox||{})}`:"Beregn en rute først.";els.fuelList.innerHTML="";return;}const items=[...visible].sort(sortChargingListByRoute);state.lastChargingList=items;const debug=chargingListDebug(all,visible);const filtered=visible.length!==all.length?` ${visible.length} vist efter leverandørfilter.`:"";const maxText=Number.isFinite(debug.maxDistanceAlongRouteKm)?` Længste efter filter: ${debug.maxDistanceAlongRouteKm.toFixed(0).replace(".",",")} km.`:"";els.fuelSummary.textContent=`${all.length} ladepunkter fundet via OSM.${filtered} ${status.withPrice} med prisinfo. ${status.withAvailability} med live-ledighed. ${pricingMessage} Aktive priskilder: ${activeSources}.${maxText} ${explanation}`;console.info("EV charger data status:",status);console.info("EV chargers debug:",debug);els.fuelList.innerHTML=items.map((p,i)=>{const priceInfo=getChargerPriceInfo(p),availabilityInfo=getChargerAvailabilityInfo(p),operatorLink=getOperatorAppLink(p);const meta=[p.provider||"Ukendt leverandør",p.powerKw?`${p.powerKw} kW`:"",p.connectorType||"",`${fmtDist(p.distanceAlongRoute)} langs ruten`,`${fmtDist(p.distanceToRoute)} fra ruten`,priceInfo.sourceText,availabilityInfo.sourceText].filter(Boolean).join(" · ");return `<article class="fuel-item"><div class="fuel-title"><span>${esc(p.name||"Ladepunkt")}</span><span class="fuel-price">${esc(priceInfo.badge)}</span></div><div class="fuel-meta">${esc(meta)}</div>${chargerPriceMarkup(priceInfo)}${chargerAvailabilityMarkup(availabilityInfo)}<div class="charge-stop-actions"><button type="button" class="charge-stop-google-action" data-list="charging" data-index="${i}">Åbn i Google og vælg</button>${operatorLinkMarkup(operatorLink)}</div></article>`;}).join("");}
function normalizeChargePriceFields(point){return{priceKwh:isValidChargePrice(point.priceKwh)?Number(point.priceKwh):null,priceMinKwh:isValidChargePrice(point.priceMinKwh)?Number(point.priceMinKwh):null,priceMaxKwh:isValidChargePrice(point.priceMaxKwh)?Number(point.priceMaxKwh):null,priceCurrency:point.priceCurrency||"DKK",priceLabel:point.priceLabel||"Pris ikke tilgængelig",priceSource:point.priceSource||"none",priceSourceUrl:point.priceSourceUrl||null,priceUpdatedAt:point.priceUpdatedAt||null,priceIsLive:Boolean(point.priceIsLive),priceIsStationSpecific:Boolean(point.priceIsStationSpecific),priceConfidence:point.priceConfidence||"none",priceQuality:point.priceQuality||"unknown"};}
function normalizeChargeAvailabilityFields(point){return{availabilityStatus:point.availabilityStatus||"unknown",availableConnectors:validConnectorCount(point.availableConnectors),occupiedConnectors:validConnectorCount(point.occupiedConnectors),totalConnectors:validConnectorCount(point.totalConnectors),unknownConnectors:validConnectorCount(point.unknownConnectors),availabilityUpdatedAt:point.availabilityUpdatedAt||null,availabilitySource:point.availabilitySource||"OSM",availabilityIsLive:Boolean(point.availabilityIsLive),availabilityLabel:point.availabilityLabel||"Ledighed ikke tilgængelig"};}
function getChargerPriceInfo(charger){const price=isValidChargePrice(charger?.priceKwh)?Number(charger.priceKwh):null,min=isValidChargePrice(charger?.priceMinKwh)?Number(charger.priceMinKwh):null,max=isValidChargePrice(charger?.priceMaxKwh)?Number(charger.priceMaxKwh):null;const stationSpecific=Boolean(charger?.priceIsStationSpecific)||charger?.priceQuality==="station-specific";const operatorGuidance=charger?.priceQuality==="operator-guidance"||(!stationSpecific&&String(charger?.priceLabel||"").toLowerCase().includes("vejledende"));if(stationSpecific&&price!==null)return{hasPriceInfo:true,hasLivePrice:charger.priceIsLive===true,stationSpecific:true,badge:formatChargePrice(price),line:`Pris: ${formatChargePrice(price)}`,note:charger.priceIsLive?"Stationsspecifik live-pris fra dokumenteret kilde.":"Stationsspecifik pris fra dokumenteret kilde.",sourceText:charger.priceSource&&charger.priceSource!=="none"?`Pris fra ${charger.priceSource}`:"",markerLabel:formatChargePriceShort(price)};if(operatorGuidance&&(price!==null||min!==null||max!==null)){const value=formatChargePriceRange(min,max)||formatChargePrice(price);return{hasPriceInfo:true,hasLivePrice:false,stationSpecific:false,badge:"Vejledende",line:`Pris: Vejledende operatørpris · ${value}`,note:"Ikke stationsspecifik og ikke live-pris.",sourceText:charger.priceSource&&charger.priceSource!=="none"?`Pris fra ${charger.priceSource}`:"Vejledende operatørpris",markerLabel:""};}const link=getOperatorAppLink(charger);const suffix=link.type!=="none"?" · se operatørens app/kort":"";const note=chargerPriceUnavailableNote(charger,link);return{hasPriceInfo:false,hasLivePrice:false,stationSpecific:false,badge:"Ikke tilgængelig",line:`Pris: Ikke tilgængelig${suffix}`,note,sourceText:note,markerLabel:""};}
function chargerPriceMarkup(info){return`<div class="charge-price-line">${esc(info.line)}</div>${info.note?`<div class="fuel-meta">${esc(info.note)}</div>`:""}`;}
function chargerPriceUnavailableNote(charger,link=getOperatorAppLink(charger)){if(link.type!=="none")return"Aktuel pris skal ses i operatørens app/kort.";return charger?.matchReason||"Ingen dokumenteret priskilde for dette ladepunkt.";}
function getChargerAvailabilityInfo(charger){const available=validConnectorCount(charger?.availableConnectors),occupied=validConnectorCount(charger?.occupiedConnectors),total=validConnectorCount(charger?.totalConnectors),live=charger?.availabilityIsLive===true;if(live){const totalText=total!==null?` / ${total} totalt`:"";const updated=charger?.availabilityUpdatedAt?` · opdateret ${formatTimeOnly(charger.availabilityUpdatedAt)}`:"";if(available!==null)return{hasAvailability:true,hasLiveAvailability:true,line:`Ledighed: ${available} ledige${totalText}${updated}`,note:charger.availabilitySource&&charger.availabilitySource!=="OSM"?`Live-status fra ${charger.availabilitySource}.`:"Live-status fra dokumenteret kilde.",sourceText:charger.availabilitySource&&charger.availabilitySource!=="OSM"?`Ledighed fra ${charger.availabilitySource}`:""};const status=String(charger?.availabilityStatus||"").trim();return{hasAvailability:status&&status!=="unknown",hasLiveAvailability:true,line:`Ledighed: ${status||"Live-status"}${updated}`,note:"Live-status fra dokumenteret kilde.",sourceText:charger.availabilitySource&&charger.availabilitySource!=="OSM"?`Ledighed fra ${charger.availabilitySource}`:""};}const link=getOperatorAppLink(charger);const line=link.type!=="none"?"Ledighed: Ikke tilgængelig · se operatørens app/kort":"Ledighed: Ikke tilgængelig · OSM har ikke live-status";return{hasAvailability:false,hasLiveAvailability:false,line,note:"Der gættes ikke på ledige ladestandere uden live-kilde.",sourceText:""};}
function chargerAvailabilityMarkup(info){return`<div class="charge-availability-line">${esc(info.line)}</div>${info.note?`<div class="fuel-meta">${esc(info.note)}</div>`:""}`;}
function getOperatorAppLink(charger){const key=String(charger?.providerKey||"").toLowerCase();const map={clever:{url:"https://clever.dk/ladekort",note:"Åbner Clevers ladekort"},ionity:{url:"https://ionity.eu/en/network/network-status",note:"Åbner IONITY-kort"},circlek:{url:"https://www.circlek.dk/elbil/ladestationer",note:"Åbner Circle K ladekort"},ok:{url:"https://www.ok.dk/privat/produkter/elbil/ok-ladestandere",note:"Åbner OK ladeoversigt"},norlys:{url:"https://norlys.dk/elbil/ladekort/",note:"Åbner Norlys ladekort"},spirii:{url:"https://spirii.com/da/charging-map/",note:"Åbner Spirii ladekort"},eon:{url:"https://www.eon.dk/privat/produkter/elbil/ladekort.html",note:"Åbner E.ON ladekort"},tesla:{url:"https://www.tesla.com/da_dk/findus",note:"Åbner Tesla Find Us"},unox:{url:"https://www.unoxmobility.dk/lynladning",note:"Åbner Uno-X ladeinfo"},q8f24:{url:"https://www.q8.dk/privat/elbil/ladestationer",note:"Åbner Q8 ladeoversigt"}};const entry=map[key];if(entry&&isSafeHttpUrl(entry.url))return{label:"Se pris og ledighed",url:entry.url,type:"web",note:entry.note};return{label:"",url:"",type:"none",note:""};}
function operatorLinkMarkup(link){return link?.type&&link.type!=="none"&&isSafeHttpUrl(link.url)?`<a class="charge-operator-link" target="_blank" rel="noopener" href="${esc(link.url)}" title="${esc(link.note||"Åbner operatørens app/kort")}">${esc(link.label||"Se pris og ledighed")}</a>`:"";}
function isSafeHttpUrl(url){try{const parsed=new URL(String(url||""));return parsed.protocol==="https:"||parsed.protocol==="http:";}catch{return false;}}
function sortChargingListByRoute(a,b){return numberOrInfinity(a.distanceAlongRoute)-numberOrInfinity(b.distanceAlongRoute)||numberOrInfinity(a.distanceToRoute)-numberOrInfinity(b.distanceToRoute)||String(a.name||"").localeCompare(String(b.name||""));}
function numberOrInfinity(value){const n=Number(value);return Number.isFinite(n)?n:Infinity;}
function chargingListDebug(all,visible){let safeRangeKm=null;try{const plan=calculateEvPlanner();safeRangeKm=Number.isFinite(Number(plan.safeRangeKm))?Math.round(Number(plan.safeRangeKm)*10)/10:null;}catch{}const distances=visible.map(p=>Number(p.distanceAlongRoute)).filter(Number.isFinite);return{received:all.length,afterProviderFilter:visible.length,maxDistanceAlongRouteKm:distances.length?Math.round(Math.max(...distances)/100)/10:null,selectedDistanceLimitKm:Math.round(Number(state.settings.fuelAlongMeters||0)/1000),safeRangeKm};}
function chargingDataStatus(all,visible,d){const byProvider={};for(const point of visible||[]){const key=point.providerKey||"unknown";byProvider[key]=(byProvider[key]||0)+1;}const priceInfos=(visible||[]).map(getChargerPriceInfo),availabilityInfos=(visible||[]).map(getChargerAvailabilityInfo);return{total:(all||[]).length,visible:(visible||[]).length,withPrice:priceInfos.filter(info=>info.hasPriceInfo).length,withLivePrice:priceInfos.filter(info=>info.hasLivePrice).length,withAvailability:availabilityInfos.filter(info=>info.hasAvailability).length,withLiveAvailability:availabilityInfos.filter(info=>info.hasLiveAvailability).length,withOperatorLink:(visible||[]).filter(point=>getOperatorAppLink(point).type!=="none").length,byProvider,sourceTypes:{sources:(d?.sources||[]).map(s=>s.id||s.name).filter(Boolean),pricingSources:(d?.pricingSources||[]).map(s=>s.id||s.name).filter(Boolean),pricingStatus:d?.pricingStatus||"unknown"}};}
function visibleChargingPoints(){const selected=state.settings.chargeProvider||"all";const points=state.settings.mobilityType==="charging"?dedupeChargingPoints(state.stations||[]):[];return selected==="all"?points:points.filter(p=>p.providerKey===selected);}
function setFuelPanelMode(){const charging=state.settings.mobilityType==="charging";const title=document.querySelector("section.fuel:not(.ev-planner) h2");if(title)title.textContent=charging?"Ladepunkter langs ruten":"Tankstationer langs ruten";if(els.fuelTypeSelect)els.fuelTypeSelect.closest("section").style.display=charging?"none":"";if(els.chargeProviderSelect)els.chargeProviderSelect.closest("section").style.display=charging?"":"none";if(els.fuelRefreshBtn)els.fuelRefreshBtn.textContent=charging?"Opdater ladepunkter":"Opdater";updateFuelAlongLabel(charging);if(!state.route&&els.fuelSummary)els.fuelSummary.textContent=charging?"Beregn en rute først for at hente ladepunkter.":"Beregn en rute først.";}
function renderGreenWaveVersionBadge(){
  let badge=document.getElementById("greenwave-version-badge");
  if(!badge){
    badge=document.createElement("div");
    badge.id="greenwave-version-badge";
    badge.className="greenwave-version-badge";
    document.body.appendChild(badge);
  }
  badge.textContent=`GreenWave ${GREENWAVE_VERSION}`;
}
function ensureGreenWaveVersionStyles(){
  if(document.getElementById("greenwave-version-style"))return;
  const style=document.createElement("style");
  style.id="greenwave-version-style";
  style.textContent=".greenwave-version-badge{position:fixed;right:10px;bottom:10px;z-index:99999;padding:6px 9px;border-radius:999px;background:rgba(8,18,24,.88);border:1px solid rgba(116,255,165,.42);color:#d7ffe3;font:700 11px/1.1 system-ui,-apple-system,Segoe UI,sans-serif;box-shadow:0 8px 22px rgba(0,0,0,.35);pointer-events:none}";
  document.head.appendChild(style);
}
function initGreenWaveVersionBadge(){
  ensureGreenWaveVersionStyles();
  renderGreenWaveVersionBadge();
}
function stationSortReasonLabel(s){
  if(!isValidFuelPrice(s.price))return"";
  const m=Number(s.distanceToRoute||0);
  if(m<=50)return"Næsten på ruten";
  if(m<=250)return"Meget tæt på ruten";
  if(m<=750)return"Acceptabel omvej";
  if(m<=1500)return"Stor omvej";
  return"Lang omvej";
}
function stationPriceReason(s){if(s.matchReason)return s.matchReason;if(s.sourceStatus==="source-error")return"Priskilden fejler lige nu";if(s.matchStatus==="unsupported")return"Kæden er ikke understøttet";if(s.matchStatus==="no-specific-match")return"Stationen kunne ikke matches sikkert";if(s.matchStatus==="product-missing")return"Produktet findes ikke sikkert";return"";}
function fuelSourceStatusSummary(d){const src=d?.sources||[];if(!src.length)return fuelSourceLabel(d);return src.map(s=>`${sourceShortName(s.id)}:${s.ok?"OK":"FEJL"}`).join(" · ");}
function sourceShortName(id){if(id==="circlek-api")return"CircleK/INGO";if(id==="ok-api")return"OK";if(id==="unox-api")return"Uno-X";if(id==="q8-f24-api")return"Q8/F24";if(id==="circlek-list")return"Liste";return id||"kilde";}
function isValidChargePrice(value){const price=Number(value);return Number.isFinite(price)&&price>=0.5&&price<=15;}
function formatChargePrice(value){return isValidChargePrice(value)?`${Number(value).toFixed(2).replace(".",",")} kr./kWh`:"Pris ikke tilgængelig";}
function formatChargePriceRange(min,max){const a=isValidChargePrice(min)?Number(min):null,b=isValidChargePrice(max)?Number(max):null;if(a!==null&&b!==null)return`${a.toFixed(2).replace(".",",")}–${b.toFixed(2).replace(".",",")} kr./kWh`;if(a!==null)return`fra ${a.toFixed(2).replace(".",",")} kr./kWh`;if(b!==null)return`op til ${b.toFixed(2).replace(".",",")} kr./kWh`;return"";}
function formatChargePriceShort(value){return isValidChargePrice(value)?Number(value).toFixed(2).replace(".",","):"";}
function chargingDebugValue(d,key){return d?.debug?.overpass?.[key]??d?.debug?.[key]??d?.counts?.[key]??"?";}
function chargingSourceStatusSummary(d){const src=Array.isArray(d?.pricingSources)?d.pricingSources:[];if(!src.length)return"Ingen aktiv priskilde til kr/kWh";return src.map(s=>s.name||s.id).join(" · ");}
function myRenaultUpdatedLabel(status){const timestamp=status?.timestamp;const date=timestamp?new Date(timestamp):null;if(date&&Number.isFinite(date.getTime())){const time=date.toLocaleTimeString("da-DK",{hour:"2-digit",minute:"2-digit"});const today=new Date();today.setHours(0,0,0,0);const day=new Date(date);day.setHours(0,0,0,0);const diffDays=Math.round((today-day)/86400000);if(diffDays===0)return`i dag ${time}`;if(diffDays===1)return`i går ${time}`;return date.toLocaleString("da-DK",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"});}const age=Number(status?.ageMinutes);return Number.isFinite(age)?`${Math.round(age)} min siden`:"";}
function sortChargingPoints(a,b){const ap=isValidChargePrice(a.priceKwh),bp=isValidChargePrice(b.priceKwh);if(ap&&!bp)return-1;if(!ap&&bp)return 1;if(ap&&bp)return Number(a.priceKwh)-Number(b.priceKwh)||Number(a.distanceToRoute||0)-Number(b.distanceToRoute||0);return Number(a.distanceToRoute||0)-Number(b.distanceToRoute||0)||Number(a.distanceAlongRoute||0)-Number(b.distanceAlongRoute||0);}
function sortFuelStations(a,b){
  const aPriced=isValidFuelPrice(a.price);
  const bPriced=isValidFuelPrice(b.price);
  if(aPriced&&!bPriced)return-1;
  if(!aPriced&&bPriced)return 1;

  if(aPriced&&bPriced){
    const aScore=fuelStopSortScore(a);
    const bScore=fuelStopSortScore(b);
    return aScore-bScore||
      Number(a.distanceToRoute||0)-Number(b.distanceToRoute||0)||
      Number(a.price)-Number(b.price)||
      Number(a.distanceAlongRoute||0)-Number(b.distanceAlongRoute||0);
  }

  return Number(a.distanceToRoute||0)-Number(b.distanceToRoute||0)||
    Number(a.distanceAlongRoute||0)-Number(b.distanceAlongRoute||0);
}
function fuelStopSortScore(s){
  const price=Number(s.price);
  const detourKm=Math.max(0,Number(s.distanceToRoute||0))/1000;
  const alongKm=Math.max(0,Number(s.distanceAlongRoute||0))/1000;
  const qualityPenalty=s.dataQuality==="list-price"?0.08:0;
  // Practical score: price matters, but detour matters a lot.
  // 1 km off route counts roughly as +0.35 kr/l in practical inconvenience.
  return price+(detourKm*0.35)+(alongKm*0.002)+qualityPenalty;
}
function sortStations(a,b){const m=state.settings.fuelSort;if(m==="detour")return a.distanceToRoute-b.distanceToRoute;if(m==="upcoming")return a.distanceAlongRoute-b.distanceAlongRoute;const ap=isValidFuelPrice(a.price),bp=isValidFuelPrice(b.price);if(ap&&bp)return Number(a.price)-Number(b.price);if(ap)return-1;if(bp)return 1;return a.distanceAlongRoute-b.distanceAlongRoute;}
function drawRoute(g){if(!state.map||typeof L==="undefined")return;if(state.routeLine)state.map.removeLayer(state.routeLine);if(state.routeGlow)state.map.removeLayer(state.routeGlow);const ll=g.map(p=>[p[1],p[0]]);state.routeGlow=L.polyline(ll,{color:"#0a58ff",weight:12,opacity:.25}).addTo(state.map);state.routeLine=L.polyline(ll,{color:"#4aa3ff",weight:6,opacity:.95}).addTo(state.map);state.map.fitBounds(state.routeLine.getBounds(),{padding:[40,40]});}
function drawFuelMarkers(){if(!state.map||typeof L==="undefined")return;state.fuelMarkers.forEach(m=>state.map.removeLayer(m));state.fuelMarkers=[];const items=state.settings.mobilityType==="charging"?visibleChargingPoints():state.stations;items.slice(0,20).forEach(s=>{const chargeInfo=state.settings.mobilityType==="charging"?getChargerPriceInfo(s):null;const label=state.settings.mobilityType==="charging"?(chargeInfo?.stationSpecific&&chargeInfo.markerLabel?chargeInfo.markerLabel:(s.provider||s.name||"Ladning").slice(0,8)):(isValidFuelPrice(s.price)?formatFuelPriceShort(s.price):(s.brand||s.name||"Fuel").slice(0,8));state.fuelMarkers.push(L.marker([s.lat,s.lng],{icon:L.divIcon({className:"fuel-marker",html:esc(label)})}).addTo(state.map));});}
function updateCurrentMarker(p,center){if(!state.map||typeof L==="undefined")return;if(!state.userMarker)state.userMarker=L.circleMarker([p.lat,p.lng],{radius:9,color:"#8fb7ff",fillColor:"#2e78ff",fillOpacity:.9}).addTo(state.map);else state.userMarker.setLatLng([p.lat,p.lng]);if(center)state.map.setView([p.lat,p.lng],14);}
function updateDestinationMarker(d){if(!state.map||typeof L==="undefined")return;if(state.destinationMarker)state.map.removeLayer(state.destinationMarker);state.destinationMarker=L.marker([d.lat,d.lng]).addTo(state.map);}
function getCurrentPosition(){return new Promise((res,rej)=>{if(!navigator.geolocation)return rej(new Error("GPS ikke tilgængelig"));navigator.geolocation.getCurrentPosition(p=>{try{const lat=Number(p?.coords?.latitude),lng=Number(p?.coords?.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))throw new Error("GPS mangler koordinater");const point={lat,lng};state.currentPosition=point;updateCurrentMarker(point,true);res(point);}catch(e){rej(e);}},e=>rej(new Error(e.message||"GPS-fejl")),{enableHighAccuracy:true,timeout:12000,maximumAge:3000});});}
function updateTrip(r){if(els.routeDistance)els.routeDistance.textContent=fmtDist(r.distance);if(els.routeDuration)els.routeDuration.textContent=fmtDur(r.duration);if(els.routeEta)els.routeEta.textContent=new Date(Date.now()+r.duration*1000).toLocaleTimeString("da-DK",{hour:"2-digit",minute:"2-digit"});try{renderRouteBatteryBoxes(calculateEvPlanner());}catch{}}
function loadSettings(){try{state.settings={...state.settings,...JSON.parse(localStorage.getItem(SKEY)||"{}")};}catch{}}
function ensureFuelAlongOptions(){if(!els.fuelAlongSelect)return;const values=[25000,50000,100000,200000,300000,400000,500000];const current=Number(state.settings.fuelAlongMeters||els.fuelAlongSelect.value||50000);const selected=values.includes(current)?current:(values.find(value=>value>=current)||500000);els.fuelAlongSelect.innerHTML=values.map(value=>`<option value="${value}">${value/1000} km</option>`).join("");els.fuelAlongSelect.value=String(selected);state.settings.fuelAlongMeters=selected;}
function ensureAvoidFerriesControl(){const routeSection=[...document.querySelectorAll("#settingsModal .settings-body section")].find(section=>/Rute/i.test(section.textContent||""));if(routeSection&&!document.getElementById("avoidFerriesToggle"))routeSection.insertAdjacentHTML("beforeend",'<label><input id="avoidFerriesToggle" type="checkbox"> Undgå færger</label><small id="avoidFerriesNote">Public OSRM understøtter ikke færge-undgåelse; appen viser fejl hvis rutekilden ikke kan honorere valget.</small>');}
function updateFuelAlongLabel(charging){const label=els.fuelAlongSelect?.previousElementSibling;if(label)label.textContent=charging?"Vis ladepunkter inden for de næste":"Vis tankstationer inden for de næste";}
function saveSettings(){if(els.mobilityTypeSelect)state.settings.mobilityType=els.mobilityTypeSelect.value;if(els.chargeProviderSelect)state.settings.chargeProvider=els.chargeProviderSelect.value;if(els.avoidFerriesToggle)state.settings.avoidFerries=Boolean(els.avoidFerriesToggle.checked);state.settings.fuelType=els.fuelTypeSelect.value;state.settings.maxFuelDetourMeters=Number(els.fuelDetourSelect.value);state.settings.fuelAlongMeters=Number(els.fuelAlongSelect.value);state.settings.fuelSort=els.fuelSortSelect.value;state.settings.routeMode=els.routeModeSelect.value;localStorage.setItem(SKEY,JSON.stringify(state.settings));setFuelPanelMode();closeSettings();if(state.route)refreshFuel();}
function syncSettingsUi(){if(els.mobilityTypeSelect)els.mobilityTypeSelect.value=state.settings.mobilityType||"fuel";if(els.chargeProviderSelect)els.chargeProviderSelect.value=state.settings.chargeProvider||"all";if(els.avoidFerriesToggle)els.avoidFerriesToggle.checked=Boolean(state.settings.avoidFerries);els.fuelTypeSelect.value=state.settings.fuelType;els.fuelDetourSelect.value=String(state.settings.maxFuelDetourMeters);els.fuelAlongSelect.value=String(state.settings.fuelAlongMeters);els.fuelSortSelect.value=state.settings.fuelSort;els.routeModeSelect.value=state.settings.routeMode;setFuelPanelMode();}
function openSettings(){els.settingsBackdrop.classList.remove("hidden");els.settingsModal.classList.remove("hidden");syncSettingsUi();}function closeSettings(){els.settingsBackdrop.classList.add("hidden");els.settingsModal.classList.add("hidden");}
function loadHistory(){try{state.history=JSON.parse(localStorage.getItem(HKEY)||"[]");}catch{state.history=[];}}function saveHistory(d){state.history=[d,...state.history.filter(x=>x.label!==d.label)].slice(0,5);localStorage.setItem(HKEY,JSON.stringify(state.history));}function renderHistory(){if(!state.history.length){els.historySection.classList.add("hidden");return;}els.historySection.classList.remove("hidden");els.historyList.innerHTML=state.history.map((h,i)=>`<button type="button" data-index="${i}"><strong>${esc(h.label)}</strong><small>${esc(h.displayName||"")}</small></button>`).join("");[...els.historyList.querySelectorAll("button")].forEach(b=>b.addEventListener("click",()=>{const h=state.history[Number(b.dataset.index)];state.selectedAutocomplete=h;els.destinationInput.value=h.label;}));}
function setStatus(t){if(els.statusText)els.statusText.textContent=t;}function splitAddress(t){const p=String(t||"").split(",").map(x=>x.trim()).filter(Boolean);return{title:p[0]||t,subtitle:p.slice(1).join(", ")}}function normalizeGeometry(g){return(g||[]).map(p=>Array.isArray(p)?[Number(p[0]),Number(p[1])]:[Number(p.lng??p.lon),Number(p.lat)]).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1]));}function isValidFuelPrice(value){const price=Number(value);return Number.isFinite(price)&&price>=5&&price<=30;}function formatFuelPrice(value){return isValidFuelPrice(value)?`${Number(value).toFixed(2).replace(".",",")} kr/l`:"Pris ikke tilgængelig";}function formatFuelPriceShort(value){return isValidFuelPrice(value)?Number(value).toFixed(2).replace(".",","):"";}function fuelSourceLabel(d){const sources=Array.isArray(d?.sources)?d.sources:[],names=[];const has=id=>sources.some(s=>s?.id===id&&s.ok&&(Number(s.stations)>0||Number(s.products)>0));const add=name=>{if(!names.includes(name))names.push(name);};if(has("circlek-api")||has("circlek-list"))add("Circle K / INGO");if(has("ok-api"))add("OK");if(has("unox-api"))add("Uno-X");if(has("q8-f24-api"))add("Q8 / F24");return names.length?joinDanish(names):"ingen aktive priskilder";}function joinDanish(items){return items.length<=1?items[0]:`${items.slice(0,-1).join(", ")} og ${items[items.length-1]}`;}function fuelDebugValue(d,key){return d?.debug?.overpass?.[key]??d?.debug?.[key]??d?.counts?.[key]??"?";}function fmtDist(m){return m>=1000?`${(m/1000).toFixed(m>=10000?0:1).replace(".",",")} km`:`${Math.round(m)} m`;}function fmtDur(sec){const min=Math.round(sec/60);return min<60?`${min} min`:`${Math.floor(min/60)} t ${min%60} min`;}function validConnectorCount(value){const count=Number(value);return Number.isFinite(count)&&count>=0?Math.round(count):null;}function formatTimeOnly(value){const date=new Date(value);return Number.isFinite(date.getTime())?date.toLocaleTimeString("da-DK",{hour:"2-digit",minute:"2-digit"}):"ukendt tid";}function distanceMeters(lat1,lng1,lat2,lng2){if(![lat1,lng1,lat2,lng2].every(Number.isFinite))return Infinity;const radius=6371000,rad=v=>v*Math.PI/180,dLat=rad(lat2-lat1),dLng=rad(lng2-lng1);const a=Math.sin(dLat/2)**2+Math.cos(rad(lat1))*Math.cos(rad(lat2))*Math.sin(dLng/2)**2;return radius*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}

initGreenWaveVersionBadge();
