const GREENWAVE_VERSION="v1.20-clean-ev-planner-weather-renault";
const SKEY="greenwave_dk_settings_v2",HKEY="greenwave_dk_history_v2",EKEY="greenwave_dk_ev_planner_v1";
const EV_PLANNER_PROFILES={renaultMeganeETech:{id:"renaultMeganeETech",name:"Renault Megane E-Tech EV40",usableBatteryKwh:40,defaultConsumptionKwh100:17,notes:"40 kWh batteri. Forbrug er justerbart."}};
const state={map:null,userMarker:null,destinationMarker:null,routeLine:null,routeGlow:null,fuelMarkers:[],currentPosition:null,destination:null,route:null,selectedAutocomplete:null,autocompleteTimer:null,stations:[],history:[],evWeather:null,myRenault:{ok:false,status:"not-connected",message:"MyRenault ikke tilsluttet. Manuel batteristatus bruges."},settings:{mobilityType:"fuel",chargeProvider:"all",fuelType:"benzin95",maxFuelDetourMeters:2000,fuelAlongMeters:50000,fuelSort:"cheapest",routeMode:"fast"}};
const els={},ids=["map","destinationInput","goBtn","autocompleteResults","historySection","historyList","settingsBtn","settingsBackdrop","settingsModal","closeSettingsBtn","saveSettingsBtn","fuelTypeSelect","fuelDetourSelect","fuelAlongSelect","fuelSortSelect","routeModeSelect","statusText","reasonText","recalcBtn","routeDistance","routeDuration","routeEta","fuelRefreshBtn","fuelSummary","fuelList"];
document.addEventListener("DOMContentLoaded",()=>{ids.forEach(id=>els[id]=document.getElementById(id));removeLegacyDrivingUi();initChargingUi();initEvPlannerUi();bind();loadSettings();loadHistory();initMap();syncSettingsUi();setFuelPanelMode();renderHistory();renderEvPlanner();setStatus("Klar");});
function bind(){on(els.destinationInput,"input",()=>{state.selectedAutocomplete=null;clearTimeout(state.autocompleteTimer);state.autocompleteTimer=setTimeout(searchAutocomplete,250);});on(els.goBtn,"click",calculateRoute);on(els.recalcBtn,"click",calculateRoute);on(els.fuelRefreshBtn,"click",refreshFuel);on(els.settingsBtn,"click",openSettings);on(els.closeSettingsBtn,"click",closeSettings);on(els.settingsBackdrop,"click",closeSettings);on(els.saveSettingsBtn,"click",saveSettings);document.addEventListener("click",e=>{if(!e.target.closest(".search-card")&&!e.target.closest(".autocomplete"))hideAutocomplete();});}
function on(el,ev,fn){if(el)el.addEventListener(ev,fn);}
function removeLegacyDrivingUi(){document.querySelector(".gw")?.remove();document.getElementById("startBtn")?.remove();document.getElementById("stopBtn")?.remove();if(els.reasonText)els.reasonText.textContent="EV Planner bruger rute, batteri og vejr til at beregne ladebehov.";const actions=document.querySelector(".actions");if(actions&&!actions.querySelector("button"))actions.remove();}
function initChargingUi(){const body=document.querySelector("#settingsModal .settings-body");if(body&&!document.getElementById("mobilityTypeSelect")){const type=document.createElement("section");type.innerHTML='<h3>Type</h3><select id="mobilityTypeSelect"><option value="fuel">Brændstof</option><option value="charging">Ladning</option></select>';body.prepend(type);const charge=document.createElement("section");charge.innerHTML='<h3>Ladning</h3><label>Ladeleverandør</label><select id="chargeProviderSelect"><option value="all">Alle</option><option value="clever">Clever</option><option value="eon">E.ON</option><option value="spirii">Spirii</option><option value="norlys">Norlys</option><option value="ok">OK</option><option value="q8f24">Q8/F24</option><option value="circlek">Circle K</option><option value="tesla">Tesla</option><option value="ionity">Ionity</option><option value="unox">Uno-X</option><option value="unknown">Andre/ukendt</option></select>';const routeSection=[...body.querySelectorAll("section")].find(s=>/Rute/i.test(s.textContent||""));body.insertBefore(charge,routeSection||null);}els.mobilityTypeSelect=document.getElementById("mobilityTypeSelect");els.chargeProviderSelect=document.getElementById("chargeProviderSelect");on(els.mobilityTypeSelect,"change",()=>{state.settings.mobilityType=els.mobilityTypeSelect.value;setFuelPanelMode();if(state.route)refreshFuel();});on(els.chargeProviderSelect,"change",()=>{state.settings.chargeProvider=els.chargeProviderSelect.value;setFuelPanelMode();renderCharging();drawFuelMarkers();});}
function initEvPlannerUi(){
  ensureEvPlannerStyles();
  const panel=document.querySelector(".panel");
  if(!panel||document.getElementById("evPlanner"))return;
  const card=document.createElement("section");
  card.id="evPlanner";
  card.className="fuel ev-planner";
  card.innerHTML=`<header><h2>EV Planner v1</h2><button id="evUseRouteBtn" type="button">Brug rute</button></header><div class="ev-profile-note">Bilprofil: Renault Megane E-Tech EV40 · 40 kWh batteri · forbrug kan justeres.</div><div id="myRenaultStatus" class="ev-planner-note">MyRenault ikke tilsluttet · Manuel batteristatus bruges.</div><div id="evWeatherStatus" class="ev-planner-note">Automatisk vejr: afventer rute.</div><div class="ev-planner-grid"><label>Bilprofil<select id="evProfileSelect"><option value="renaultMeganeETech">Renault Megane E-Tech EV40</option></select></label><label>Start-SoC %<input id="evStartSocInput" type="number" min="0" max="100" step="1"></label><label>Minimum-SoC %<input id="evMinSocInput" type="number" min="0" max="50" step="1"></label><label>Rutedistance km<input id="evRouteDistanceInput" type="number" min="0" step="0.1"></label><label>Basisforbrug kWh/100 km<input id="evConsumptionInput" type="number" min="5" max="35" step="0.1"></label><label>Temperatur °C<input id="evTemperatureInput" type="number" min="-30" max="45" step="1"></label><label>Vind km/t<input id="evWindInput" type="number" min="0" max="120" step="1"></label><label>Nedbør<select id="evPrecipitationSelect"><option value="none">Ingen/tørt</option><option value="rain">Regn</option><option value="heavyRain">Kraftig regn</option><option value="snow">Sne/slud</option></select></label><label>Vejtype<select id="evRoadTypeSelect"><option value="mixed">Blandet</option><option value="city">By</option><option value="country">Landevej</option><option value="highway">Motorvej</option></select></label></div><div id="evPlannerSummary" class="ev-planner-summary"></div><div id="evPlannerSuggestions" class="ev-planner-suggestions"></div>`;
  const fuel=document.querySelector(".fuel");
  panel.insertBefore(card,fuel||null);
  els.evProfileSelect=document.getElementById("evProfileSelect");
  els.evStartSocInput=document.getElementById("evStartSocInput");
  els.evMinSocInput=document.getElementById("evMinSocInput");
  els.evRouteDistanceInput=document.getElementById("evRouteDistanceInput");
  els.evConsumptionInput=document.getElementById("evConsumptionInput");
  els.evTemperatureInput=document.getElementById("evTemperatureInput");
  els.evWindInput=document.getElementById("evWindInput");
  els.evPrecipitationSelect=document.getElementById("evPrecipitationSelect");
  els.evRoadTypeSelect=document.getElementById("evRoadTypeSelect");
  els.evUseRouteBtn=document.getElementById("evUseRouteBtn");
  els.evPlannerSummary=document.getElementById("evPlannerSummary");
  els.evPlannerSuggestions=document.getElementById("evPlannerSuggestions");
  els.myRenaultStatus=document.getElementById("myRenaultStatus");
  els.evWeatherStatus=document.getElementById("evWeatherStatus");
  loadEvPlannerSettings();
  syncEvPlannerUi();
  [els.evProfileSelect,els.evStartSocInput,els.evMinSocInput,els.evRouteDistanceInput,els.evConsumptionInput,els.evTemperatureInput,els.evWindInput,els.evPrecipitationSelect,els.evRoadTypeSelect].forEach(el=>on(el,"input",()=>{saveEvPlannerSettings();renderEvPlanner();}));
  [els.evProfileSelect,els.evStartSocInput,els.evMinSocInput,els.evRouteDistanceInput,els.evConsumptionInput,els.evTemperatureInput,els.evWindInput,els.evPrecipitationSelect,els.evRoadTypeSelect].forEach(el=>on(el,"change",()=>{saveEvPlannerSettings();renderEvPlanner();}));
  on(els.evUseRouteBtn,"click",()=>{syncEvPlannerRouteDistance(true);saveEvPlannerSettings();renderEvPlanner();});
}
function defaultEvPlannerSettings(){const profile=EV_PLANNER_PROFILES.renaultMeganeETech;return{profileId:profile.id,startSoc:80,minSoc:15,routeDistanceKm:"",consumptionKwh100:profile.defaultConsumptionKwh100,temperatureC:10,windKmh:10,precipitation:"none",roadType:"mixed"};}
function loadEvPlannerSettings(){try{state.evPlanner={...defaultEvPlannerSettings(),...JSON.parse(localStorage.getItem(EKEY)||"{}")};}catch{state.evPlanner=defaultEvPlannerSettings();}}
function saveEvPlannerSettings(){state.evPlanner={profileId:els.evProfileSelect?.value||"renaultMeganeETech",startSoc:numPlannerInput(els.evStartSocInput,80),minSoc:numPlannerInput(els.evMinSocInput,15),routeDistanceKm:els.evRouteDistanceInput?.value||"",consumptionKwh100:numPlannerInput(els.evConsumptionInput,EV_PLANNER_PROFILES.renaultMeganeETech.defaultConsumptionKwh100),temperatureC:numPlannerInput(els.evTemperatureInput,10),windKmh:numPlannerInput(els.evWindInput,10),precipitation:els.evPrecipitationSelect?.value||"none",roadType:els.evRoadTypeSelect?.value||"mixed"};try{localStorage.setItem(EKEY,JSON.stringify(state.evPlanner));}catch{}}
function syncEvPlannerUi(){const v=state.evPlanner||defaultEvPlannerSettings();if(els.evProfileSelect)els.evProfileSelect.value=v.profileId||"renaultMeganeETech";if(els.evStartSocInput)els.evStartSocInput.value=String(v.startSoc??80);if(els.evMinSocInput)els.evMinSocInput.value=String(v.minSoc??15);if(els.evRouteDistanceInput)els.evRouteDistanceInput.value=v.routeDistanceKm||"";if(els.evConsumptionInput)els.evConsumptionInput.value=String(v.consumptionKwh100??EV_PLANNER_PROFILES.renaultMeganeETech.defaultConsumptionKwh100);if(els.evTemperatureInput)els.evTemperatureInput.value=String(v.temperatureC??10);if(els.evWindInput)els.evWindInput.value=String(v.windKmh??10);if(els.evPrecipitationSelect)els.evPrecipitationSelect.value=v.precipitation||"none";if(els.evRoadTypeSelect)els.evRoadTypeSelect.value=v.roadType||"mixed";}
function syncEvPlannerRouteDistance(force){if(!els.evRouteDistanceInput||!state.route?.distance)return;const current=String(els.evRouteDistanceInput.value||"").trim();if(force||!current){els.evRouteDistanceInput.value=(Number(state.route.distance)/1000).toFixed(1);saveEvPlannerSettings();}}
function evPlannerInputs(){const profile=EV_PLANNER_PROFILES[els.evProfileSelect?.value]||EV_PLANNER_PROFILES.renaultMeganeETech;const routeInput=numPlannerInput(els.evRouteDistanceInput,NaN);const routeDistanceKm=Number.isFinite(routeInput)&&routeInput>0?routeInput:(state.route?.distance?Number(state.route.distance)/1000:0);const myRenault=usableMyRenaultStatus();const autoWeather=usableEvWeather();const manualStartSoc=Math.max(0,Math.min(100,numPlannerInput(els.evStartSocInput,80)));const manualWeather={temperatureC:Math.max(-30,Math.min(45,numPlannerInput(els.evTemperatureInput,10))),windKmh:Math.max(0,Math.min(120,numPlannerInput(els.evWindInput,10))),precipitation:els.evPrecipitationSelect?.value||"none"};const weather=autoWeather||manualWeather;return{profile,startSoc:myRenault?myRenault.soc:manualStartSoc,manualStartSoc,startSocSource:myRenault?"myrenault":"manual",myRenault,routeDistanceKm,consumptionKwh100:Math.max(5,Math.min(35,numPlannerInput(els.evConsumptionInput,profile.defaultConsumptionKwh100))),temperatureC:weather.temperatureC,windKmh:weather.windKmh,precipitation:weather.precipitation,weatherSource:autoWeather?"automatic":"manual",weatherMessage:autoWeather?.message||state.evWeather?.message||"Manuel vejrinput bruges.",roadType:els.evRoadTypeSelect?.value||"mixed"};}
function usableMyRenaultStatus(){const soc=Number(state.myRenault?.soc??state.myRenault?.batterySoc??state.myRenault?.batteryLevel);return state.myRenault?.ok&&Number.isFinite(soc)&&soc>=0&&soc<=100?{soc,status:state.myRenault.status||"connected"}:null;}
function usableEvWeather(){const w=state.evWeather?.weather;if(!state.evWeather?.ok||!w)return null;const temperatureC=Number(w.temperatureC),windKmh=Number(w.windKmh);return{temperatureC:Number.isFinite(temperatureC)?Math.max(-30,Math.min(45,temperatureC)):10,windKmh:Number.isFinite(windKmh)?Math.max(0,Math.min(120,windKmh)):10,precipitation:w.precipitation||precipitationFromWeather(w),message:state.evWeather.message||"Automatisk vejr fra Open-Meteo."};}
function precipitationFromWeather(w){const snow=Number(w.snowfallMm),rain=Number(w.rainMm),precip=Number(w.precipitationMm);if(Number.isFinite(snow)&&snow>0.05)return"snow";const wet=Math.max(Number.isFinite(rain)?rain:0,Number.isFinite(precip)?precip:0);if(wet>=2)return"heavyRain";if(wet>0.05)return"rain";return"none";}
function updateEvExternalStatus(plan){if(els.myRenaultStatus)els.myRenaultStatus.textContent=plan.myRenault?`MyRenault tilsluttet · Start-SoC ${formatSoc(plan.startSoc)}.`:"MyRenault ikke tilsluttet · Manuel batteristatus bruges.";if(els.evWeatherStatus){if(plan.weatherSource==="automatic")els.evWeatherStatus.textContent=`Automatisk vejr aktivt · ${weatherInputLabel(plan)}.`;else els.evWeatherStatus.textContent=state.evWeather?.status==="error"?"Automatisk vejr ikke tilgængeligt · manuel vejrinput bruges.":"Automatisk vejr afventer rute · manuel vejrinput bruges.";}}
function calculateEvPlanner(){const v=evPlannerInputs();const weatherFactor=calculateEvWeatherFactor(v);const adjustedConsumptionKwh100=v.consumptionKwh100*weatherFactor;const energyNeededKwh=v.routeDistanceKm*adjustedConsumptionKwh100/100;const socUsed=v.profile.usableBatteryKwh>0?energyNeededKwh/v.profile.usableBatteryKwh*100:0;const arrivalSoc=v.startSoc-socUsed;const safeEnergyKwh=Math.max(0,(v.startSoc-v.minSoc)/100*v.profile.usableBatteryKwh);const safeRangeKm=adjustedConsumptionKwh100>0?safeEnergyKwh/adjustedConsumptionKwh100*100:0;const missingKwh=Math.max(0,(v.minSoc-arrivalSoc)/100*v.profile.usableBatteryKwh);return{...v,weatherFactor,adjustedConsumptionKwh100,energyNeededKwh,socUsed,arrivalSoc,safeRangeKm,missingKwh,needsCharge:arrivalSoc<v.minSoc};}
function renderEvPlanner(){if(!els.evPlannerSummary||!els.evPlannerSuggestions)return;const plan=calculateEvPlanner();updateEvExternalStatus(plan);if(!plan.routeDistanceKm){els.evPlannerSummary.innerHTML=`<div class="ev-planner-empty">Indtast rutedistance eller beregn en rute for at planlægge batteriet.</div>`;els.evPlannerSuggestions.innerHTML="";return;}const arrival=Math.max(0,Math.min(100,plan.arrivalSoc));const status=plan.needsCharge?"Ladestop anbefales":"Batteriet rækker";const level=plan.needsCharge?"warn":"ok";const weatherPct=(plan.weatherFactor-1)*100;els.evPlannerSummary.innerHTML=`<div class="ev-planner-kpis"><div><span>Forventet ankomst</span><strong>${formatSoc(arrival)}</strong></div><div><span>Start-SoC</span><strong>${formatSoc(plan.startSoc)}</strong></div><div><span>Minimum</span><strong>${formatSoc(plan.minSoc)}</strong></div><div><span>Basisforbrug</span><strong>${formatKwh100(plan.consumptionKwh100)}</strong></div><div><span>Vejrjustering</span><strong>${formatSignedPercent(weatherPct)}</strong></div><div><span>Justeret forbrug</span><strong>${formatKwh100(plan.adjustedConsumptionKwh100)}</strong></div><div><span>Ruteenergi</span><strong>${plan.energyNeededKwh.toFixed(1).replace(".",",")} kWh</strong></div></div><div class="ev-planner-status" data-level="${level}">${status}. ${plan.needsCharge?`Mangler ca. ${plan.missingKwh.toFixed(1).replace(".",",")} kWh for at ankomme med ${formatSoc(plan.minSoc)}.`:`Estimeret reserve ved ankomst er ca. ${(arrival-plan.minSoc).toFixed(0)} procentpoint.`}</div><div class="ev-planner-note">${esc(plan.profile.name)} · ${plan.profile.usableBatteryKwh} kWh batteri · Start-SoC: ${plan.startSocSource==="myrenault"?"MyRenault":"manuel"} · vejr: ${plan.weatherSource==="automatic"?"automatisk Open-Meteo":"manuel fallback"} · weatherFactor ${plan.weatherFactor.toFixed(2).replace(".",",")} · ${weatherInputLabel(plan)}.</div>`;renderEvPlannerSuggestions(plan);}
function renderEvPlannerSuggestions(plan){if(!els.evPlannerSuggestions)return;if(!plan.needsCharge){els.evPlannerSuggestions.innerHTML="";return;}const result=evPlannerChargingSuggestions(plan);if(!result.items.length){els.evPlannerSuggestions.innerHTML=`<div class="ev-planner-status" data-level="warn">${esc(result.message)}</div>`;return;}els.evPlannerSuggestions.innerHTML=`<h3>Foreslåede ladepunkter inden ca. ${fmtDist(plan.safeRangeKm*1000)}</h3>${result.items.map(p=>{const hasPrice=isValidChargePrice(p.priceKwh);const price=hasPrice?formatChargePrice(p.priceKwh):"Pris ikke tilgængelig";const meta=[p.provider||"Ukendt leverandør",p.powerKw?`${p.powerKw} kW`:"",`${fmtDist(p.distanceAlongRoute)} langs ruten`,`${fmtDist(p.distanceToRoute)} fra ruten`,price].filter(Boolean).join(" · ");return `<article class="fuel-item"><div class="fuel-title"><span>${esc(p.name||"Ladepunkt")}</span><span class="fuel-price">${esc(price)}</span></div><div class="fuel-meta">${esc(meta)}</div><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${p.lat},${p.lng}">?bn i Google Maps</a></article>`;}).join("")}`;
}
function evPlannerChargingSuggestions(plan){if(state.settings.mobilityType!=="charging")return{items:[],message:"Skift Type til Ladning og hent ladepunkter langs ruten for konkrete ladestop."};const points=(state.stations||[]).filter(p=>Number.isFinite(Number(p.distanceAlongRoute))&&Number.isFinite(Number(p.distanceToRoute))&&Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng))&&(p.providerKey||p.connectorType||p.powerKw||"priceKwh"in p));if(!points.length)return{items:[],message:"Ingen ladepunkter er hentet endnu. Tryk Opdater ladepunkter."};const maxAlong=Math.max(0,plan.safeRangeKm*1000);const target=Math.max(0,maxAlong*0.75);const reachable=points.filter(p=>Number(p.distanceAlongRoute)<=maxAlong);const pool=reachable.length?reachable:points;const items=[...pool].sort((a,b)=>Math.abs(Number(a.distanceAlongRoute)-target)-Math.abs(Number(b.distanceAlongRoute)-target)||Number(b.powerKw||0)-Number(a.powerKw||0)||Number(a.distanceToRoute||0)-Number(b.distanceToRoute||0)).slice(0,5);return{items,message:reachable.length?"":"Ingen hentede ladepunkter ligger før minimum-SoC-grænsen; viser nærmeste kendte ladepunkter langs ruten."};}
function calculateEvWeatherFactor(plan){let factor=1;const temp=Number(plan.temperatureC),wind=Number(plan.windKmh);if(temp<0)factor+=0.20+Math.min(0.10,Math.abs(temp)*0.006);else if(temp<5)factor+=0.12;else if(temp<10)factor+=0.06;else if(temp>30)factor+=0.08;else if(temp>25)factor+=0.04;if(wind>10)factor+=Math.min(0.15,(wind-10)*0.003);factor+=({none:0,rain:0.07,heavyRain:0.12,snow:0.20}[plan.precipitation]??0);factor+=({city:-0.05,mixed:0,country:0.03,highway:0.12}[plan.roadType]??0);return Math.max(0.85,Math.min(1.55,factor));}
function weatherInputLabel(plan){return `${Math.round(plan.temperatureC)}°C, ${Math.round(plan.windKmh)} km/t vind, ${precipitationLabel(plan.precipitation)}, ${roadTypeLabel(plan.roadType)}`;}
function precipitationLabel(value){return{none:"tørt",rain:"regn",heavyRain:"kraftig regn",snow:"sne/slud"}[value]||"tørt";}
function roadTypeLabel(value){return{city:"by",mixed:"blandet vej",country:"landevej",highway:"motorvej"}[value]||"blandet vej";}
function ensureEvPlannerStyles(){if(document.getElementById("ev-planner-style"))return;const style=document.createElement("style");style.id="ev-planner-style";style.textContent=".ev-planner{margin-top:12px}.ev-profile-note,.ev-planner-note,.ev-planner-empty{color:var(--muted);font-size:13px}.ev-planner-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin-top:12px}.ev-planner-grid label{display:block;color:var(--muted);font-size:12px;text-transform:uppercase}.ev-planner-grid input,.ev-planner-grid select{width:100%;margin-top:6px;background:#111f33;border:1px solid #31425d;border-radius:14px;padding:11px}.ev-planner-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px;margin-top:12px}.ev-planner-kpis div,.ev-planner-status{background:#101d2f;border:1px solid var(--line);border-radius:16px;padding:12px}.ev-planner-kpis span{display:block;color:var(--muted);font-size:11px;text-transform:uppercase}.ev-planner-kpis strong{display:block;margin-top:3px;font-size:20px;color:#fff}.ev-planner-status{margin-top:10px;color:#dce8f8}.ev-planner-status[data-level=ok]{border-color:rgba(57,228,123,.55)}.ev-planner-status[data-level=warn]{border-color:rgba(255,194,102,.65);color:#ffe3ad}.ev-planner-suggestions h3{margin:14px 0 4px;color:var(--muted);font-size:13px;text-transform:uppercase}@media(max-width:720px){.ev-planner-grid{grid-template-columns:1fr 1fr}.ev-planner-grid label:first-child{grid-column:1/-1}}";document.head.appendChild(style);}
function numPlannerInput(el,fallback){const n=Number(String(el?.value??"").replace(",","."));return Number.isFinite(n)?n:fallback;}
function formatSoc(value){return `${Math.round(Math.max(0,Math.min(100,Number(value)||0)))}%`;}
function formatKwh100(value){return `${Number(value).toFixed(1).replace(".",",")} kWh/100 km`;}
function formatSignedPercent(value){const n=Number(value);const sign=n>0?"+":"";return `${sign}${n.toFixed(0).replace(".",",")}%`;}
function initMap(){if(typeof L==="undefined"){setStatus("Kort kunne ikke indlæses.");return;}state.map=L.map("map",{zoomControl:false,attributionControl:false,preferCanvas:true});L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{subdomains:"abcd",maxZoom:20}).addTo(state.map);state.map.setView([55.6761,12.5683],10);}
async function searchAutocomplete(){const q=els.destinationInput.value.trim();if(q.length<2){hideAutocomplete();return;}try{const r=await fetch(`/api/geocode?q=${encodeURIComponent(q)}&limit=6&mode=suggest`,{cache:"no-store"});const d=await r.json();const items=Array.isArray(d)?d:(d.results||[]);if(!items.length){hideAutocomplete();return;}els.autocompleteResults.innerHTML=items.map((it,i)=>{const label=it.displayName||it.label||"Ukendt adresse",p=splitAddress(label);return `<button type="button" data-index="${i}"><strong>${esc(p.title)}</strong><small>${esc(p.subtitle)}</small></button>`;}).join("");els.autocompleteResults.classList.remove("hidden");[...els.autocompleteResults.querySelectorAll("button")].forEach(b=>b.addEventListener("click",()=>{const it=items[Number(b.dataset.index)],label=it.displayName||it.label||"Destination",p=splitAddress(label);state.selectedAutocomplete={lat:Number(it.lat),lng:Number(it.lng??it.lon),label:p.title,displayName:label};els.destinationInput.value=p.title;hideAutocomplete();}));}catch(e){console.warn(e);hideAutocomplete();}}
function hideAutocomplete(){els.autocompleteResults?.classList.add("hidden");}
async function calculateRoute(){const q=els.destinationInput.value.trim();if(!q){alert("Indtast en destination.");return;}try{setStatus("Finder position og beregner rute...");els.goBtn.disabled=true;els.recalcBtn.disabled=true;els.fuelRefreshBtn.disabled=true;const pos=await getCurrentPosition();state.currentPosition=pos;updateCurrentMarker(pos,true);const dest=state.selectedAutocomplete||await geocode(q);state.destination=dest;updateDestinationMarker(dest);saveHistory(dest);renderHistory();const route=await fetchRoute(pos,dest);await applyRoute(route);els.recalcBtn.disabled=false;els.fuelRefreshBtn.disabled=false;setStatus(state.settings.mobilityType==="charging"?"Rute klar. Henter ladepunkter...":"Rute klar. Henter tankstationer...");await refreshFuel();}catch(e){console.error(e);setStatus(`Fejl: ${e.message}`);}finally{els.goBtn.disabled=false;}}
async function geocode(q){const r=await fetch(`/api/geocode?q=${encodeURIComponent(q)}&limit=1`,{cache:"no-store"});const d=await r.json();const it=Array.isArray(d)?d[0]:(d.result||d.results?.[0]);if(!r.ok||!it)throw new Error(d.message||d.error||"Adresse ikke fundet");const lat=Number(it.lat),lng=Number(it.lng??it.lon);if(!Number.isFinite(lat)||!Number.isFinite(lng))throw new Error("Adresse uden koordinater");const label=it.displayName||it.label||q;return{lat,lng,label:splitAddress(label).title,displayName:label};}
async function fetchRoute(from,to){const r=await fetch(`/api/route?fromLat=${from.lat}&fromLng=${from.lng}&toLat=${to.lat}&toLng=${to.lng}&mode=${encodeURIComponent(state.settings.routeMode)}`,{cache:"no-store"});const d=await r.json();if(!r.ok||!d.routes?.length)throw new Error(d.error||"Ingen rute fundet");const route=selectRoute(d.routes);return{geometry:normalizeGeometry(route.geometry?.coordinates||route.geometry),distance:Number(route.distance||0),duration:Number(route.duration||0)};}
function selectRoute(routes){if(state.settings.routeMode!=="eco")return routes[0];return[...routes].sort((a,b)=>(a.distance+a.duration*4)-(b.distance+b.duration*4))[0];}
async function refreshEvWeather(){if(!state.route?.geometry?.length){state.evWeather={ok:false,status:"missing-route",message:"Automatisk vejr afventer rute."};return;}state.evWeather={ok:false,status:"loading",message:"Henter automatisk vejr..."};renderEvPlanner();try{const r=await fetch("/api/weather-route",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({geometry:state.route.geometry})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||`weather-route ${r.status}`);state.evWeather=d;}catch(e){console.warn(e);state.evWeather={ok:false,status:"error",message:"Automatisk vejr ikke tilgængeligt.",error:e.message};}}
async function applyRoute(route){state.route=route;drawRoute(route.geometry);updateTrip(route);syncEvPlannerRouteDistance(true);await refreshEvWeather();renderEvPlanner();}
async function refreshFuel(){if(state.settings.mobilityType==="charging")return refreshCharging();if(!state.route)return;setFuelPanelMode();els.fuelRefreshBtn.disabled=true;els.fuelSummary.textContent="Henter tankstationer og priser...";try{const r=await fetch("/api/fuel-route",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({geometry:state.route.geometry,fuelType:state.settings.fuelType,maxDetourMeters:state.settings.maxFuelDetourMeters,fuelAlongMeters:state.settings.fuelAlongMeters})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`fuel-route ${r.status}`);state.stations=(d.stations||[]).map(s=>({...s,price:isValidFuelPrice(s.price)?Number(s.price):null,matchStatus:s.matchStatus||null,matchReason:s.matchReason||null,sourceStatus:s.sourceStatus||null,dataQuality:s.dataQuality||null})).sort(sortFuelStations);renderFuel(d);drawFuelMarkers();renderEvPlanner();}catch(e){console.error(e);els.fuelSummary.textContent=`Kunne ikke hente tankstationer: ${e.message}`;}finally{els.fuelRefreshBtn.disabled=false;}}
function renderFuel(d){const count=state.stations.length,priced=state.stations.filter(s=>isValidFuelPrice(s.price)).length;if(!count){const raw=fuelDebugValue(d,"rawElements");const norm=fuelDebugValue(d,"normalizedStations");const returned=d?.counts?.returned??d?.stations?.length??0;const api=d?.counts?.apiStations??d?.debug?.priceApi?.apiStations??"?";els.fuelSummary.textContent=`0 stationer. Debug: raw=${raw}, norm=${norm}, returned=${returned}, API=${api}, bbox=${JSON.stringify(d?.input?.routeBbox||d?.debug?.routeBox||d?.debug?.overpass?.bbox||{})}, errors=${(d?.debug?.errors||d?.debug?.overpass?.attempts?.map(a=>a.error||a.statusText||a.status).filter(Boolean)||[]).join(" | ")}`;els.fuelList.innerHTML="";return;}els.fuelSummary.textContent=`${count} stationer inden for ${fmtDist(state.settings.fuelAlongMeters)} langs ruten. ${priced} med kendt pris. Kilder: ${fuelSourceStatusSummary(d)}.`;els.fuelList.innerHTML=state.stations.slice(0,20).map(s=>{const hasPrice=isValidFuelPrice(s.price);const price=hasPrice?formatFuelPrice(s.price):"Pris ikke tilgængelig";const reason=stationPriceReason(s);const sortReason=stationSortReasonLabel(s);const meta=[hasPrice&&sortReason?sortReason:"",`${fmtDist(s.distanceAlongRoute)} langs ruten`,`${fmtDist(s.distanceToRoute)} fra ruten`,hasPrice&&s.priceProduct?s.priceProduct:"",hasPrice&&s.priceSource?`Pris fra ${s.priceSource}`:"",!hasPrice&&reason?reason:""].filter(Boolean).join(" · ");return `<article class="fuel-item"><div class="fuel-title"><span>${esc(s.name||"Tankstation")}</span><span class="fuel-price">${esc(price)}</span></div><div class="fuel-meta">${esc(meta)}</div><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${s.lat},${s.lng}">?bn i Google Maps</a></article>`;}).join("");}
async function refreshCharging(){if(!state.route)return;setFuelPanelMode();els.fuelRefreshBtn.disabled=true;els.fuelSummary.textContent="Henter ladepunkter langs ruten...";try{const r=await fetch("/api/charging-route",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({geometry:state.route.geometry,maxDetourMeters:state.settings.maxFuelDetourMeters,fuelAlongMeters:state.settings.fuelAlongMeters})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`charging-route ${r.status}`);state.stations=(d.chargingPoints||[]).map(p=>({...p,priceKwh:isValidChargePrice(p.priceKwh)?Number(p.priceKwh):null,provider:p.provider||"Ukendt leverandør",providerKey:p.providerKey||"unknown",priceQuality:p.priceQuality||"unknown"})).sort(sortChargingPoints);renderCharging(d);drawFuelMarkers();renderEvPlanner();}catch(e){console.error(e);els.fuelSummary.textContent=`Kunne ikke hente ladepunkter: ${e.message}`;}finally{els.fuelRefreshBtn.disabled=false;}}
function renderCharging(d){setFuelPanelMode();const all=state.stations||[],visible=visibleChargingPoints(),priced=visible.filter(p=>isValidChargePrice(p.priceKwh)).length;const pricingMessage=d?.pricingMessage||"Ladepunkter fundet via OSM. Ingen aktiv priskilde til kr/kWh.";const activeSources=chargingSourceStatusSummary(d);if(!all.length){const raw=d?chargingDebugValue(d,"rawElements"):"?";const norm=d?chargingDebugValue(d,"normalizedChargingPoints"):"?";els.fuelSummary.textContent=d?`0 ladepunkter. Debug: raw=${raw}, norm=${norm}, returned=${d?.counts?.returned??0}, priser=${priced}, kilder=${activeSources}, status=${pricingMessage}, bbox=${JSON.stringify(d?.input?.routeBbox||d?.debug?.overpass?.bbox||{})}`:"Beregn en rute først.";els.fuelList.innerHTML="";return;}const filtered=visible.length!==all.length?` ${visible.length} vist efter filter.`:"";els.fuelSummary.textContent=`${all.length} ladepunkter fundet via OSM.${filtered} ${priced} med kendt ladepris. ${pricingMessage} Aktive priskilder: ${activeSources}.`;els.fuelList.innerHTML=visible.slice(0,20).map(p=>{const hasPrice=isValidChargePrice(p.priceKwh);const price=hasPrice?formatChargePrice(p.priceKwh):"Pris ikke tilgængelig";const quality=p.priceQuality==="operator-guidance"?"Vejledende operatørpris":p.priceQuality==="station-specific"?"Stationsspecifik pris":"";const noPriceReason=!hasPrice?(p.matchReason||pricingMessage):"";const meta=[p.provider||"Ukendt leverandør",p.powerKw?`${p.powerKw} kW`:"",p.connectorType||"",`${fmtDist(p.distanceAlongRoute)} langs ruten`,`${fmtDist(p.distanceToRoute)} fra ruten`,hasPrice&&p.priceSource?`Pris fra ${p.priceSource}`:"",quality,noPriceReason].filter(Boolean).join(" · ");return `<article class="fuel-item"><div class="fuel-title"><span>${esc(p.name||"Ladepunkt")}</span><span class="fuel-price">${esc(price)}</span></div><div class="fuel-meta">${esc(meta)}</div><a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${p.lat},${p.lng}">?bn i Google Maps</a></article>`;}).join("");}
function visibleChargingPoints(){const selected=state.settings.chargeProvider||"all";const points=state.settings.mobilityType==="charging"?(state.stations||[]):[];return selected==="all"?points:points.filter(p=>p.providerKey===selected);}
function setFuelPanelMode(){const charging=state.settings.mobilityType==="charging";const title=document.querySelector(".fuel h2");if(title)title.textContent=charging?"Ladepunkter langs ruten":"Tankstationer langs ruten";if(els.fuelTypeSelect)els.fuelTypeSelect.closest("section").style.display=charging?"none":"";if(els.chargeProviderSelect)els.chargeProviderSelect.closest("section").style.display=charging?"":"none";if(els.fuelRefreshBtn)els.fuelRefreshBtn.textContent=charging?"Opdater ladepunkter":"Opdater";if(!state.route&&els.fuelSummary)els.fuelSummary.textContent=charging?"Beregn en rute først for at hente ladepunkter.":"Beregn en rute først.";}
function renderGreenWaveVersionBadge(){
  let badge=document.getElementById("greenwave-version-badge");
  if(!badge){
    badge=document.createElement("div");
    badge.id="greenwave-version-badge";
    badge.className="greenwave-version-badge";
    document.body.appendChild(badge);
  }
  badge.textContent=`GreenWave ${GREENWAVE_VERSION}`;
}
function ensureGreenWaveVersionStyles(){
  if(document.getElementById("greenwave-version-style"))return;
  const style=document.createElement("style");
  style.id="greenwave-version-style";
  style.textContent=".greenwave-version-badge{position:fixed;right:10px;bottom:10px;z-index:99999;padding:6px 9px;border-radius:999px;background:rgba(8,18,24,.88);border:1px solid rgba(116,255,165,.42);color:#d7ffe3;font:700 11px/1.1 system-ui,-apple-system,Segoe UI,sans-serif;box-shadow:0 8px 22px rgba(0,0,0,.35);pointer-events:none}";
  document.head.appendChild(style);
}
function initGreenWaveVersionBadge(){
  ensureGreenWaveVersionStyles();
  renderGreenWaveVersionBadge();
}
function stationSortReasonLabel(s){
  if(!isValidFuelPrice(s.price))return"";
  const m=Number(s.distanceToRoute||0);
  if(m<=50)return"Næsten på ruten";
  if(m<=250)return"Meget tæt på ruten";
  if(m<=750)return"Acceptabel omvej";
  if(m<=1500)return"Stor omvej";
  return"Lang omvej";
}
function stationPriceReason(s){if(s.matchReason)return s.matchReason;if(s.sourceStatus==="source-error")return"Priskilden fejler lige nu";if(s.matchStatus==="unsupported")return"Kæden er ikke understøttet";if(s.matchStatus==="no-specific-match")return"Stationen kunne ikke matches sikkert";if(s.matchStatus==="product-missing")return"Produktet findes ikke sikkert";return"";}
function fuelSourceStatusSummary(d){const src=d?.sources||[];if(!src.length)return fuelSourceLabel(d);return src.map(s=>`${sourceShortName(s.id)}:${s.ok?"OK":"FEJL"}`).join(" · ");}
function sourceShortName(id){if(id==="circlek-api")return"CircleK/INGO";if(id==="ok-api")return"OK";if(id==="unox-api")return"Uno-X";if(id==="q8-f24-api")return"Q8/F24";if(id==="circlek-list")return"Liste";return id||"kilde";}
function isValidChargePrice(value){const price=Number(value);return Number.isFinite(price)&&price>=0.5&&price<=15;}
function formatChargePrice(value){return isValidChargePrice(value)?`${Number(value).toFixed(2).replace(".",",")} kr/kWh`:"Pris ikke tilgængelig";}
function formatChargePriceShort(value){return isValidChargePrice(value)?Number(value).toFixed(2).replace(".",","):"";}
function chargingDebugValue(d,key){return d?.debug?.overpass?.[key]??d?.debug?.[key]??d?.counts?.[key]??"?";}
function chargingSourceStatusSummary(d){const src=Array.isArray(d?.pricingSources)?d.pricingSources:[];if(!src.length)return"Ingen aktiv priskilde til kr/kWh";return src.map(s=>s.name||s.id).join(" · ");}
function sortChargingPoints(a,b){const ap=isValidChargePrice(a.priceKwh),bp=isValidChargePrice(b.priceKwh);if(ap&&!bp)return-1;if(!ap&&bp)return 1;if(ap&&bp)return Number(a.priceKwh)-Number(b.priceKwh)||Number(a.distanceToRoute||0)-Number(b.distanceToRoute||0);return Number(a.distanceToRoute||0)-Number(b.distanceToRoute||0)||Number(a.distanceAlongRoute||0)-Number(b.distanceAlongRoute||0);}
function sortFuelStations(a,b){
  const aPriced=isValidFuelPrice(a.price);
  const bPriced=isValidFuelPrice(b.price);
  if(aPriced&&!bPriced)return-1;
  if(!aPriced&&bPriced)return 1;

  if(aPriced&&bPriced){
    const aScore=fuelStopSortScore(a);
    const bScore=fuelStopSortScore(b);
    return aScore-bScore||
      Number(a.distanceToRoute||0)-Number(b.distanceToRoute||0)||
      Number(a.price)-Number(b.price)||
      Number(a.distanceAlongRoute||0)-Number(b.distanceAlongRoute||0);
  }

  return Number(a.distanceToRoute||0)-Number(b.distanceToRoute||0)||
    Number(a.distanceAlongRoute||0)-Number(b.distanceAlongRoute||0);
}
function fuelStopSortScore(s){
  const price=Number(s.price);
  const detourKm=Math.max(0,Number(s.distanceToRoute||0))/1000;
  const alongKm=Math.max(0,Number(s.distanceAlongRoute||0))/1000;
  const qualityPenalty=s.dataQuality==="list-price"?0.08:0;
  // Practical score: price matters, but detour matters a lot.
  // 1 km off route counts roughly as +0.35 kr/l in practical inconvenience.
  return price+(detourKm*0.35)+(alongKm*0.002)+qualityPenalty;
}
function sortStations(a,b){const m=state.settings.fuelSort;if(m==="detour")return a.distanceToRoute-b.distanceToRoute;if(m==="upcoming")return a.distanceAlongRoute-b.distanceAlongRoute;const ap=isValidFuelPrice(a.price),bp=isValidFuelPrice(b.price);if(ap&&bp)return Number(a.price)-Number(b.price);if(ap)return-1;if(bp)return 1;return a.distanceAlongRoute-b.distanceAlongRoute;}
function drawRoute(g){if(!state.map||typeof L==="undefined")return;if(state.routeLine)state.map.removeLayer(state.routeLine);if(state.routeGlow)state.map.removeLayer(state.routeGlow);const ll=g.map(p=>[p[1],p[0]]);state.routeGlow=L.polyline(ll,{color:"#0a58ff",weight:12,opacity:.25}).addTo(state.map);state.routeLine=L.polyline(ll,{color:"#4aa3ff",weight:6,opacity:.95}).addTo(state.map);state.map.fitBounds(state.routeLine.getBounds(),{padding:[40,40]});}
function drawFuelMarkers(){if(!state.map||typeof L==="undefined")return;state.fuelMarkers.forEach(m=>state.map.removeLayer(m));state.fuelMarkers=[];const items=state.settings.mobilityType==="charging"?visibleChargingPoints():state.stations;items.slice(0,20).forEach(s=>{const label=state.settings.mobilityType==="charging"?(isValidChargePrice(s.priceKwh)?formatChargePriceShort(s.priceKwh):(s.provider||s.name||"Ladning").slice(0,8)):(isValidFuelPrice(s.price)?formatFuelPriceShort(s.price):(s.brand||s.name||"Fuel").slice(0,8));state.fuelMarkers.push(L.marker([s.lat,s.lng],{icon:L.divIcon({className:"fuel-marker",html:esc(label)})}).addTo(state.map));});}
function updateCurrentMarker(p,center){if(!state.map||typeof L==="undefined")return;if(!state.userMarker)state.userMarker=L.circleMarker([p.lat,p.lng],{radius:9,color:"#8fb7ff",fillColor:"#2e78ff",fillOpacity:.9}).addTo(state.map);else state.userMarker.setLatLng([p.lat,p.lng]);if(center)state.map.setView([p.lat,p.lng],14);}
function updateDestinationMarker(d){if(!state.map||typeof L==="undefined")return;if(state.destinationMarker)state.map.removeLayer(state.destinationMarker);state.destinationMarker=L.marker([d.lat,d.lng]).addTo(state.map);}
function getCurrentPosition(){return new Promise((res,rej)=>{if(!navigator.geolocation)return rej(new Error("GPS ikke tilgængelig"));navigator.geolocation.getCurrentPosition(p=>{try{const lat=Number(p?.coords?.latitude),lng=Number(p?.coords?.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))throw new Error("GPS mangler koordinater");const point={lat,lng};state.currentPosition=point;updateCurrentMarker(point,true);res(point);}catch(e){rej(e);}},e=>rej(new Error(e.message||"GPS-fejl")),{enableHighAccuracy:true,timeout:12000,maximumAge:3000});});}
function updateTrip(r){if(els.routeDistance)els.routeDistance.textContent=fmtDist(r.distance);if(els.routeDuration)els.routeDuration.textContent=fmtDur(r.duration);if(els.routeEta)els.routeEta.textContent=new Date(Date.now()+r.duration*1000).toLocaleTimeString("da-DK",{hour:"2-digit",minute:"2-digit"});}
function loadSettings(){try{state.settings={...state.settings,...JSON.parse(localStorage.getItem(SKEY)||"{}")};}catch{}}
function saveSettings(){if(els.mobilityTypeSelect)state.settings.mobilityType=els.mobilityTypeSelect.value;if(els.chargeProviderSelect)state.settings.chargeProvider=els.chargeProviderSelect.value;state.settings.fuelType=els.fuelTypeSelect.value;state.settings.maxFuelDetourMeters=Number(els.fuelDetourSelect.value);state.settings.fuelAlongMeters=Number(els.fuelAlongSelect.value);state.settings.fuelSort=els.fuelSortSelect.value;state.settings.routeMode=els.routeModeSelect.value;localStorage.setItem(SKEY,JSON.stringify(state.settings));setFuelPanelMode();closeSettings();if(state.route)refreshFuel();}
function syncSettingsUi(){if(els.mobilityTypeSelect)els.mobilityTypeSelect.value=state.settings.mobilityType||"fuel";if(els.chargeProviderSelect)els.chargeProviderSelect.value=state.settings.chargeProvider||"all";els.fuelTypeSelect.value=state.settings.fuelType;els.fuelDetourSelect.value=String(state.settings.maxFuelDetourMeters);els.fuelAlongSelect.value=String(state.settings.fuelAlongMeters);els.fuelSortSelect.value=state.settings.fuelSort;els.routeModeSelect.value=state.settings.routeMode;setFuelPanelMode();}
function openSettings(){els.settingsBackdrop.classList.remove("hidden");els.settingsModal.classList.remove("hidden");syncSettingsUi();}function closeSettings(){els.settingsBackdrop.classList.add("hidden");els.settingsModal.classList.add("hidden");}
function loadHistory(){try{state.history=JSON.parse(localStorage.getItem(HKEY)||"[]");}catch{state.history=[];}}function saveHistory(d){state.history=[d,...state.history.filter(x=>x.label!==d.label)].slice(0,5);localStorage.setItem(HKEY,JSON.stringify(state.history));}function renderHistory(){if(!state.history.length){els.historySection.classList.add("hidden");return;}els.historySection.classList.remove("hidden");els.historyList.innerHTML=state.history.map((h,i)=>`<button type="button" data-index="${i}"><strong>${esc(h.label)}</strong><small>${esc(h.displayName||"")}</small></button>`).join("");[...els.historyList.querySelectorAll("button")].forEach(b=>b.addEventListener("click",()=>{const h=state.history[Number(b.dataset.index)];state.selectedAutocomplete=h;els.destinationInput.value=h.label;}));}
function setStatus(t){if(els.statusText)els.statusText.textContent=t;}function splitAddress(t){const p=String(t||"").split(",").map(x=>x.trim()).filter(Boolean);return{title:p[0]||t,subtitle:p.slice(1).join(", ")}}function normalizeGeometry(g){return(g||[]).map(p=>Array.isArray(p)?[Number(p[0]),Number(p[1])]:[Number(p.lng??p.lon),Number(p.lat)]).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1]));}function isValidFuelPrice(value){const price=Number(value);return Number.isFinite(price)&&price>=5&&price<=30;}function formatFuelPrice(value){return isValidFuelPrice(value)?`${Number(value).toFixed(2).replace(".",",")} kr/l`:"Pris ikke tilgængelig";}function formatFuelPriceShort(value){return isValidFuelPrice(value)?Number(value).toFixed(2).replace(".",","):"";}function fuelSourceLabel(d){const sources=Array.isArray(d?.sources)?d.sources:[],names=[];const has=id=>sources.some(s=>s?.id===id&&s.ok&&(Number(s.stations)>0||Number(s.products)>0));const add=name=>{if(!names.includes(name))names.push(name);};if(has("circlek-api")||has("circlek-list"))add("Circle K / INGO");if(has("ok-api"))add("OK");if(has("unox-api"))add("Uno-X");if(has("q8-f24-api"))add("Q8 / F24");return names.length?joinDanish(names):"ingen aktive priskilder";}function joinDanish(items){return items.length<=1?items[0]:`${items.slice(0,-1).join(", ")} og ${items[items.length-1]}`;}function fuelDebugValue(d,key){return d?.debug?.overpass?.[key]??d?.debug?.[key]??d?.counts?.[key]??"?";}function fmtDist(m){return m>=1000?`${(m/1000).toFixed(m>=10000?0:1).replace(".",",")} km`:`${Math.round(m)} m`;}function fmtDur(sec){const min=Math.round(sec/60);return min<60?`${min} min`:`${Math.floor(min/60)} t ${min%60} min`;}function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}

initGreenWaveVersionBadge();
