
const SETTINGS_KEY="greenwave_companion_dk_settings_v1";
const state={map:null,userMarker:null,destinationMarker:null,routeLine:null,routeGlow:null,fuelMarkers:[],currentPosition:null,smoothedSpeed:null,destination:null,route:null,routeSteps:[],routeMeasurements:null,selectedAutocomplete:null,autocompleteTimer:null,watchId:null,wakeLock:null,offRouteSince:null,lastRerouteAt:0,stations:[],priceData:null,roadContext:{ways:[],signals:[]},maxSpeed:null,settings:{fuelType:"benzin95",maxFuelDetourMeters:5000,routeMode:"fast"}};
const els={};
document.addEventListener("DOMContentLoaded",()=>{cacheDom();loadSettings();initMap();syncSettingsUi();bindEvents();setStatus("Klar");});
function cacheDom(){["map","destinationInput","goBtn","autocompleteResults","settingsBtn","settingsBackdrop","settingsModal","closeSettingsBtn","saveSettingsBtn","fuelTypeSelect","fuelDetourSelect","routeModeSelect","statusText","recommendedSpeed","speedLimit","currentSpeed","reasonText","startBtn","stopBtn","recalcBtn","routeDistance","routeDuration","routeEta","fuelRefreshBtn","fuelSummary","fuelList"].forEach(id=>els[id]=document.getElementById(id));}
function bindEvents(){els.destinationInput.addEventListener("input",()=>{state.selectedAutocomplete=null;clearTimeout(state.autocompleteTimer);state.autocompleteTimer=setTimeout(searchAutocomplete,250)});els.goBtn.addEventListener("click",calculateRoute);els.startBtn.addEventListener("click",startCompanion);els.stopBtn.addEventListener("click",stopCompanion);els.recalcBtn.addEventListener("click",recalculateFromCurrentPosition);els.fuelRefreshBtn.addEventListener("click",refreshFuel);els.settingsBtn.addEventListener("click",openSettings);els.closeSettingsBtn.addEventListener("click",closeSettings);els.settingsBackdrop.addEventListener("click",closeSettings);els.saveSettingsBtn.addEventListener("click",saveSettings);document.addEventListener("click",e=>{if(!e.target.closest(".search-card")&&!e.target.closest(".autocomplete"))hideAutocomplete()});}
function initMap(){state.map=L.map("map",{zoomControl:false,attributionControl:false,preferCanvas:true});L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{subdomains:"abcd",maxZoom:20}).addTo(state.map);state.map.setView([55.6761,12.5683],12);}
async function calculateRoute(){const q=els.destinationInput.value.trim();if(!q){alert("Indtast en destination.");return}try{setStatus("Finder position og beregner rute...");els.goBtn.disabled=true;els.startBtn.disabled=true;els.fuelRefreshBtn.disabled=true;const pos=await getCurrentPosition();updateCurrentPosition(pos,true);const dest=state.selectedAutocomplete||await geocode(q);state.destination=dest;updateDestinationMarker(dest);const route=await fetchRoute(pos,dest);applyRoute(route);els.startBtn.disabled=false;els.recalcBtn.disabled=false;els.fuelRefreshBtn.disabled=false;setStatus("Rute klar. Henter vejdata og tankstationer...");loadRoadContext(route.geometry).then(()=>updateGreenWave()).catch(console.warn);refreshFuel().catch(console.warn);setStatus("Rute klar.")}catch(e){console.error(e);alert(`Kunne ikke beregne rute:\n${e.message||e}`);setStatus("Fejl ved ruteberegning.")}finally{els.goBtn.disabled=false}}
async function recalculateFromCurrentPosition(){if(!state.currentPosition||!state.destination)return;setStatus("Genberegner rute...");const route=await fetchRoute(state.currentPosition,state.destination);applyRoute(route);loadRoadContext(route.geometry).then(()=>updateGreenWave()).catch(console.warn);refreshFuel().catch(console.warn);setStatus("Rute genberegnet.")}
function applyRoute(route){state.route=route;state.routeSteps=prepareSteps(route.steps);state.routeMeasurements=measureRoute(route.geometry);drawRoute(route.geometry);updateTripInfo(route);updateGreenWave();}
async function startCompanion(){if(!state.route){alert("Beregn en rute først.");return}if(!navigator.geolocation){alert("GPS understøttes ikke.");return}await requestWakeLock();state.watchId=navigator.geolocation.watchPosition(p=>{const cur=normalizePosition(p);updateCurrentPosition(cur,false);const progress=getRouteProgress(cur);updateGreenWave(progress);maybeReroute(progress)},e=>{console.warn(e);setStatus(`GPS-fejl: ${e.message}`)},{enableHighAccuracy:true,maximumAge:1000,timeout:10000});els.startBtn.disabled=true;els.stopBtn.disabled=false;setStatus("Companion aktiv.")}
function stopCompanion(){if(state.watchId)navigator.geolocation.clearWatch(state.watchId);state.watchId=null;releaseWakeLock();els.startBtn.disabled=!state.route;els.stopBtn.disabled=true;setStatus("Companion stoppet.")}
function updateCurrentPosition(position,centerMap){const smoothed=smoothSpeed(position);state.currentPosition=smoothed;els.currentSpeed.textContent=Math.round(smoothed.speed||0);const icon=L.divIcon({className:"user-marker-icon",html:'<div class="user-marker-dot"></div>',iconSize:[28,28],iconAnchor:[14,14]});if(!state.userMarker)state.userMarker=L.marker([smoothed.lat,smoothed.lng],{icon,zIndexOffset:5000}).addTo(state.map);else state.userMarker.setLatLng([smoothed.lat,smoothed.lng]);if(centerMap)state.map.flyTo([smoothed.lat,smoothed.lng],14,{duration:.7})}
function smoothSpeed(position){const speed=position.speed||0;if(state.smoothedSpeed===null)state.smoothedSpeed=speed;else{const alpha=speed<10?.18:.28;state.smoothedSpeed=state.smoothedSpeed*(1-alpha)+speed*alpha}return{...position,speed:state.smoothedSpeed}}
function updateDestinationMarker(dest){const icon=L.divIcon({className:"dest-marker-icon",html:'<div class="dest-marker-dot">⌖</div>',iconSize:[40,40],iconAnchor:[20,20]});if(!state.destinationMarker)state.destinationMarker=L.marker([dest.lat,dest.lng],{icon,zIndexOffset:4500}).addTo(state.map);else state.destinationMarker.setLatLng([dest.lat,dest.lng])}
function drawRoute(geometry){if(state.routeGlow)state.map.removeLayer(state.routeGlow);if(state.routeLine)state.map.removeLayer(state.routeLine);const latlngs=geometry.map(p=>[p[1],p[0]]);state.routeGlow=L.polyline(latlngs,{color:"#68c4ff",weight:18,opacity:.22,lineCap:"round",lineJoin:"round"}).addTo(state.map);state.routeLine=L.polyline(latlngs,{color:"#2b91ff",weight:7,opacity:1,lineCap:"round",lineJoin:"round"}).addTo(state.map);state.map.fitBounds(state.routeLine.getBounds(),{padding:[70,70],animate:true})}
function updateTripInfo(route){els.routeDistance.textContent=formatDistance(route.distance);els.routeDuration.textContent=formatDuration(route.duration);els.routeEta.textContent=new Date(Date.now()+route.duration*1000).toLocaleTimeString("da-DK",{hour:"2-digit",minute:"2-digit"})}
function updateGreenWave(progress=null){const cur=state.currentPosition;if(!cur||!state.route){setRecommendation(null,"Beregn en rute for at starte GreenWave.");return}if(!progress)progress=getRouteProgress(cur);const max=findMaxSpeed(cur);state.maxSpeed=max;els.speedLimit.textContent=max||"?";if(!max){setRecommendation(null,"Maxhastighed ukendt på dette vejstykke.");return}const step=findCurrentStep(progress);const signal=findUpcomingSignal(progress);const rec=calculateRecommendedSpeed(max,progress,step,signal);setRecommendation(rec.speed,rec.reason)}
function calculateRecommendedSpeed(max,progress,step,signal){if(step){const d=Math.max(0,step.endDistance-progress.alongMeters);const type=`${step.maneuverType} ${step.maneuverModifier}`.toLowerCase();if(d<500){if(type.includes("roundabout"))return speedPlan(max,d,28,"Rundkørsel forude.");if(type.includes("left")||type.includes("right")||type.includes("turn"))return speedPlan(max,d,25,"Sving forude.");if(type.includes("arrive"))return speedPlan(max,d,15,"Destination tæt på.")}}if(signal&&signal.distanceAhead<850){const speed=signal.distanceAhead<220?Math.round(max*.72/5)*5:Math.round(max*.84/5)*5;return{speed:clamp(speed,25,max),reason:"Signalreguleret kryds forude. Forsigtig GreenWave-estimering."}}return{speed:max,reason:"Ingen konkret grund til at køre under max."}}
function speedPlan(max,d,target,reason){if(d<100)return{speed:Math.min(max,target),reason};if(d<250)return{speed:Math.min(max,Math.max(target+10,Math.round(max*.65/5)*5)),reason};return{speed:Math.min(max,Math.max(target+20,Math.round(max*.8/5)*5)),reason}}
function setRecommendation(speed,reason){els.recommendedSpeed.textContent=speed||"--";els.reasonText.textContent=reason||""}
async function refreshFuel(){if(!state.route)return;els.fuelRefreshBtn.disabled=true;els.fuelSummary.textContent="Henter stationer og priser...";try{const [stations,priceData]=await Promise.all([findFuelStations(state.route.geometry),fetchPriceData()]);state.priceData=priceData;state.stations=attachRouteDistances(stations,state.route.geometry).map(s=>attachPrice(s,priceData,state.settings.fuelType)).filter(s=>s.distanceToRoute<=state.settings.maxFuelDetourMeters).sort((a,b)=>{if(Number.isFinite(a.price)&&Number.isFinite(b.price))return a.price-b.price;if(Number.isFinite(a.price))return-1;if(Number.isFinite(b.price))return 1;return a.distanceAlongRoute-b.distanceAlongRoute});renderFuel();drawFuelMarkers()}catch(e){console.error(e);els.fuelSummary.textContent="Kunne ikke hente tankstationer/priser."}finally{els.fuelRefreshBtn.disabled=false}}
function renderFuel(){const count=state.stations.length;const priced=state.stations.filter(s=>Number.isFinite(s.price)).length;const sources=state.priceData?.sources?.filter(s=>s.ok).map(s=>s.name).join(", ");els.fuelSummary.textContent=count?`${count} stationer fundet. ${priced} med pris. ${sources?"Kilder: "+sources:""}`:"Ingen stationer inden for valgt afstand fra ruten.";els.fuelList.innerHTML=state.stations.slice(0,12).map(s=>{const price=Number.isFinite(s.price)?`${s.price.toFixed(2).replace(".",",")} kr/l`:"Pris ikke tilgængelig";const meta=[`${formatDistance(s.distanceAlongRoute)} langs ruten`,`${formatDistance(s.distanceToRoute)} fra ruten`,s.priceProduct||"",s.priceSource?`Pris fra ${s.priceSource}`:""].filter(Boolean).join(" · ");return `<article class="fuel-item"><div class="fuel-title"><span>${escapeHtml(s.name)}</span><span class="fuel-price">${escapeHtml(price)}</span></div><div class="fuel-meta">${escapeHtml(meta)}</div><a href="https://www.google.com/maps/search/?api=1&query=${s.lat},${s.lng}" target="_blank">Åbn i Google Maps</a></article>`}).join("")}
function drawFuelMarkers(){state.fuelMarkers.forEach(m=>state.map.removeLayer(m));state.fuelMarkers=[];state.stations.slice(0,12).forEach(s=>{const price=Number.isFinite(s.price)?s.price.toFixed(2).replace(".",","):"";const label=price||s.name.slice(0,8);const icon=L.divIcon({className:"fuel-marker",html:`<div class="fuel-pin">⛽ ${escapeHtml(label)}</div>`,iconSize:[100,34],iconAnchor:[50,34]});state.fuelMarkers.push(L.marker([s.lat,s.lng],{icon}).addTo(state.map))})}
async function searchAutocomplete(){const q=els.destinationInput.value.trim();if(q.length<2){hideAutocomplete();return}try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=6&countrycodes=dk&q=${encodeURIComponent(q)}`);const items=await r.json();if(!items.length){hideAutocomplete();return}els.autocompleteResults.innerHTML=items.map((item,i)=>{const f=formatAddress(item);return `<button type="button" data-index="${i}"><strong>${escapeHtml(f.title)}</strong><small>${escapeHtml(f.subtitle)}</small></button>`}).join("");els.autocompleteResults.classList.remove("hidden");[...els.autocompleteResults.querySelectorAll("button")].forEach(btn=>btn.addEventListener("click",()=>{const item=items[Number(btn.dataset.index)];const f=formatAddress(item);state.selectedAutocomplete={lat:Number(item.lat),lng:Number(item.lon),label:f.title,displayName:[f.title,f.subtitle].filter(Boolean).join(", ")};els.destinationInput.value=f.title;hideAutocomplete()}))}catch(e){console.warn(e);hideAutocomplete()}}
function hideAutocomplete(){els.autocompleteResults.classList.add("hidden");els.autocompleteResults.innerHTML=""}
function formatAddress(item){const a=item.address||{};const road=a.road||a.pedestrian||item.name||"";const num=a.house_number||"";const city=a.city||a.town||a.village||a.municipality||"";const postcode=a.postcode||"";return{title:[road,num].filter(Boolean).join(" ")||item.display_name||"Ukendt",subtitle:[postcode,city].filter(Boolean).join(" ")}}
async function geocode(q){const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&addressdetails=1&countrycodes=dk&q=${encodeURIComponent(q)}`);const data=await r.json();if(!data.length)throw new Error("Destination ikke fundet.");const item=data[0];const f=formatAddress(item);return{lat:Number(item.lat),lng:Number(item.lon),label:f.title,displayName:[f.title,f.subtitle].filter(Boolean).join(", ")}}
async function fetchRoute(from,to){const url=`https://router.project-osrm.org/route/v1/driving/${from.lng},${from.lat};${to.lng},${to.lat}?overview=full&geometries=geojson&steps=true&alternatives=true`;const r=await fetch(url);const data=await r.json();if(!data.routes?.length)throw new Error("Ingen rute fundet.");const route=selectRoute(data.routes);return{geometry:route.geometry.coordinates,distance:Number(route.distance||0),duration:Number(route.duration||0),steps:extractSteps(route)}}
function selectRoute(routes){if(state.settings.routeMode==="eco")return[...routes].sort((a,b)=>ecoRouteScore(a)-ecoRouteScore(b))[0];return[...routes].sort((a,b)=>Number(a.duration||Infinity)-Number(b.duration||Infinity))[0]}
function ecoRouteScore(r){return Number(r.distance||0)/1000+Number(r.duration||0)/60*.22}
function extractSteps(route){const out=[];(route.legs||[]).forEach(l=>(l.steps||[]).forEach(s=>{const m=s.maneuver||{};out.push({distance:Number(s.distance||0),duration:Number(s.duration||0),name:s.name||"",maneuverType:m.type||"",maneuverModifier:m.modifier||""})}));return out}
function prepareSteps(steps){let total=0;return steps.map((s,i)=>{const o={...s,index:i,startDistance:total,endDistance:total+s.distance};total+=s.distance;return o})}
function measureRoute(g){const cumulative=[0];let total=0;for(let i=1;i<g.length;i++){const a=g[i-1],b=g[i];total+=haversine(a[1],a[0],b[1],b[0]);cumulative.push(total)}return{cumulative,total}}
function getRouteProgress(pos){const g=state.route.geometry,c=state.routeMeasurements.cumulative;let best={distanceToRoute:Infinity,alongMeters:0,segmentIndex:1};for(let i=1;i<g.length;i++){const a=g[i-1],b=g[i];const p=projectPointToSegment(pos.lat,pos.lng,a[1],a[0],b[1],b[0]);if(p.distanceMeters<best.distanceToRoute){const len=haversine(a[1],a[0],b[1],b[0]);best={distanceToRoute:p.distanceMeters,alongMeters:c[i-1]+len*p.t,segmentIndex:i}}}const ratio=Math.min(1,best.alongMeters/state.route.distance);return{...best,remainingMeters:Math.max(0,state.route.distance-best.alongMeters),remainingSeconds:Math.max(0,state.route.duration*(1-ratio))}}
function maybeReroute(progress){const now=Date.now();if(progress.distanceToRoute<=90){state.offRouteSince=null;return}if(!state.offRouteSince){state.offRouteSince=now;return}if(now-state.offRouteSince<7000||now-state.lastRerouteAt<25000)return;state.lastRerouteAt=now;state.offRouteSince=null;recalculateFromCurrentPosition().catch(console.warn)}
function findCurrentStep(progress){return state.routeSteps.find(s=>progress.alongMeters>=s.startDistance&&progress.alongMeters<=s.endDistance)||state.routeSteps[state.routeSteps.length-1]}
function findUpcomingSignal(progress){return(state.roadContext.signals||[]).map(s=>({...s,distanceAhead:s.alongMeters-progress.alongMeters})).filter(s=>s.distanceAhead>40&&s.distanceAhead<900).sort((a,b)=>a.distanceAhead-b.distanceAhead)[0]||null}
function findMaxSpeed(pos){let best=null;for(const way of state.roadContext.ways||[]){for(let i=1;i<way.geometry.length;i++){const a=way.geometry[i-1],b=way.geometry[i];const p=projectPointToSegment(pos.lat,pos.lng,a[0],a[1],b[0],b[1]);if(!best||p.distanceMeters<best.distance)best={distance:p.distanceMeters,speed:way.maxspeed}}}return best&&best.distance<=60?best.speed:null}
async function loadRoadContext(g){const bbox=routeBbox(g,.035);const b=`${bbox.south},${bbox.west},${bbox.north},${bbox.east}`;const q=`[out:json][timeout:25];(way["highway"]["maxspeed"](${b});node["highway"="traffic_signals"](${b}););out body geom;`;const data=await runOverpass(q,9000);const ways=[],signals=[];for(const el of data.elements||[]){if(el.type==="way"&&el.geometry?.length){const max=parseMaxspeed(el.tags?.maxspeed);if(max)ways.push({id:el.id,maxspeed:max,geometry:el.geometry.map(p=>[p.lat,p.lon])})}if(el.type==="node"&&el.tags?.highway==="traffic_signals")signals.push({id:el.id,lat:el.lat,lng:el.lon})}state.roadContext={ways,signals:attachSignalsToRoute(signals,g)}}
async function findFuelStations(g){const bbox=routeBbox(g,.08);const b=`${bbox.south},${bbox.west},${bbox.north},${bbox.east}`;const q=`[out:json][timeout:35];(node["amenity"="fuel"](${b});way["amenity"="fuel"](${b});relation["amenity"="fuel"](${b}););out center tags;`;const data=await runOverpass(q,10000);return dedupeStations((data.elements||[]).map(normalizeFuelStation).filter(Boolean))}
async function runOverpass(q,timeoutMs){const eps=["https://overpass-api.de/api/interpreter","https://overpass.kumi.systems/api/interpreter","https://overpass.osm.ch/api/interpreter"];for(const ep of eps){try{const r=await fetchWithTimeout(ep,{method:"POST",headers:{"Content-Type":"text/plain;charset=UTF-8"},body:q},timeoutMs);if(r.ok)return await r.json()}catch(e){console.warn("Overpass failed",ep,e)}}throw new Error("Overpass svarer ikke.")}
function normalizeFuelStation(el){const lat=typeof el.lat==="number"?el.lat:el.center?.lat;const lng=typeof el.lon==="number"?el.lon:el.center?.lon;if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;const t=el.tags||{};return{id:`${el.type}-${el.id}`,lat,lng,name:t.name||t.brand||t.operator||"Tankstation",brand:t.brand||t.operator||t.name||"",address:[t["addr:street"],t["addr:housenumber"]].filter(Boolean).join(" "),postalCode:t["addr:postcode"]||"",city:t["addr:city"]||"",distanceToRoute:Infinity,distanceAlongRoute:Infinity}}
function attachRouteDistances(stations,g){const segs=[];let cum=0;for(let i=1;i<g.length;i++){const a=g[i-1],b=g[i];const len=haversine(a[1],a[0],b[1],b[0]);segs.push({start:a,end:b,startMeters:cum,length:len});cum+=len}return stations.map(s=>{let best=Infinity,along=Infinity;for(const seg of segs){const p=projectPointToSegment(s.lat,s.lng,seg.start[1],seg.start[0],seg.end[1],seg.end[0]);if(p.distanceMeters<best){best=p.distanceMeters;along=seg.startMeters+seg.length*p.t}}return{...s,distanceToRoute:best,distanceAlongRoute:along}})}
function attachSignalsToRoute(signals,g){return attachRouteDistances(signals.map(s=>({...s,name:"Traffic signal"})),g).filter(s=>s.distanceToRoute<=45)}
async function fetchPriceData(){const r=await fetch(`/api/fuel-prices?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`/api/fuel-prices ${r.status}`);return await r.json()}
function attachPrice(station,priceData,fuelType){const candidates=Array.isArray(priceData?.stations)?priceData.stations:[];let best=null;for(const c of candidates){const score=scorePriceMatch(station,c);if(!best||score.value>best.score)best={candidate:c,score:score.value,confidence:score.confidence}}if(!best||best.score<50)return{...station,price:null};const product=chooseProduct(best.candidate.prices||[],fuelType);if(!product)return{...station,price:null,priceSource:best.candidate.source};return{...station,price:Number(product.price),priceProduct:product.productName||product.displayName||product.fuelType,priceSource:best.candidate.source,priceConfidence:best.confidence}}
function scorePriceMatch(osm,price){let score=0;const ob=normalizeBrand(osm.brand||osm.name),pb=normalizeBrand(price.brand||price.name);if(ob&&pb&&ob===pb)score+=35;if(sharesToken(osm.name,price.name))score+=20;if(sharesToken(osm.address,price.addressText))score+=25;if(osm.postalCode&&price.postalCode&&String(osm.postalCode)===String(price.postalCode))score+=18;if(Number.isFinite(price.lat)&&Number.isFinite(price.lng)){const m=haversine(osm.lat,osm.lng,price.lat,price.lng);if(m<120)score+=60;else if(m<350)score+=46;else if(m<900)score+=28;else if(m<1800)score+=12}return{value:score,confidence:score>=85?"high":score>=62?"medium":"low"}}
function chooseProduct(prices,fuelType){const c=prices.filter(p=>Number.isFinite(Number(p.price)));const text=p=>normalizeText(`${p.code} ${p.octane} ${p.fuelType} ${p.productName} ${p.displayName}`);if(fuelType==="diesel")return c.find(p=>/diesel/.test(text(p))&&!/premium|plus|extra|deluxe|hvo/.test(text(p)))||c.find(p=>/diesel/.test(text(p)))||null;if(fuelType==="premiumDiesel")return c.find(p=>/diesel/.test(text(p))&&/premium|plus|extra|deluxe/.test(text(p)))||c.find(p=>/diesel/.test(text(p)))||null;if(fuelType==="benzin98")return c.find(p=>/98|100|e5|oktan 98|oktan 100|blyfri 98/.test(text(p))&&!/diesel/.test(text(p)))||null;return c.find(p=>/95|e10|blyfri 95|miles 95|benzin|gasoline|petrol/.test(text(p))&&!/98|100|premium|diesel/.test(text(p)))||c.find(p=>/benzin|gasoline|petrol/.test(text(p))&&!/diesel/.test(text(p)))||null}
function openSettings(){syncSettingsUi();els.settingsModal.classList.remove("hidden");els.settingsBackdrop.classList.remove("hidden")}
function closeSettings(){els.settingsModal.classList.add("hidden");els.settingsBackdrop.classList.add("hidden")}
function saveSettings(){state.settings.fuelType=els.fuelTypeSelect.value;state.settings.maxFuelDetourMeters=Number(els.fuelDetourSelect.value);state.settings.routeMode=els.routeModeSelect.value;localStorage.setItem(SETTINGS_KEY,JSON.stringify(state.settings));closeSettings();if(state.route)refreshFuel().catch(console.warn)}
function loadSettings(){try{state.settings={...state.settings,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}")} }catch{}}
function syncSettingsUi(){els.fuelTypeSelect.value=state.settings.fuelType;els.fuelDetourSelect.value=String(state.settings.maxFuelDetourMeters);els.routeModeSelect.value=state.settings.routeMode}
function setStatus(t){els.statusText.textContent=t}
function routeBbox(g,padding){let south=Infinity,west=Infinity,north=-Infinity,east=-Infinity;for(const p of g){const lng=p[0],lat=p[1];south=Math.min(south,lat);north=Math.max(north,lat);west=Math.min(west,lng);east=Math.max(east,lng)}return{south:south-padding,west:west-padding,north:north+padding,east:east+padding}}
function parseMaxspeed(v){if(!v)return null;const text=String(v).toLowerCase();if(text.includes("none"))return 130;const m=text.match(/\d+/);if(!m)return null;let speed=Number(m[0]);if(text.includes("mph"))speed=Math.round(speed*1.60934);return speed>=5&&speed<=140?speed:null}
function getCurrentPosition(){return new Promise(resolve=>{if(!navigator.geolocation){resolve({lat:55.6761,lng:12.5683,speed:0,heading:0});return}navigator.geolocation.getCurrentPosition(p=>resolve(normalizePosition(p)),()=>resolve({lat:55.6761,lng:12.5683,speed:0,heading:0}),{enableHighAccuracy:true,maximumAge:1000,timeout:9000})})}
function normalizePosition(p){return{lat:p.coords.latitude,lng:p.coords.longitude,speed:typeof p.coords.speed==="number"?Math.max(0,p.coords.speed*3.6):0,heading:typeof p.coords.heading==="number"?p.coords.heading:0,accuracy:typeof p.coords.accuracy==="number"?p.coords.accuracy:null}}
async function requestWakeLock(){try{if("wakeLock"in navigator)state.wakeLock=await navigator.wakeLock.request("screen")}catch{}}
async function releaseWakeLock(){try{if(state.wakeLock)await state.wakeLock.release()}catch{}state.wakeLock=null}
function fetchWithTimeout(url,options,timeoutMs){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeoutMs);return fetch(url,{...options,signal:c.signal}).finally(()=>clearTimeout(t))}
function haversine(lat1,lng1,lat2,lng2){const R=6371000,toRad=v=>v*Math.PI/180,dLat=toRad(lat2-lat1),dLng=toRad(lng2-lng1);const a=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
function projectPointToSegment(lat,lng,lat1,lng1,lat2,lng2){const mLat=111320,mLng=111320*Math.cos(lat*Math.PI/180),px=lng*mLng,py=lat*mLat,ax=lng1*mLng,ay=lat1*mLat,bx=lng2*mLng,by=lat2*mLat,dx=bx-ax,dy=by-ay,len=dx*dx+dy*dy;if(!len)return{t:0,distanceMeters:Math.hypot(px-ax,py-ay)};let t=((px-ax)*dx+(py-ay)*dy)/len;t=clamp(t,0,1);return{t,distanceMeters:Math.hypot(px-(ax+t*dx),py-(ay+t*dy))}}
function formatDistance(m){if(!Number.isFinite(m))return"—";if(m<1000)return`${Math.round(m)} m`;if(m<10000)return`${(m/1000).toFixed(1).replace(".",",")} km`;return`${Math.round(m/1000)} km`}
function formatDuration(s){if(!Number.isFinite(s))return"—";const min=Math.max(1,Math.round(s/60));if(min<60)return`${min} min`;const h=Math.floor(min/60),r=min%60;return r?`${h} t ${r} min`:`${h} t`}
function escapeHtml(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function normalizeBrand(v){const text=normalizeText(v);if(text.includes("circle"))return"circle k";if(text.includes("ingo"))return"ingo";if(text.includes("ok"))return"ok";if(text.includes("uno"))return"uno-x";if(text.includes("q8"))return"q8";if(text.includes("shell"))return"shell";return text}
function normalizeText(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/æ/g,"ae").replace(/ø/g,"oe").replace(/å/g,"aa").replace(/[^a-z0-9]+/g," ").trim()}
function sharesToken(a,b){const ignore=new Set(["vej","gade","alle","tank","station","automat","circle","ingo","uno","ok"]);const at=normalizeText(a).split(" ").filter(t=>t.length>2&&!ignore.has(t));const bt=new Set(normalizeText(b).split(" ").filter(t=>t.length>2&&!ignore.has(t)));return at.some(t=>bt.has(t))}
function dedupeStations(stations){const seen=new Set();return stations.filter(s=>{const key=s.id||`${Math.round(s.lat*10000)}:${Math.round(s.lng*10000)}`;if(seen.has(key))return false;seen.add(key);return true})}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
