import {state} from "./state.js";
export function initMap(){state.map=L.map("map",{zoomControl:false,attributionControl:false,preferCanvas:true});L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{subdomains:"abcd",maxZoom:20}).addTo(state.map);state.map.setView([55.6761,12.5683],12);}
export function drawRoute(geometry){if(!state.map||!Array.isArray(geometry))return;clearRoute();const latlngs=geometry.map(p=>[p[1],p[0]]);state.routeGlow=L.polyline(latlngs,{color:"#68c4ff",weight:22,opacity:.20,lineCap:"round",lineJoin:"round"}).addTo(state.map);state.routeDoneLine=L.polyline([],{color:"#173554",weight:9,opacity:.72,lineCap:"round",lineJoin:"round"}).addTo(state.map);state.routeAheadLine=L.polyline(latlngs,{color:"#2b91ff",weight:10,opacity:1,lineCap:"round",lineJoin:"round"}).addTo(state.map);state.routeLine=state.routeAheadLine;state.map.fitBounds(state.routeAheadLine.getBounds(),{paddingTopLeft:[55,260],paddingBottomRight:[55,260],animate:true});}
export function updateRouteHighlight(progress){if(!state.routeData?.geometry||!state.routeAheadLine||!state.routeDoneLine)return;const g=state.routeData.geometry,index=Math.max(1,Math.min(g.length-1,progress?.segmentIndex||1));state.routeDoneLine.setLatLngs(g.slice(0,index+1).map(p=>[p[1],p[0]]));state.routeAheadLine.setLatLngs(g.slice(index).map(p=>[p[1],p[0]]));}
export function clearRoute(){[state.routeGlow,state.routeDoneLine,state.routeAheadLine].forEach(l=>{if(l)state.map.removeLayer(l)});state.routeGlow=null;state.routeDoneLine=null;state.routeAheadLine=null;state.routeLine=null;}
export function updateUserMarker(lat,lng){const icon=L.divIcon({className:"user-marker-icon",html:'<div class="user-marker-dot"></div>',iconSize:[28,28],iconAnchor:[14,14]});if(!state.userMarker){state.userMarker=L.marker([lat,lng],{icon,zIndexOffset:5000}).addTo(state.map);return}state.userMarker.setLatLng([lat,lng]);}
export function updateDestinationMarker(lat,lng){const icon=L.divIcon({className:"dest-marker-icon",html:'<div class="dest-marker-dot">⌖</div>',iconSize:[40,40],iconAnchor:[20,20]});if(!state.destinationMarker){state.destinationMarker=L.marker([lat,lng],{icon,zIndexOffset:4500}).addTo(state.map);return}state.destinationMarker.setLatLng([lat,lng]);}
export function followNavigationCamera(pos){if(!state.map||!pos)return;const zoom=pos.speed>70?15.6:pos.speed>35?16.4:17.2;state.map.flyTo([pos.lat,pos.lng],zoom,{animate:true,duration:.45});}
export function enterNavigationView(){document.body.classList.add("navigation-active");}
export function exitNavigationView(){document.body.classList.remove("navigation-active");}
export function recenterMap(){if(state.currentPosition)state.map.flyTo([state.currentPosition.lat,state.currentPosition.lng],16,{duration:.8});else state.map.setView([55.6761,12.5683],12);}
