import {state} from "./state.js";import {haversine,projectPointToSegment} from "./utils.js";
const OVERPASS_ENDPOINTS=["https://overpass-api.de/api/interpreter","https://overpass.kumi.systems/api/interpreter","https://overpass.osm.ch/api/interpreter"];
export async function loadRoadContext(geometry){state.roadContext={ways:[],signals:[],loaded:false,error:null};if(!Array.isArray(geometry)||geometry.length<2)return state.roadContext;const bbox=routeBbox(geometry,0.035);const query=buildQuery(bbox);try{const data=await runOverpass(query);const ways=[];const signals=[];for(const element of data.elements||[]){if(element.type==='way'&&element.geometry?.length){const maxspeed=parseMaxspeed(element.tags?.maxspeed);if(maxspeed){ways.push({id:element.id,maxspeed,highway:element.tags?.highway||'',geometry:element.geometry.map(point=>[point.lat,point.lon])});}}if(element.type==='node'&&element.tags?.highway==='traffic_signals'){signals.push({id:element.id,lat:element.lat,lng:element.lon});}}state.roadContext={ways,signals:attachAlongRoute(signals,geometry),loaded:true,error:null};}catch(error){state.roadContext={ways:[],signals:[],loaded:false,error:error.message};}return state.roadContext;}
export function updateSpeedLimitFromPosition(position){const ways=state.roadContext?.ways||[];let best=null;for(const way of ways){for(let i=1;i<way.geometry.length;i++){const a=way.geometry[i-1];const b=way.geometry[i];const projected=projectPointToSegment(position.lat,position.lng,a[0],a[1],b[0],b[1]);if(!best||projected.distanceMeters<best.distance){best={distance:projected.distanceMeters,maxspeed:way.maxspeed};}}}state.currentMaxSpeed=best&&best.distance<=45?best.maxspeed:null;return state.currentMaxSpeed;}
export function getUpcomingSignal(progress){const signals=state.roadContext?.signals||[];const along=progress?.alongMeters||0;return signals.map(signal=>({...signal,distanceAhead:signal.alongMeters-along})).filter(signal=>signal.distanceAhead>40&&signal.distanceAhead<900).sort((a,b)=>a.distanceAhead-b.distanceAhead)[0]||null;}
function buildQuery(bbox){const b=`${bbox.south},${bbox.west},${bbox.north},${bbox.east}`;return`[out:json][timeout:25];(way["highway"]["maxspeed"](${b});node["highway"="traffic_signals"](${b}););out body geom;`;}
async function runOverpass(query){for(const endpoint of OVERPASS_ENDPOINTS){try{const response=await fetchWithTimeout(endpoint,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:query},9000);if(!response.ok)continue;return await response.json();}catch(error){console.warn('Road context Overpass failed',endpoint,error);}}throw new Error('Road context unavailable');}
function routeBbox(geometry,padding){let south=Infinity,west=Infinity,north=-Infinity,east=-Infinity;for(const point of geometry){const lng=point[0],lat=point[1];south=Math.min(south,lat);north=Math.max(north,lat);west=Math.min(west,lng);east=Math.max(east,lng);}return{south:south-padding,west:west-padding,north:north+padding,east:east+padding};}
function parseMaxspeed(value){if(!value)return null;const text=String(value).toLowerCase();if(text.includes('walk'))return 10;if(text.includes('signals'))return null;if(text.includes('none'))return 130;const match=text.match(/\d+/);if(!match)return null;let speed=Number(match[0]);if(text.includes('mph'))speed=Math.round(speed*1.60934);if(speed<5||speed>140)return null;return speed;}
function attachAlongRoute(signals,geometry){return signals.map(signal=>{let best=Infinity,along=0,cumulative=0;for(let i=1;i<geometry.length;i++){const a=geometry[i-1],b=geometry[i];const length=haversine(a[1],a[0],b[1],b[0]);const projected=projectPointToSegment(signal.lat,signal.lng,a[1],a[0],b[1],b[0]);if(projected.distanceMeters<best){best=projected.distanceMeters;along=cumulative+length*projected.t;}cumulative+=length;}return{...signal,distanceToRoute:best,alongMeters:along};}).filter(signal=>signal.distanceToRoute<=45);}
async function fetchWithTimeout(url,options,timeoutMs){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal});}finally{clearTimeout(timeout);}}
