import {state,SETTINGS_KEY} from "./state.js";
import {els} from "./dom.js";
import {applyPricesToStations,updateFuelBox,updateFuelMarkers} from "./fuel.js";
export function loadSettings(){try{state.settings={...state.settings,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}")} }catch{} state.settings.region="dk";}
export function renderSettings(){els.settingsBody.innerHTML=`
<section class="setting-section"><h3>Danmark</h3><p class="settings-note">USA-sporet er sat på pause. Denne version fokuserer på dansk navigation, danske stationer og danske prisdata.</p></section>
<section class="setting-section"><h3>Rutevalg</h3><label class="setting-option"><input id="routeFast" name="routeMode" type="radio">Hurtigste rute</label><label class="setting-option"><input id="routeEco" name="routeMode" type="radio">Mest økonomiske rute</label><p class="settings-note">Økonomisk rute vælger den mest brændstofvenlige af de alternative ruter OSRM returnerer.</p></section>
<section class="setting-section"><h3>Brændstoftype</h3><select id="fuelType"><option value="benzin95">Benzin 95 / E10</option><option value="benzin98">Benzin 98 / E5</option><option value="diesel">Diesel</option><option value="premiumDiesel">Premium diesel</option></select><p class="settings-note">Priser vises kun når prisdatakilden har valgt produkt på den konkrete station.</p></section>
<section class="setting-section"><h3>Navigation</h3><label class="setting-option"><input id="autoReroute" type="checkbox">Automatisk omdirigering</label><label class="setting-option"><input id="greenWave" type="checkbox">Anbefalet hastighed / GreenWave</label></section>`;syncSettings();}
export function openSettings(){renderSettings();els.settingsPanel.classList.remove("hidden");els.settingsBackdrop.classList.remove("hidden");}
export function closeSettings(){els.settingsPanel.classList.add("hidden");els.settingsBackdrop.classList.add("hidden");}
export function saveSettingsFromControls(){state.settings.region="dk";state.settings.routeMode=document.getElementById("routeEco").checked?"eco":"fast";state.settings.fuelType=document.getElementById("fuelType").value;state.settings.autoRerouteEnabled=document.getElementById("autoReroute").checked;state.settings.greenWaveEnabled=document.getElementById("greenWave").checked;localStorage.setItem(SETTINGS_KEY,JSON.stringify(state.settings));closeSettings();if(state.fuelStations?.length){applyPricesToStations();updateFuelBox();updateFuelMarkers();}}
function syncSettings(){document.getElementById("routeFast").checked=(state.settings.routeMode||"fast")==="fast";document.getElementById("routeEco").checked=state.settings.routeMode==="eco";document.getElementById("fuelType").value=state.settings.fuelType||"benzin95";document.getElementById("autoReroute").checked=state.settings.autoRerouteEnabled;document.getElementById("greenWave").checked=state.settings.greenWaveEnabled;}
