const OVERPASS_ENDPOINTS=["https://overpass-api.de/api/interpreter","https://overpass.kumi.systems/api/interpreter","https://overpass.osm.ch/api/interpreter"];
export default async function handler(req,res){
  res.setHeader("Cache-Control","no-store");res.setHeader("Access-Control-Allow-Origin","*");
  if(req.method!=="POST")return res.status(405).json({ok:false,error:"POST only"});
  try{
    const geometry=normalizeGeometry(req.body?.geometry),fuelType=String(req.body?.fuelType||"benzin95"),maxDetourMeters=clamp(Number(req.body?.maxDetourMeters||2000),500,20000),fuelAlongMeters=clamp(Number(req.body?.fuelAlongMeters||50000),1000,250000);
    if(geometry.length<2)return res.status(400).json({ok:false,error:"Missing route geometry"});
    const [osmRes,priceRes]=await Promise.allSettled([fetchOsmFuel(geometry,maxDetourMeters),fetchPrices(req)]);
    const errors=[],osmStations=osmRes.status==="fulfilled"?osmRes.value.stations:[],osmDebug=osmRes.status==="fulfilled"?osmRes.value.debug:{error:osmRes.reason?.message||String(osmRes.reason)};
    if(osmRes.status!=="fulfilled")errors.push(osmDebug.error);
    const prices=priceRes.status==="fulfilled"?priceRes.value:{stations:[],listPrices:{},sources:[]};
    if(priceRes.status!=="fulfilled")errors.push(priceRes.reason?.message||String(priceRes.reason));
    const apiStations=(prices.stations||[]).filter(s=>isLat(Number(s.lat))&&isLng(Number(s.lng))).map(s=>({...s,lat:Number(s.lat),lng:Number(s.lng),source:s.source||"price API"}));
    const apiWithoutCoords=(prices.stations||[]).length-apiStations.length,merged=dedupe([...osmStations,...apiStations]),attached=attachRouteDistances(merged,geometry);
    const stations=attached.filter(s=>s.distanceToRoute<=maxDetourMeters).filter(s=>s.distanceAlongRoute<=fuelAlongMeters).map(s=>attachPrice(s,prices,fuelType)).sort(sortStations);
    return res.status(200).json({ok:true,input:{fuelType,maxDetourMeters,fuelAlongMeters,geometryPoints:geometry.length},counts:{osmStations:osmStations.length,apiStations:apiStations.length,apiWithoutCoords,merged:merged.length,returned:stations.length,priced:stations.filter(s=>Number.isFinite(s.price)).length},sources:prices.sources||[],debug:{...osmDebug,errors,nearestRaw:attached.sort((a,b)=>a.distanceToRoute-b.distanceToRoute).slice(0,8).map(s=>({name:s.name,brand:s.brand,distanceToRoute:Math.round(s.distanceToRoute),distanceAlongRoute:Math.round(s.distanceAlongRoute)}))},stations:stations.slice(0,100).map(s=>({id:s.id,name:s.name,brand:s.brand,lat:s.lat,lng:s.lng,addressText:s.addressText||s.address||"",city:s.city||"",distanceToRoute:Math.round(s.distanceToRoute),distanceAlongRoute:Math.round(s.distanceAlongRoute),price:Number.isFinite(s.price)?s.price:null,priceProduct:s.priceProduct||null,priceSource:s.priceSource||null}))});
  }catch(e){return res.status(500).json({ok:false,error:e.message,stack:e.stack});}
}
async function fetchOsmFuel(geometry,maxDetourMeters){
  const bbox=routeBbox(geometry,clamp(maxDetourMeters/111320+0.08,0.09,0.22));
  const bboxQuery=`[out:json][timeout:45];(node["amenity"="fuel"](${bbox.south},${bbox.west},${bbox.north},${bbox.east});way["amenity"="fuel"](${bbox.south},${bbox.west},${bbox.north},${bbox.east});relation["amenity"="fuel"](${bbox.south},${bbox.west},${bbox.north},${bbox.east}););out center tags;`;
  const samples=sampleRoute(geometry,3500,24),radius=clamp(maxDetourMeters+2500,3000,9000);
  const aroundQuery=`[out:json][timeout:45];(${samples.map(p=>`node(around:${Math.round(radius)},${p.lat},${p.lng})["amenity"="fuel"];way(around:${Math.round(radius)},${p.lat},${p.lng})["amenity"="fuel"];relation(around:${Math.round(radius)},${p.lat},${p.lng})["amenity"="fuel"];`).join("")});out center tags;`;
  const attempts=[];let all=[];
  for(const [name,query]of[["bbox",bboxQuery],["around",aroundQuery]])for(const method of["POST","GET"]){try{const data=await overpass(query,method,26000);const n=Array.isArray(data.elements)?data.elements.length:0;attempts.push({name,method,ok:true,rawElements:n});if(n)all.push(...data.elements);}catch(e){attempts.push({name,method,ok:false,error:e.message});}}
  const stations=dedupe(all.map(normalizeOsmFuel).filter(Boolean));
  return{stations,debug:{bbox,samples:samples.length,radius,attempts,rawElements:all.length,normalizedStations:stations.length}};
}
async function fetchPrices(req){const r=await fetch(`${origin(req)}/api/fuel-prices?v=${Date.now()}`,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`/api/fuel-prices ${r.status}`);return await r.json();}
function origin(req){const host=req.headers["x-forwarded-host"]||req.headers.host||process.env.VERCEL_URL;const proto=req.headers["x-forwarded-proto"]||"https";return`${proto}://${host}`;}
async function overpass(query,method,timeoutMs){const errors=[];for(const endpoint of OVERPASS_ENDPOINTS){try{const controller=new AbortController(),t=setTimeout(()=>controller.abort(),timeoutMs);const options=method==="GET"?{signal:controller.signal}:{method:"POST",headers:{"Content-Type":"text/plain;charset=UTF-8"},body:query,signal:controller.signal};const url=method==="GET"?`${endpoint}?data=${encodeURIComponent(query)}`:endpoint;const r=await fetch(url,options);clearTimeout(t);if(r.ok)return await r.json();errors.push(`${endpoint} ${method} HTTP ${r.status}`);}catch(e){errors.push(`${endpoint} ${method} ${e.message}`);}}throw new Error(errors.join(" | "));}
function normalizeOsmFuel(el){const lat=typeof el.lat==="number"?el.lat:el.center?.lat,lng=typeof el.lon==="number"?el.lon:el.center?.lon;if(!isLat(lat)||!isLng(lng))return null;const t=el.tags||{};return{id:`${el.type}-${el.id}`,source:"OSM",lat,lng,name:t.name||t.brand||t.operator||"Tankstation",brand:t.brand||t.operator||t.name||"",addressText:[t["addr:street"],t["addr:housenumber"]].filter(Boolean).join(" "),postalCode:t["addr:postcode"]||"",city:t["addr:city"]||""};}
function attachPrice(station,prices,fuelType){const product=chooseProduct(station.prices||[],fuelType);if(product)return{...station,price:Number(product.price),priceProduct:product.productName||product.displayName||product.fuelType,priceSource:station.source};const brand=norm(`${station.brand} ${station.name}`);if(brand.includes("circle")||brand.includes("ingo")){const p=prices.listPrices?.[fuelType];if(p&&Number.isFinite(Number(p.price)))return{...station,price:Number(p.price),priceProduct:p.productName||fuelType,priceSource:p.source};}return{...station,price:null};}
function chooseProduct(prices,fuelType){const items=prices.filter(p=>Number.isFinite(Number(p.price))),text=p=>norm(`${p.code} ${p.octane} ${p.fuelType} ${p.productName} ${p.displayName}`);if(fuelType==="diesel")return items.find(p=>/diesel/.test(text(p))&&!/premium|plus|extra|hvo/.test(text(p)))||items.find(p=>/diesel/.test(text(p)))||null;if(fuelType==="premiumDiesel")return items.find(p=>/diesel/.test(text(p))&&/premium|plus|extra/.test(text(p)))||items.find(p=>/diesel/.test(text(p)))||null;if(fuelType==="benzin98")return items.find(p=>/98|100|e5/.test(text(p))&&!/diesel/.test(text(p)))||null;return items.find(p=>/95|e10|benzin|gasoline|petrol/.test(text(p))&&!/98|100|premium|diesel/.test(text(p)))||items.find(p=>/benzin|gasoline|petrol/.test(text(p))&&!/diesel/.test(text(p)))||null;}
function attachRouteDistances(stations,geometry){const seg=[];let cum=0;for(let i=1;i<geometry.length;i++){const a=geometry[i-1],b=geometry[i],len=haversine(a[1],a[0],b[1],b[0]);seg.push({a,b,cum,len});cum+=len;}return stations.map(s=>{let best=Infinity,along=Infinity;for(const x of seg){const p=project(s.lat,s.lng,x.a[1],x.a[0],x.b[1],x.b[0]);if(p.d<best){best=p.d;along=x.cum+x.len*p.t;}}return{...s,distanceToRoute:best,distanceAlongRoute:along};});}
function normalizeGeometry(g){return(Array.isArray(g)?g:[]).map(p=>Array.isArray(p)?[Number(p[0]),Number(p[1])]:[Number(p.lng??p.lon),Number(p.lat)]).filter(p=>isLng(p[0])&&isLat(p[1]));}
function routeBbox(g,pad){let s=Infinity,w=Infinity,n=-Infinity,e=-Infinity;for(const p of g){w=Math.min(w,p[0]);e=Math.max(e,p[0]);s=Math.min(s,p[1]);n=Math.max(n,p[1]);}return{south:s-pad,west:w-pad,north:n+pad,east:e+pad};}
function sampleRoute(g,spacing,max){const pts=[{lng:g[0][0],lat:g[0][1]}];let acc=0;for(let i=1;i<g.length;i++){acc+=haversine(g[i-1][1],g[i-1][0],g[i][1],g[i][0]);if(acc>=spacing){pts.push({lng:g[i][0],lat:g[i][1]});acc=0;}if(pts.length>=max-1)break;}const last=g[g.length-1];pts.push({lng:last[0],lat:last[1]});return pts;}
function sortStations(a,b){if(Number.isFinite(a.price)&&Number.isFinite(b.price))return a.price-b.price;if(Number.isFinite(a.price))return-1;if(Number.isFinite(b.price))return 1;return a.distanceAlongRoute-b.distanceAlongRoute;}
function project(lat,lng,lat1,lng1,lat2,lng2){const ml=111320,mg=111320*Math.cos(lat*Math.PI/180),px=lng*mg,py=lat*ml,ax=lng1*mg,ay=lat1*ml,bx=lng2*mg,by=lat2*ml,dx=bx-ax,dy=by-ay,len=dx*dx+dy*dy;if(!len)return{t:0,d:Math.hypot(px-ax,py-ay)};let t=((px-ax)*dx+(py-ay)*dy)/len;t=clamp(t,0,1);return{t,d:Math.hypot(px-(ax+t*dx),py-(ay+t*dy))};}
function haversine(a,b,c,d){const R=6371000,rad=x=>x*Math.PI/180,A=rad(c-a),B=rad(d-b),x=Math.sin(A/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(B/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function dedupe(items){const seen=new Set();return items.filter(x=>{const k=x.id||`${Math.round(x.lat*10000)}:${Math.round(x.lng*10000)}`;if(seen.has(k))return false;seen.add(k);return true;});}
function isLat(v){return Number.isFinite(v)&&v>=54.2&&v<=58.2}function isLng(v){return Number.isFinite(v)&&v>=7.5&&v<=15.8}function clamp(v,a,b){return Math.max(a,Math.min(b,v));}function norm(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/æ/g,"ae").replace(/ø/g,"oe").replace(/å/g,"aa").replace(/[^a-z0-9]+/g," ").trim();}
