
const CIRCLEK_URL='https://api.circlek.com/eu/prices/v1/fuel/countries/DK';
const OK_URL='https://mobility-prices.ok.dk/api/v1/fuel-prices';
export default async function handler(request,response){response.setHeader('Cache-Control','s-maxage=120, stale-while-revalidate=900');response.setHeader('Access-Control-Allow-Origin','*');const [circleK,ok]=await Promise.allSettled([fetchCircleK(),fetchOK()]);const sources=[],stations=[];if(circleK.status==='fulfilled'){sources.push({id:'circlek-ingo-dk',name:'Circle K / INGO',ok:true,stations:circleK.value.length});stations.push(...circleK.value)}else sources.push({id:'circlek-ingo-dk',name:'Circle K / INGO',ok:false,error:circleK.reason?.message||String(circleK.reason)});if(ok.status==='fulfilled'){sources.push({id:'ok-dk',name:'OK',ok:true,stations:ok.value.length});stations.push(...ok.value)}else sources.push({id:'ok-dk',name:'OK',ok:false,error:ok.reason?.message||String(ok.reason)});response.status(200).json({schemaVersion:1,generatedAt:new Date().toISOString(),sources,stations:dedupe(stations)})}
async function fetchCircleK(){const r=await fetch(CIRCLEK_URL,{headers:{Accept:'application/json','X-App-Name':'PRICES'}});if(!r.ok)throw new Error(`Circle K HTTP ${r.status}`);const data=await r.json();const sites=Array.isArray(data.sites)?data.sites:[];return sites.map(site=>{const prices=normalizePrices(site.fuelPrices||site.prices||site.fuels||[]);if(!prices.length)return null;const address=site.address||{};const brand=String(site.name||'').toLowerCase().includes('ingo')?'INGO':'Circle K';return{source:'Circle K / INGO',sourceId:'circlek-ingo-dk',stationId:String(site.id||site.siteId||''),name:site.name||brand,brand,addressText:[address.street,address.houseNumber].filter(Boolean).join(' '),postalCode:String(address.postalCode||''),city:address.city||'',lat:parseNumber(site.latitude||site.lat||site.coordinates?.latitude||site.location?.lat),lng:parseNumber(site.longitude||site.lng||site.coordinates?.longitude||site.location?.lng),prices}}).filter(Boolean)}
async function fetchOK(){const r=await fetch(OK_URL,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`OK HTTP ${r.status}`);const data=await r.json();const items=Array.isArray(data.items)?data.items:Array.isArray(data)?data:[];return items.map(item=>{const prices=normalizePrices(item.prices||item.fuelPrices||[]);if(!prices.length)return null;return{source:'OK',sourceId:'ok-dk',stationId:String(item.facility_number||item.id||''),name:item.name||'OK',brand:'OK',addressText:[item.street,item.house_number].filter(Boolean).join(' '),postalCode:String(item.postal_code||item.postalCode||''),city:item.city||'',lat:parseNumber(item.coordinates?.latitude||item.lat||item.latitude),lng:parseNumber(item.coordinates?.longitude||item.lng||item.longitude),prices}}).filter(Boolean)}
function normalizePrices(prices){if(!Array.isArray(prices))return[];return prices.map(p=>({code:p.code||p.productCode||p.id||'',displayName:p.displayName||p.name||p.productName||p.product_name||p.fuelType||'',productName:p.productName||p.product_name||p.displayName||p.name||p.fuelType||'',fuelType:p.fuelType||p.productName||p.product_name||p.displayName||p.name||'',octane:p.octane||'',price:parseNumber(p.price||p.amount||p.value),currency:p.currency||'DKK',lastUpdated:p.lastUpdated||p.updatedAt||p.validFrom||null})).filter(p=>Number.isFinite(p.price))}
function parseNumber(v){if(v===undefined||v===null||v==='')return NaN;const n=Number(String(v).replace(',','.'));return Number.isFinite(n)?n:NaN}
function dedupe(stations){const seen=new Set();return stations.filter(s=>{const key=`${s.sourceId}:${s.stationId}:${s.postalCode}:${s.addressText}`;if(seen.has(key))return false;seen.add(key);return true})}
