const CIRCLEK_COUNTRY_URL='https://api.circlek.com/eu/prices/v1/fuel/countries/DK';
const CIRCLEK_SITE_URL='https://api.circlek.com/eu/prices/v1/fuel/sites/';
const OK_URL='https://mobility-prices.ok.dk/api/v1/fuel-prices';
export default async function handler(request,response){response.setHeader('Cache-Control','s-maxage=120, stale-while-revalidate=900');response.setHeader('Access-Control-Allow-Origin','*');const generatedAt=new Date().toISOString();const sources=[];let stations=[];const circleK=await safeFetch('circlek-dk-public-api','Circle K / INGO DK Fuel Prices API',fetchCircleK);sources.push(circleK.source);stations.push(...circleK.stations);const ok=await safeFetch('ok-dk-public-api','OK DK Fuel Prices API',fetchOK);sources.push(ok.source);stations.push(...ok.stations);stations=dedupeStations(stations);return response.status(200).json({schemaVersion:2,generatedAt,sources,stations});}
async function safeFetch(id,name,fetcher){try{const stations=await fetcher();return{source:{id,name,ok:true,stations:stations.length,fetchedAt:new Date().toISOString()},stations};}catch(error){return{source:{id,name,ok:false,error:error.message,fetchedAt:new Date().toISOString()},stations:[]};}}
async function fetchCircleK(){const response=await fetch(CIRCLEK_COUNTRY_URL,{headers:{Accept:'application/json','X-App-Name':'PRICES'}});if(!response.ok)throw new Error(`Circle K country HTTP ${response.status}`);const data=await response.json();const sites=Array.isArray(data.sites)?data.sites:[];const countryLevel=sites.map(site=>normalizeCircleKSite(site)).filter(Boolean);if(countryLevel.some(site=>site.prices.length))return countryLevel;const detailed=[];const concurrency=8;for(let i=0;i<sites.length;i+=concurrency){const batch=sites.slice(i,i+concurrency);const results=await Promise.allSettled(batch.map(site=>fetchCircleKSite(site.id||site.siteId)));for(const result of results){if(result.status==='fulfilled'&&result.value)detailed.push(result.value);}}return detailed;}
async function fetchCircleKSite(siteId){if(!siteId)return null;const response=await fetch(`${CIRCLEK_SITE_URL}${encodeURIComponent(siteId)}`,{headers:{Accept:'application/json','X-App-Name':'PRICES'}});if(!response.ok)return null;return normalizeCircleKSite(await response.json());}
function normalizeCircleKSite(site){if(!site)return null;const prices=normalizeGenericPrices(site.fuelPrices||site.prices||site.fuels||[]);if(!prices.length)return null;const address=site.address||{};const brand=detectCircleKBrand(site.name);return{source:'Circle K / INGO DK Fuel Prices API',sourceId:'circlek-dk-public-api',stationId:String(site.id||site.siteId||''),name:site.name||brand,brand,addressText:[address.street,address.houseNumber].filter(Boolean).join(' '),postalCode:String(address.postalCode||''),city:address.city||'',country:'DK',lat:parseCoordinate(site.latitude||site.lat||site.coordinates?.latitude||site.location?.lat),lng:parseCoordinate(site.longitude||site.lng||site.coordinates?.longitude||site.location?.lng),lastUpdated:latestUpdate(prices),prices};}
async function fetchOK(){const response=await fetch(OK_URL,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`OK HTTP ${response.status}`);const data=await response.json();const items=Array.isArray(data.items)?data.items:[];return items.map(item=>normalizeOKStation(item)).filter(Boolean);}
function normalizeOKStation(item){if(!item)return null;const prices=normalizeOKPrices(item.prices||[]);if(!prices.length)return null;return{source:'OK DK Fuel Prices API',sourceId:'ok-dk-public-api',stationId:String(item.facility_number||''),name:'OK',brand:'OK',addressText:[item.street,item.house_number].filter(Boolean).join(' '),postalCode:String(item.postal_code||''),city:item.city||'',country:'DK',lat:parseCoordinate(item.coordinates?.latitude),lng:parseCoordinate(item.coordinates?.longitude),lastUpdated:item.last_updated_time||latestUpdate(prices),prices};}
function normalizeOKPrices(prices){return prices.map(price=>({code:normalizeText(price.product_name||''),displayName:price.product_name||'',productName:price.product_name||'',fuelType:price.product_name||'',price:parsePrice(price.price),currency:'DKK',volumeUnit:'LITER',lastUpdated:null})).filter(price=>Number.isFinite(price.price));}
function normalizeGenericPrices(prices){if(!Array.isArray(prices))return[];return prices.map(price=>({code:price.code||price.productCode||price.id||'',displayName:price.displayName||price.name||price.productName||price.fuelType||'',productName:price.productName||price.displayName||price.name||price.fuelType||'',fuelType:price.fuelType||price.productName||price.displayName||price.name||'',octane:price.octane||'',price:parsePrice(price.price||price.amount||price.value),currency:price.currency||'DKK',volumeUnit:price.volumeUnit||price.unit||'LITER',lastUpdated:price.lastUpdated||price.updatedAt||price.validFrom||null})).filter(price=>Number.isFinite(price.price));}
function detectCircleKBrand(name){const normalized=String(name||'').toLowerCase();if(normalized.includes('ingo'))return'INGO';return'Circle K';}
function latestUpdate(prices){return prices.map(price=>price.lastUpdated).filter(Boolean).sort().at(-1)||null;}
function parseCoordinate(value){if(value===undefined||value===null||value==='')return null;const numeric=Number(String(value).replace(',','.'));return Number.isFinite(numeric)?numeric:null;}
function parsePrice(value){if(value===undefined||value===null||value==='')return NaN;const numeric=Number(String(value).replace(',','.'));return Number.isFinite(numeric)?numeric:NaN;}
function dedupeStations(stations){const seen=new Set();return stations.filter(station=>{const key=`${station.sourceId}:${station.stationId||station.name}:${station.postalCode}:${station.addressText}`;if(seen.has(key))return false;seen.add(key);return true;});}
function normalizeText(value){return String(value||'').toLowerCase().trim();}
