const CIRCLEK_LIST_PRICE_URL="https://www.circlek.dk/erhverv/braendstof/priser";
const CIRCLEK_COUNTRY_URL="https://api.circlek.com/eu/prices/v1/fuel/countries/DK";
export default async function handler(req,res){
  res.setHeader("Cache-Control","s-maxage=300, stale-while-revalidate=1800");
  res.setHeader("Access-Control-Allow-Origin","*");
  const [bulk,list]=await Promise.allSettled([fetchCircleKStations(),fetchCircleKListPrices()]);
  const sources=[];let stations=[];let listPrices={};
  if(bulk.status==="fulfilled"){stations=bulk.value;sources.push({id:"circlek-api",name:"Circle K / INGO station API",ok:true,stations:stations.length});}else sources.push({id:"circlek-api",name:"Circle K / INGO station API",ok:false,error:bulk.reason?.message||String(bulk.reason)});
  if(list.status==="fulfilled"){listPrices=list.value;sources.push({id:"circlek-list",name:"Circle K official list prices",ok:true,products:Object.values(listPrices).filter(Boolean).length});}else sources.push({id:"circlek-list",name:"Circle K official list prices",ok:false,error:list.reason?.message||String(list.reason)});
  res.status(200).json({ok:true,generatedAt:new Date().toISOString(),sources,stations,listPrices});
}
async function fetchCircleKStations(){const r=await fetch(CIRCLEK_COUNTRY_URL,{headers:{Accept:"application/json","X-App-Name":"PRICES"}});if(!r.ok)throw new Error(`Circle K API HTTP ${r.status}`);const data=await r.json();return (Array.isArray(data.sites)?data.sites:[]).map(normalizeCircleKSite).filter(Boolean);}
function normalizeCircleKSite(site){const address=site.address||{},coord=extractDanishCoordinates(site);return{id:`circlek-${site.id||site.siteId||site.name||`${coord?.lat}:${coord?.lng}`}`,source:"Circle K / INGO station API",sourceId:"circlek-api",stationId:String(site.id||site.siteId||""),name:site.name||"Circle K",brand:String(site.name||"").toLowerCase().includes("ingo")?"INGO":"Circle K",addressText:[address.street,address.houseNumber,address.addressLine1].filter(Boolean).join(" "),postalCode:String(address.postalCode||""),city:address.city||"",lat:coord?coord.lat:NaN,lng:coord?coord.lng:NaN,coordinateSource:coord?coord.source:"none",prices:normalizePrices(site.fuelPrices||site.prices||site.fuels||site.products||[])};}
function extractDanishCoordinates(site){const c=[["latitude/longitude",site.latitude,site.longitude],["lat/lng",site.lat,site.lng],["coordinates latitude/longitude",site.coordinates?.latitude,site.coordinates?.longitude],["coordinates lat/lng",site.coordinates?.lat,site.coordinates?.lng],["location lat/lng",site.location?.lat,site.location?.lng],["location latitude/longitude",site.location?.latitude,site.location?.longitude],["address coordinates",site.address?.coordinates?.latitude,site.address?.coordinates?.longitude],["address location",site.address?.location?.lat,site.address?.location?.lng]];if(Array.isArray(site.coordinates)){c.push(["coordinates array lng/lat",site.coordinates[1],site.coordinates[0]]);c.push(["coordinates array lat/lng",site.coordinates[0],site.coordinates[1]]);}for(const [source,a,b]of c){const p=coordPair(a,b,source);if(p)return p;}return null;}
function coordPair(a,b,source){a=num(a);b=num(b);if(!Number.isFinite(a)||!Number.isFinite(b))return null;if(isLat(a)&&isLng(b))return{lat:a,lng:b,source};if(isLat(b)&&isLng(a))return{lat:b,lng:a,source:`${source} swapped`};return null;}
function isLat(v){return v>=54.2&&v<=58.2}function isLng(v){return v>=7.5&&v<=15.8}
async function fetchCircleKListPrices(){const r=await fetch(CIRCLEK_LIST_PRICE_URL,{headers:{Accept:"text/html"}});if(!r.ok)throw new Error(`Circle K list HTTP ${r.status}`);const text=stripHtml(await r.text());return{benzin95:extractPrice(text,["Miles 95","miles95","Blyfri 95"]),benzin98:extractPrice(text,["Miles Plus 95","Miles+ 95","Miles Plus"]),diesel:extractPrice(text,["Miles Diesel","Diesel"]),premiumDiesel:extractPrice(text,["Miles Plus Diesel","Miles+ Diesel"])};}
function extractPrice(text,needles){for(const n of needles){const i=text.toLowerCase().indexOf(n.toLowerCase());if(i<0)continue;const vals=[...text.slice(i,i+900).matchAll(/(\d{1,2},\d{2})/g)].map(m=>num(m[1]));const p=vals.find(v=>v>=8&&v<=30);if(Number.isFinite(p))return{price:p,productName:n,source:"Circle K official list prices"};}return null;}
function normalizePrices(prices){return Array.isArray(prices)?prices.map(p=>({code:p.code||p.productCode||p.id||"",displayName:p.displayName||p.name||p.productName||p.fuelType||"",productName:p.productName||p.displayName||p.name||p.fuelType||"",fuelType:p.fuelType||p.productName||p.displayName||p.name||"",octane:p.octane||"",price:num(p.price||p.amount||p.value),currency:p.currency||"DKK"})).filter(p=>Number.isFinite(p.price)):[];}
function stripHtml(html){return String(html||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ");}
function num(v){if(v===undefined||v===null||v==="")return NaN;return Number(String(v).replace(",","."));}
