const DAWA_AUTOCOMPLETE="https://api.dataforsyningen.dk/autocomplete";
const DAWA_ADRESSER="https://api.dataforsyningen.dk/adresser";
const NOMINATIM="https://nominatim.openstreetmap.org/search";
export default async function handler(req,res){
  res.setHeader("Cache-Control","s-maxage=86400, stale-while-revalidate=604800");
  res.setHeader("Access-Control-Allow-Origin","*");
  const q=String(req.query.q||req.query.address||"").trim(),limit=Math.max(1,Math.min(10,Number(req.query.limit||1))),mode=String(req.query.mode||"").toLowerCase();
  if(!q)return res.status(400).json(mode==="suggest"?[]:{ok:false,error:"Missing q"});
  const result=await geocodeAddress(q,limit);
  if(result.results.length){const results=result.results.map(normalizeOutput);const payload={ok:true,result:results[0],results,provider:results[0].provider,q,attempts:req.query.debug?result.attempts:undefined};return res.status(200).json(mode==="suggest"?results:payload);}
  return res.status(mode==="suggest"?200:404).json(mode==="suggest"?[]:{ok:false,error:"Address not found",message:`Address not found: ${q}`,q,results:[],attempts:result.attempts});
}
async function geocodeAddress(input,limit){const attempts=[];for(const fn of [tryDawaAutocomplete,tryDawaAdresser,tryNominatim]){const r=await fn(input,limit);attempts.push(r.attempt);if(r.results.length)return{results:r.results,attempts};}return{results:[],attempts};}
function variants(input){const clean=String(input).replace(/\s+/g," ").replace(/\s*,\s*/g,", ").trim(),noComma=clean.replace(/,/g," ").replace(/\s+/g," ").trim();const out=[clean,noComma,`${noComma}, Danmark`];const m=noComma.match(/^(.+?)\s+(\d{4})\s+(.+)$/);if(m){out.push(`${m[1]}, ${m[2]} ${m[3]}`);out.push(`${m[1]}, ${m[2]} ${m[3]}, Danmark`);}return[...new Set(out.filter(Boolean))];}
async function tryDawaAutocomplete(input,limit){const all=[];let last=null;for(const q of variants(input)){const url=`${DAWA_AUTOCOMPLETE}?q=${encodeURIComponent(q)}&type=adresse&caretpos=${q.length}&fuzzy=true&per_side=${Math.max(5,limit)}`;try{const r=await fetch(url,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`DAWA autocomplete HTTP ${r.status}`);const items=await r.json();last={provider:"DAWA autocomplete",ok:true,q,results:Array.isArray(items)?items.length:0};for(const item of Array.isArray(items)?items:[]){const n=fromDawaAuto(item,input);if(n)all.push(n);}if(all.length)break;}catch(e){return{attempt:{provider:"DAWA autocomplete",ok:false,q,error:e.message},results:[]};}}return{attempt:last||{provider:"DAWA autocomplete",ok:true,q:input,results:0},results:all.slice(0,limit)};}
async function tryDawaAdresser(input,limit){const all=[];let last=null;for(const q of variants(input)){const url=`${DAWA_ADRESSER}?q=${encodeURIComponent(q)}&struktur=mini&per_side=${Math.max(5,limit)}`;try{const r=await fetch(url,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`DAWA adresser HTTP ${r.status}`);const items=await r.json();last={provider:"DAWA adresser",ok:true,q,results:Array.isArray(items)?items.length:0};for(const item of Array.isArray(items)?items:[]){const n=fromDawaAddress(item,input);if(n)all.push(n);}if(all.length)break;}catch(e){return{attempt:{provider:"DAWA adresser",ok:false,q,error:e.message},results:[]};}}return{attempt:last||{provider:"DAWA adresser",ok:true,q:input,results:0},results:all.slice(0,limit)};}
async function tryNominatim(input,limit){const all=[];let last=null;for(const q of variants(input)){const url=`${NOMINATIM}?format=jsonv2&addressdetails=1&countrycodes=dk&limit=${Math.max(5,limit)}&q=${encodeURIComponent(q)}`;try{const r=await fetch(url,{headers:{Accept:"application/json","User-Agent":"GreenWave-DK/1.0"}});if(!r.ok)throw new Error(`Nominatim HTTP ${r.status}`);const items=await r.json();last={provider:"Nominatim",ok:true,q,results:Array.isArray(items)?items.length:0};for(const item of Array.isArray(items)?items:[]){const lat=Number(item.lat),lng=Number(item.lon);if(Number.isFinite(lat)&&Number.isFinite(lng))all.push({provider:"Nominatim",lat,lng,displayName:item.display_name||input,raw:item});}if(all.length)break;}catch(e){return{attempt:{provider:"Nominatim",ok:false,q,error:e.message},results:[]};}}return{attempt:last||{provider:"Nominatim",ok:true,q:input,results:0},results:all.slice(0,limit)};}
function fromDawaAuto(item,fallback){const d=item?.data||{},lat=Number(d.y),lng=Number(d.x);if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;return{provider:"DAWA autocomplete",lat,lng,displayName:item.tekst||d.betegnelse||fallback,dawaId:d.id||null,raw:item};}
function fromDawaAddress(item,fallback){const c=item?.adgangsadresse?.adgangspunkt?.koordinater||item?.adgangspunkt?.koordinater;if(!Array.isArray(c))return null;const lng=Number(c[0]),lat=Number(c[1]);if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;return{provider:"DAWA adresser",lat,lng,displayName:item.betegnelse||fallback,dawaId:item.id||null,raw:item};}
function normalizeOutput(item){return{provider:item.provider,lat:Number(item.lat),lng:Number(item.lng),lon:Number(item.lng),label:item.displayName||item.label||"",displayName:item.displayName||item.label||"",dawaId:item.dawaId||null,raw:item.raw||null};}
